In [1]:
import pandas as pd
import numpy as np
import requests
#dfs = pd.read_csv(
#    "https://raw.githubusercontent.com/dylanmalis-collab/Exoplanet_Life/refs/heads/Machine_Learning/PSCompPars_2026.03.19_06.16.51.csv")
#dfs.head()

In [2]:
url = "https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+*+from+pscomppars&format=csv"

df1 = pd.read_csv(url)

df1.head()

C:\Users\berna\AppData\Local\Temp\ipykernel_19600\3133681681.py:3: DtypeWarning: Columns (0: hd_name, 1: hip_name, 2: pl_orbtperstr, 3: pl_orbtper_reflink, 4: pl_occdepstr, 5: pl_occdep_reflink, 6: pl_orbtper_systemref, 7: pl_projobliqstr, 8: pl_trueobliqstr, 9: pl_trueobliq_reflink, 10: st_log_rhkstr, 11: st_log_rhk_reflink, 12: sy_icmagstr, 13: pl_cmassjstr, 14: pl_cmassj_reflink, 15: pl_cmassestr, 16: pl_cmasse_reflink, 17: pl_msinijstr, 18: pl_msinij_reflink, 19: pl_msiniestr, 20: pl_msinie_reflink, 21: pl_projobliq_reflink) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv(url)

,objectid,pl_name,pl_letter,hostid,hostname,hd_name,hip_name,tic_id,disc_pubdate,disc_year,...,cb_flag,pl_angsep,pl_angseperr1,pl_angseperr2,pl_angseplim,pl_angsepformat,pl_angsepstr,pl_angsepsymerr,pl_angsep_reflink,pl_ndispec
0,3.2390,Kepler-1167 b,b,2.136990,Kepler-1167,NaN,NaN,TIC 273875149,2016-05,2016.0,...,0,0.0213,NaN,NaN,0.0,NaN,0.0213,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
1,3.1444,Kepler-1740 b,b,2.433343,Kepler-1740,NaN,NaN,TIC 138479461,2022-02,2021.0,...,0,0.0734,NaN,NaN,0.0,NaN,0.0734,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
2,3.4135,Kepler-1581 b,b,2.442550,Kepler-1581,NaN,NaN,TIC 121215710,2016-05,2016.0,...,0,0.1390,NaN,NaN,0.0,NaN,0.1390,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
3,3.6590,Kepler-644 b,b,2.512738,Kepler-644,NaN,NaN,TIC 271669616,2016-05,2016.0,...,0,0.0352,NaN,NaN,0.0,NaN,0.0352,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
4,3.1575,Kepler-1752 b,b,2.507010,Kepler-1752,NaN,NaN,TIC 417655835,2022-02,2021.0,...,0,0.2800,NaN,NaN,0.0,NaN,0.2800,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0

In [3]:
df1["st_spectype"].isna().sum()

np.int64(3845)

In [6]:
url2 = "https://raw.githubusercontent.com/dylanmalis-collab/Exoplanet_Life/refs/heads/Machine_Learning/exoplanet_hosts_spectype.csv"

df2 = pd.read_csv(url2)

In [7]:
df2.head()

   hostname st_spectype
0    11 Com      G8 III
1    11 UMi      K4 III
2    14 And      K0 III
3    14 Her         K0V
4  16 Cyg B        G3 V

In [8]:
df1.loc[df1["hostname"] == "KOI-1783", "st_spectype"]

4403    NaN
5932    NaN
Name: st_spectype, dtype: str

In [12]:
df2["st_spectype"].isna().sum()

np.int64(2200)

In [13]:
df2.shape

(6147, 2)

In [9]:
df2.loc[df2["hostname"] == "KOI-1783", "st_spectype"]

2090    K5
2091    K5
Name: st_spectype, dtype: str

In [10]:
df = df1.merge(
    df2[['hostname', 'st_spectype']],
    on='hostname',
    how='left',
    suffixes=('', '_new')
)

# Remplacer uniquement les NaN de df1 par les valeurs de df2
df['st_spectype'] = df['st_spectype'].fillna(df['st_spectype_new'])

# Supprimer la colonne temporaire
df = df.drop(columns=['st_spectype_new'])

In [11]:
df["st_spectype"].isna().sum()

np.int64(3353)

In [91]:
df[df["pl_bmasse"] <= 5].head(20)

,objectid,pl_name,pl_letter,hostid,hostname,hd_name,hip_name,tic_id,disc_pubdate,disc_year,disc_method,discoverymethod,disc_locale,disc_facility,disc_instrument,disc_telescope,disc_refname,ra,raerr1,raerr2,rasymerr,rastr,ra_solnid,ra_reflink,dec,decerr1,decerr2,decsymerr,decstr,dec_solnid,dec_reflink,glon,glonerr1,glonerr2,glonsymerr,glonstr,glon_solnid,glon_reflink,glat,glaterr1,glaterr2,glatsymerr,glatstr,glat_solnid,glat_reflink,elon,elonerr1,elonerr2,elonsymerr,elonstr,elon_solnid,elon_reflink,elat,elaterr1,elaterr2,elatsymerr,elat_solnid,elat_reflink,elatstr,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbpersymerr,pl_orbperlim,pl_orbperstr,pl_orbperformat,pl_orbper_solnid,pl_orbper_reflink,pl_orblpererr1,pl_orblper,pl_orblpererr2,pl_orblpersymerr,pl_orblperlim,pl_orblperstr,pl_orblperformat,pl_orblper_solnid,pl_orblper_reflink,pl_orbsmax,pl_orbsmaxerr1,pl_orbsmaxerr2,pl_orbsmaxsymerr,pl_orbsmaxlim,pl_orbsmaxstr,pl_orbsmaxformat,pl_orbsmax_solnid,pl_orbsmax_reflink,pl_orbincl,pl_orbinclerr1,pl_orbinclerr2,pl_orbinclsymerr,pl_orbincllim,pl_orbinclstr,pl_orbinclformat,pl_orbincl_solnid,pl_orbincl_reflink,pl_orbtper,pl_orbtpererr1,pl_orbtpererr2,pl_orbtpersymerr,pl_orbtperlim,pl_orbtperstr,pl_orbtperformat,pl_orbtper_solnid,pl_orbtper_reflink,pl_orbeccen,pl_orbeccenerr1,pl_orbeccenerr2,pl_orbeccensymerr,pl_orbeccenlim,pl_orbeccenstr,pl_orbeccenformat,pl_orbeccen_solnid,pl_orbeccen_reflink,pl_eqt,pl_eqterr1,pl_eqterr2,pl_eqtsymerr,pl_eqtlim,pl_eqtstr,pl_eqtformat,pl_eqt_solnid,pl_eqt_reflink,pl_occdep,pl_occdeperr1,pl_occdeperr2,pl_occdepsymerr,pl_occdeplim,pl_occdepstr,pl_occdepformat,pl_occdep_solnid,pl_occdep_reflink,pl_insol,pl_insolerr1,pl_insolerr2,pl_insolsymerr,pl_insollim,pl_insolstr,pl_insolformat,pl_insol_solnid,pl_insol_reflink,pl_dens,pl_denserr1,sy_umagerr1,sy_umagerr2,sy_umaglim,sy_umagsymerr,sy_umagstr,sy_umagformat,sy_umag_solnid,sy_umag_reflink,sy_rmag,sy_rmagerr1,sy_rmagerr2,sy_rmaglim,sy_rmagsymerr,sy_rmagstr,sy_rmagformat,sy_rmag_solnid,sy_rmag_reflink,sy_imag,sy_imagerr1,sy_imagerr2,sy_imaglim,sy_imagsymerr,sy_imagstr,sy_imagformat,sy_imag_solnid,sy_imag_reflink,sy_zmag,sy_zmagerr1,sy_zmagerr2,sy_zmaglim,sy_zmagsymerr,sy_zmagstr,sy_zmagformat,sy_zmag_solnid,sy_zmag_reflink,sy_w1mag,sy_w1magerr1,sy_w1magerr2,sy_w1maglim,sy_w1magsymerr,sy_w1magstr,sy_w1magformat,sy_w1mag_solnid,sy_w1mag_reflink,sy_w2mag,sy_w2magerr1,sy_w2magerr2,sy_w2maglim,sy_w2magsymerr,sy_w2magstr,sy_w2magformat,sy_w2mag_solnid,sy_w2mag_reflink,sy_w3mag,sy_w3magerr1,sy_w3magerr2,sy_w3maglim,sy_w3magsymerr,sy_w3magstr,sy_w3magformat,sy_w3mag_solnid,sy_w3mag_reflink,sy_w4mag,sy_w4magerr1,sy_w4magerr2,sy_w4maglim,sy_w4magsymerr,sy_w4magstr,sy_w4magformat,sy_w4mag_solnid,sy_w4mag_reflink,sy_gmag,sy_gmagerr1,sy_gmagerr2,sy_gmaglim,sy_gmagsymerr,sy_gmagstr,sy_gmagformat,sy_gmag_solnid,sy_gmag_reflink,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2,sy_gaiamaglim,sy_gaiamagsymerr,sy_gaiamagstr,sy_gaiamagformat,sy_gaiamag_solnid,sy_gaiamag_reflink,sy_tmag,sy_tmagerr1,sy_tmagerr2,sy_tmaglim,sy_tmagsymerr,sy_tmagstr,sy_tmagformat,sy_tmag_solnid,sy_tmag_reflink,sy_name,pl_controv_flag,pl_orbtper_systemref,pl_tranmid_systemref,st_metratio,st_spectype,st_spectype_solnid,st_spectype_reflink,sy_plxlim,sy_kepmag,sy_kepmagerr1,sy_kepmagerr2,sy_kepmaglim,sy_kepmagsymerr,sy_kepmagstr,sy_kepformat,sy_kepmag_solnid,sy_kepmag_reflink,st_rotp,st_rotperr1,st_rotperr2,st_rotpsymerr,st_rotplim,st_rotpstr,st_rotpformat,st_rotp_solnid,st_rotp_reflink,pl_projobliq,pl_projobliqerr1,pl_projobliqerr2,pl_projobliqsymerr,pl_projobliqlim,pl_projobliqstr,pl_projobliqformat,pl_denserr2,pl_denssymerr,pl_denslim,pl_densstr,pl_densformat,pl_dens_solnid,pl_dens_reflink,pl_trandep,pl_trandeperr1,pl_trandeperr2,pl_trandepsymerr,pl_trandeplim,pl_trandepstr,pl_trandepformat,pl_trandep_solnid,pl_trandep_reflink,pl_tranmid,pl_tranmiderr1,pl_tranmiderr2,pl_tranmidsymerr,pl_tranmidlim,pl_tranmidstr,pl_tranmidformat,pl_tranmid_solnid,pl_tranmid_reflink,pl_trandur,pl_trandurerr1,pl_trandurerr2,pl_trandursymerr,pl_trandurlim,pl_trandurstr,pl_trandurformat,pl_trandur_solnid,pl_trandur_reflink,pl_rvamp,pl_rvamperr1,pl_rvamperr2,pl_rvampsymerr,pl_rvamplim,pl_rvampstr,pl_rvampformat,pl_rvamp_solnid,pl_rvamp_reflink,pl_radj,pl_radjerr1,pl_radjerr2,pl_radjsymerr,pl_radjlim,pl_radjstr,pl_radjformat,pl_radj_solnid,pl_radj_reflink,pl_rade,pl_radeerr1,pl_radeerr2,pl_radesymerr,pl_radelim,pl_radestr,pl_radeformat,pl_rade_solnid,pl_rade_reflink,pl_ratror,pl_ratrorerr1,pl_ratrorerr2,pl_ratrorsymerr,pl_ratrorlim,pl_ratrorstr,pl_ratrorformat,pl_ratror_solnid,pl_ratror_reflink,pl_ratdor,pl_trueobliq,pl_trueobliqerr1,pl_trueobliqerr2,pl_trueobliqsymerr,pl_trueobliqlim,pl_trueobliqstr,pl_trueobliqformat,pl_trueobliq_solnid,pl_trueobliq_reflink,st_log_rhk,st_log_rhkerr1,st_log_rhkerr2,st_log_rhksymerr,st_log_rhklim,st_log_rhkstr,st_log_rhkformat,st_log_rhk_solnid,st_log_rhk_reflink,st_metn,sy_icmag,sy_icmagerr1,sy_icmagerr2,sy_icmagsymerr,sy_icmagstr,sy_icmagformat,sy_icmag_solnid,sy_icmag_reflink,pl_pubdate,dkin_flag,pl_ratdorerr1,pl_ratdorerr2,pl_ratdorsymerr,pl_ratdorlim,pl_ratdorstr,pl_ratdorformat,pl_ratdor_solnid,pl_ratdor_reflink,pl_imppar,pl_impparerr1,pl_impparerr2,pl_impparsymerr,pl_impparlim,pl_impparstr,pl_impparformat,pl_imppar_solnid,pl_imppar_reflink,pl_cmassj,pl_cmassjerr1,pl_cmassjerr2,pl_cmassjsymerr,pl_cmassjlim,pl_cmassjstr,pl_cmassjformat,pl_cmassj_solnid,pl_cmassj_reflink,pl_cmasse,pl_cmasseerr1,pl_cmasseerr2,pl_cmassesymerr,pl_cmasselim,pl_cmassestr,pl_cmasseformat,pl_cmasse_solnid,pl_cmasse_reflink,pl_massj,pl_massjerr1,pl_massjerr2,pl_massjsymerr,pl_massjlim,pl_massjstr,pl_massjformat,pl_massj_solnid,pl_massj_reflink,pl_masse,pl_masseerr1,pl_masseerr2,pl_massesymerr,pl_masselim,pl_massestr,pl_masseformat,pl_masse_solnid,pl_masse_reflink,pl_bmassj,pl_bmassjerr1,pl_bmassjerr2,pl_bmassjsymerr,pl_bmassjlim,pl_bmassjstr,pl_bmassjformat,pl_bmassj_solnid,pl_bmassj_reflink,pl_bmasse,pl_bmasseerr1,pl_bmasseerr2,pl_bmassesymerr,pl_bmasselim,pl_bmassestr,pl_bmasseformat,pl_bmasse_solnid,pl_bmasse_reflink,pl_bmassprov,pl_msinij,pl_msinijerr1,pl_msinijerr2,pl_msinijsymerr,pl_msinijlim,pl_msinijstr,pl_msinijformat,pl_msinij_solnid,pl_msinij_reflink,pl_msinie,pl_msinieerr1,pl_msinieerr2,pl_msiniesymerr,pl_msinielim,pl_msiniestr,pl_msinieformat,pl_msinie_solnid,pl_msinie_reflink,st_teff,st_tefferr1,st_tefferr2,st_teffsymerr,st_tefflim,st_teffstr,st_teffformat,st_teff_solnid,st_teff_reflink,st_met,st_meterr1,st_meterr2,st_metsymerr,st_metlim,st_metstr,st_metformat,st_met_solnid,st_met_reflink,st_radv,st_radverr1,st_radverr2,st_radvsymerr,st_radvlim,st_radvstr,st_radvformat,st_radv_solnid,st_radv_reflink,st_vsin,st_vsinerr1,st_vsinerr2,st_vsinsymerr,st_vsinlim,st_vsinstr,st_vsin_solnid,st_vsin_reflink,st_vsinformat,st_lum,st_lumerr1,st_lumerr2,st_lumsymerr,st_lumlim,st_lumstr,st_lumformat,st_lum_solnid,st_lum_reflink,st_logg,st_loggerr1,st_loggerr2,st_loggsymerr,st_logglim,st_loggstr,st_loggformat,st_logg_solnid,st_logg_reflink,st_age,st_ageerr1,st_ageerr2,st_agesymerr,st_agelim,st_agestr,st_ageformat,st_age_solnid,st_age_reflink,st_mass,st_masserr1,st_masserr2,st_masssymerr,st_masslim,st_massstr,st_massformat,st_mass_solnid,st_mass_reflink,st_dens,st_denserr1,st_denserr2,st_denssymerr,st_denslim,st_densstr,st_densformat,st_dens_solnid,st_dens_reflink,st_rad,st_raderr1,st_raderr2,st_radsymerr,st_radlim,st_radstr,st_radformat,st_rad_solnid,st_rad_reflink,systemid,ttv_flag,ptv_flag,tran_flag,rv_flag,ast_flag,obm_flag,micro_flag,etv_flag,ima_flag,pul_flag,disc_refid,sy_snum,sy_pnum,sy_mnum,st_nphot,st_nrvc,st_nspec,pl_nespec,pl_ntranspec,pl_nnotes,sy_pm,sy_pmerr1,sy_pmerr2,sy_pmsymerr,sy_pmlim,sy_pmstr,sy_pmformat,sy_pm_solnid,sy_pm_reflink,sy_pmra,sy_pmraerr1,sy_pmraerr2,sy_pmrasymerr,sy_pmralim,sy_pmrastr,sy_pmraformat,sy_pmra_solnid,sy_pmra_reflink,sy_pmdec,sy_pmdecerr1,sy_pmdecerr2,sy_pmdecsymerr,sy_pmdeclim,sy_pmdecstr,sy_pmdecformat,sy_pmdec_solnid,sy_pmdec_reflink,sy_plx,sy_plxerr1,sy_plxerr2,sy_plxsymerr,sy_plxstr,sy_plxformat,sy_plx_solnid,sy_plx_reflink,sy_dist,sy_disterr1,sy_disterr2,sy_distsymerr,sy_distlim,sy_diststr,sy_distformat,sy_dist_solnid,sy_dist_reflink,sy_bmag,sy_bmagerr1,sy_bmagerr2,sy_bmaglim,sy_bmagsymerr,sy_bmagstr,sy_bmagformat,sy_bmag_solnid,sy_bmag_reflink,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_vmaglim,sy_vmagsymerr,sy_vmagstr,sy_vmagformat,sy_vmag_solnid,sy_vmag_reflink,sy_jmag,sy_jmagerr1,sy_jmagerr2,sy_jmaglim,sy_jmagsymerr,sy_jmagstr,sy_jmagformat,sy_jmag_solnid,sy_jmag_reflink,sy_hmag,sy_hmagerr1,sy_hmagerr2,sy_hmaglim,sy_hmagsymerr,sy_hmagstr,sy_hmagformat,sy_hmag_solnid,sy_hmag_reflink,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_kmaglim,sy_kmagsymerr,sy_kmagstr,sy_kmagformat,sy_kmag_solnid,sy_kmag_reflink,sy_umag,pl_projobliq_solnid,pl_projobliq_reflink,x,y,z,htm20,gaia_dr2_id,gaia_dr3_id,cb_flag,pl_angsep,pl_angseperr1,pl_angseperr2,pl_angseplim,pl_angsepformat,pl_angsepstr,pl_angsepsymerr,pl_angsep_reflink,pl_ndispec,Masse_10^24kg,Gravity_G_earth,Score_roch,pl_type,sim_earth,pl_insol_calc,eau_possible,st_spectype_group
0,3.23900,Kepler-1167 b,b,2.136990,Kepler-1167,NaN,NaN,TIC 273875149,2016-05,2016.0,tran,Transit,Space,Kepler,Kepler CCD Array,0.95 m Kepler Telescope,<a refstr=MORTON_ET_AL__2016 href=https://ui.a...,298.302660,8.146389e-09,-8.146389e-09,1,19h53m12.64s,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,47.693965,9.711167e-09,-9.711167e-09,1,+47d41m38.28s,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,81.68674,NaN,NaN,NaN,81.68674,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,10.23657,NaN,NaN,NaN,10.23657,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,321.97265,NaN,NaN,NaN,321.97265,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,66.10174,NaN,NaN,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,66.10174,1.003934,0.000003,-0.000003,1.0,0.0,1.003933739&plusmn;2.678e-06,NaN,3789.1,<a refstr=MORTON_ET_AL__2016 href=https://ui.a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.01750,NaN,NaN,NaN,0.0,.0175,NaN,4440.70767,<a refstr=Q1_Q17_DR25_KOI_TABLE href=https://e...,89.76000,NaN,NaN,NaN,0.0,89.76,NaN,4440.70767,<a refstr=Q1_Q17_DR25_KOI_TABLE href=https://e...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,NaN,NaN,NaN,0.0,0,NaN,4440.70767,<a refstr=Q1_Q17_DR25_KOI_TABLE href=https://e...,1419.0,NaN,NaN,NaN,0.0,1419,NaN,4440.70767,<a refstr=Q1_Q17_DR25_KOI_TABLE href=https://e...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1039.697000,79.399,-73.021,0.0,0.0,"<div><span class=supersubNumber"">1039.697</spa...",NaN,4194.10000,<a refstr=BERGER_ET_AL__2018 href=https://ui.a...,3.920000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,15.883,NaN,NaN,NaN,0.0,15.883,NaN,720.2,<a refstr=LATHAM_ET_AL__2005 href=https://ui.a...,15.5900,NaN,NaN,0.0,0.0,15.590,NaN,720.2,<a refstr=LATHAM_ET_AL__2005 href=https://ui.a...,15.3620,NaN,NaN,NaN,0.0,15.362,NaN,720.2,<a refstr=LATHAM_ET_AL__2005 href=https://ui.a...,13.616,0.024,-0.024,NaN,1.0,13.616&plusmn;0.024,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,13.712,0.029,-0.029,NaN,1.0,13.712&plusmn;0.029,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,13.273,NaN,NaN,NaN,0.0,13.273,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,9.294,NaN,NaN,NaN,0.0,9.294,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,16.7650,NaN,NaN,NaN,0.0,16.765,NaN,720.2,<a refstr=LATHAM_ET_AL__2005 href=https://ui.a...,15.92920,0.000562,-0.000562,NaN,1.0,15.929200&plusmn;0.000562,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,15.2776,0.009200,-0.009200,NaN,1.0,15.2776&plusmn;0.0092,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,Kepler-1167,0,NaN,JD,[Fe/H],NaN,NaN,NaN,0.0,15.942,NaN,NaN,NaN,0.0,15.942,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3.92,NaN,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0.04911,0.00238,-0.00238,NaN,0.0,0.04911&plusmn0.00238,NaN,4440.70767,<a refstr=Q1_Q17_DR25_KOI_TABLE href=https://e...,2.454965e+06,0.002490,-0.002490,1.0,0.0,2454965.09731&plusmn;0.00249,NaN,3789.10000,<a refstr=MORTON_ET_AL__2016 href=https://ui.a...,1.4562,0.0609,-0.0609,1.0,0.0,1.4562&plusmn;0.0609,NaN,3789.10000,<a refstr=MORTON_ET_AL__2016 href=https://ui.a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.152556,0.010706,-0.010706,1.0,0.0,0.153&plusmn;0.011,NaN,3789.1,<a refstr=MORTON_ET_AL__2016 href=https://ui.a...,1.710000,0.120,-0.120,1.0,0.0,1.71&plusmn;0.12,NaN,3789.1,<a refstr=MORTON_ET_AL__2016 href=https://ui.a...,0.021030,0.000932,-0.000737,0.0,0.0,"<div><span class=supersubNumber"">0.02103</span...",NaN,3789.10000,<a refstr=MORTON_ET_AL__2016 href=https://ui.a...,5.477000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,NaN,0,0.315000,-0.315000,NaN,0.0,5.477&plusmn;0.315,NaN,4440.70767,<a refstr=Q1_Q17_DR25_KOI_TABLE href=https://e...,0.0230,0.435,-0.0230,NaN,0.0,"<div><span class=supersubNumber"">0.023</span> ...",NaN,4440.70767,<a refstr=Q1_Q17_DR25_KOI_TABLE href=https://e...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.011200,NaN,NaN,NaN,0.0,0.0112,NaN,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,3.570,NaN,NaN,NaN,0.0,3.57,NaN,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,M-R relationship,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4971.0,96.57,-125.10,0.0,0.0,"<div><span class=supersubNumber"">4971.000</spa...",NaN,3789.10000,<a refstr=MORTON_ET_AL__2016 href=https://ui.a...,-0.0500,0.1630,-0.1750,0.0,0.0,"<div><span class=supersubNumber"">-0.0500</span...",NaN,3789.10000,<a refstr=MORTON_ET_AL__2016 href=https://ui.a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.53589,NaN,NaN,0.0,0.0,-0.5358931,NaN,4400.1,<a refstr=GAJDO_SCARON__ET_AL__2019 href=https...,4.600,0.026,-0.043,0.0,0.0,"<div><span class=supersubNumber"">4.600</span><...",NaN,3789.10000,<a refstr=MORTON_ET_AL__2016 href=https://ui.a...,4.27,6.20,-2.48,0.0,0.0,"<div><span class=supersubNumber"">4.270</span><...",NaN,3789.10000,<a refstr=MORTON_ET_AL__2016 href=https://ui.a...,0.790,0.040,-0.049,0.0,0.0,"<div><span class=supersubNumber"">0.790</span><...",NaN,3789.10000,<a refstr=MORTON_ET_AL__2016 href=https://ui.a...,2.858170,0.281460,-1.148190,NaN,0.0,"<div><span class=supersubNumber"">2.85817</span...",NaN,4439.63219,<a refstr=Q1_Q17_DR24_KOI_TABLE href=https://e...,0.750,0.040,-0.044,0.0,0.0,"<div><span class=supersubNumber"">0.750</span><...",NaN,3789.10000,<a refstr=MORTON_ET_AL__2016 href=https://ui.a...,1.136990,0,0,1,0,0,0,0,0,0,0,3789,1,1,0,0,0,0,0,0,1,15.464475,0.061569,-0.061569,1.0,NaN,15.4644749&plusmn;0.0615693,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,-10.791100,0.063013,-0.063013,1.0,NaN,-10.7911000&plusmn;0.0630132,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,-11.077100,0.060167,-0.060167,1.0,NaN,-11.0771000&plusmn;0.0601669,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,1.190750,0.036676,-0.036676,1.0,1.1907500&plusmn;0.0366759,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,820.9050,25.6750,-24.1890,0.0,0.0,"<div><span class=supersubNumber"">820.905</span...",NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,17.133,0.069,-0.069,NaN,1.0,17.133&plusmn;0.069,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,16.047,0.229,-0.229,0.0,1.0,16.047&plusmn;0.229,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,14.327,0.028,-0.028,0.0,1.0,14.327&plusmn;0.028,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,13.819,0.031,-0.031,0.0,1.0,13.819&plusmn;0.031,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,13.663,0.045,-0.045,0.0,1.0,13.663&plusmn;0.045,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,NaN,NaN,NaN,0.319132,-0.592626,0.739560,1149788419,Gaia DR2 2086441721667415424,Gaia DR3 2086441721667415424,0,0.0213,NaN,NaN,0.0,NaN,0.0213,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0,21.320040,6.104700,0.783967,Gazeuse/Mixte,0.160409,-1749.844898,0,Unknown

In [93]:

df[df["pl_name"] == "Kepler-280 c"]

,objectid,pl_name,pl_letter,hostid,hostname,hd_name,hip_name,tic_id,disc_pubdate,disc_year,disc_method,discoverymethod,disc_locale,disc_facility,disc_instrument,disc_telescope,disc_refname,ra,raerr1,raerr2,rasymerr,rastr,ra_solnid,ra_reflink,dec,decerr1,decerr2,decsymerr,decstr,dec_solnid,dec_reflink,glon,glonerr1,glonerr2,glonsymerr,glonstr,glon_solnid,glon_reflink,glat,glaterr1,glaterr2,glatsymerr,glatstr,glat_solnid,glat_reflink,elon,elonerr1,elonerr2,elonsymerr,elonstr,elon_solnid,elon_reflink,elat,elaterr1,elaterr2,elatsymerr,elat_solnid,elat_reflink,elatstr,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbpersymerr,pl_orbperlim,pl_orbperstr,pl_orbperformat,pl_orbper_solnid,pl_orbper_reflink,pl_orblpererr1,pl_orblper,pl_orblpererr2,pl_orblpersymerr,pl_orblperlim,pl_orblperstr,pl_orblperformat,pl_orblper_solnid,pl_orblper_reflink,pl_orbsmax,pl_orbsmaxerr1,pl_orbsmaxerr2,pl_orbsmaxsymerr,pl_orbsmaxlim,pl_orbsmaxstr,pl_orbsmaxformat,pl_orbsmax_solnid,pl_orbsmax_reflink,pl_orbincl,pl_orbinclerr1,pl_orbinclerr2,pl_orbinclsymerr,pl_orbincllim,pl_orbinclstr,pl_orbinclformat,pl_orbincl_solnid,pl_orbincl_reflink,pl_orbtper,pl_orbtpererr1,pl_orbtpererr2,pl_orbtpersymerr,pl_orbtperlim,pl_orbtperstr,pl_orbtperformat,pl_orbtper_solnid,pl_orbtper_reflink,pl_orbeccen,pl_orbeccenerr1,pl_orbeccenerr2,pl_orbeccensymerr,pl_orbeccenlim,pl_orbeccenstr,pl_orbeccenformat,pl_orbeccen_solnid,pl_orbeccen_reflink,pl_eqt,pl_eqterr1,pl_eqterr2,pl_eqtsymerr,pl_eqtlim,pl_eqtstr,pl_eqtformat,pl_eqt_solnid,pl_eqt_reflink,pl_occdep,pl_occdeperr1,pl_occdeperr2,pl_occdepsymerr,pl_occdeplim,pl_occdepstr,pl_occdepformat,pl_occdep_solnid,pl_occdep_reflink,pl_insol,pl_insolerr1,pl_insolerr2,pl_insolsymerr,pl_insollim,pl_insolstr,pl_insolformat,pl_insol_solnid,pl_insol_reflink,pl_dens,pl_denserr1,sy_umagerr1,sy_umagerr2,sy_umaglim,sy_umagsymerr,sy_umagstr,sy_umagformat,sy_umag_solnid,sy_umag_reflink,sy_rmag,sy_rmagerr1,sy_rmagerr2,sy_rmaglim,sy_rmagsymerr,sy_rmagstr,sy_rmagformat,sy_rmag_solnid,sy_rmag_reflink,sy_imag,sy_imagerr1,sy_imagerr2,sy_imaglim,sy_imagsymerr,sy_imagstr,sy_imagformat,sy_imag_solnid,sy_imag_reflink,sy_zmag,sy_zmagerr1,sy_zmagerr2,sy_zmaglim,sy_zmagsymerr,sy_zmagstr,sy_zmagformat,sy_zmag_solnid,sy_zmag_reflink,sy_w1mag,sy_w1magerr1,sy_w1magerr2,sy_w1maglim,sy_w1magsymerr,sy_w1magstr,sy_w1magformat,sy_w1mag_solnid,sy_w1mag_reflink,sy_w2mag,sy_w2magerr1,sy_w2magerr2,sy_w2maglim,sy_w2magsymerr,sy_w2magstr,sy_w2magformat,sy_w2mag_solnid,sy_w2mag_reflink,sy_w3mag,sy_w3magerr1,sy_w3magerr2,sy_w3maglim,sy_w3magsymerr,sy_w3magstr,sy_w3magformat,sy_w3mag_solnid,sy_w3mag_reflink,sy_w4mag,sy_w4magerr1,sy_w4magerr2,sy_w4maglim,sy_w4magsymerr,sy_w4magstr,sy_w4magformat,sy_w4mag_solnid,sy_w4mag_reflink,sy_gmag,sy_gmagerr1,sy_gmagerr2,sy_gmaglim,sy_gmagsymerr,sy_gmagstr,sy_gmagformat,sy_gmag_solnid,sy_gmag_reflink,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2,sy_gaiamaglim,sy_gaiamagsymerr,sy_gaiamagstr,sy_gaiamagformat,sy_gaiamag_solnid,sy_gaiamag_reflink,sy_tmag,sy_tmagerr1,sy_tmagerr2,sy_tmaglim,sy_tmagsymerr,sy_tmagstr,sy_tmagformat,sy_tmag_solnid,sy_tmag_reflink,sy_name,pl_controv_flag,pl_orbtper_systemref,pl_tranmid_systemref,st_metratio,st_spectype,st_spectype_solnid,st_spectype_reflink,sy_plxlim,sy_kepmag,sy_kepmagerr1,sy_kepmagerr2,sy_kepmaglim,sy_kepmagsymerr,sy_kepmagstr,sy_kepformat,sy_kepmag_solnid,sy_kepmag_reflink,st_rotp,st_rotperr1,st_rotperr2,st_rotpsymerr,st_rotplim,st_rotpstr,st_rotpformat,st_rotp_solnid,st_rotp_reflink,pl_projobliq,pl_projobliqerr1,pl_projobliqerr2,pl_projobliqsymerr,pl_projobliqlim,pl_projobliqstr,pl_projobliqformat,pl_denserr2,pl_denssymerr,pl_denslim,pl_densstr,pl_densformat,pl_dens_solnid,pl_dens_reflink,pl_trandep,pl_trandeperr1,pl_trandeperr2,pl_trandepsymerr,pl_trandeplim,pl_trandepstr,pl_trandepformat,pl_trandep_solnid,pl_trandep_reflink,pl_tranmid,pl_tranmiderr1,pl_tranmiderr2,pl_tranmidsymerr,pl_tranmidlim,pl_tranmidstr,pl_tranmidformat,pl_tranmid_solnid,pl_tranmid_reflink,pl_trandur,pl_trandurerr1,pl_trandurerr2,pl_trandursymerr,pl_trandurlim,pl_trandurstr,pl_trandurformat,pl_trandur_solnid,pl_trandur_reflink,pl_rvamp,pl_rvamperr1,pl_rvamperr2,pl_rvampsymerr,pl_rvamplim,pl_rvampstr,pl_rvampformat,pl_rvamp_solnid,pl_rvamp_reflink,pl_radj,pl_radjerr1,pl_radjerr2,pl_radjsymerr,pl_radjlim,pl_radjstr,pl_radjformat,pl_radj_solnid,pl_radj_reflink,pl_rade,pl_radeerr1,pl_radeerr2,pl_radesymerr,pl_radelim,pl_radestr,pl_radeformat,pl_rade_solnid,pl_rade_reflink,pl_ratror,pl_ratrorerr1,pl_ratrorerr2,pl_ratrorsymerr,pl_ratrorlim,pl_ratrorstr,pl_ratrorformat,pl_ratror_solnid,pl_ratror_reflink,pl_ratdor,pl_trueobliq,pl_trueobliqerr1,pl_trueobliqerr2,pl_trueobliqsymerr,pl_trueobliqlim,pl_trueobliqstr,pl_trueobliqformat,pl_trueobliq_solnid,pl_trueobliq_reflink,st_log_rhk,st_log_rhkerr1,st_log_rhkerr2,st_log_rhksymerr,st_log_rhklim,st_log_rhkstr,st_log_rhkformat,st_log_rhk_solnid,st_log_rhk_reflink,st_metn,sy_icmag,sy_icmagerr1,sy_icmagerr2,sy_icmagsymerr,sy_icmagstr,sy_icmagformat,sy_icmag_solnid,sy_icmag_reflink,pl_pubdate,dkin_flag,pl_ratdorerr1,pl_ratdorerr2,pl_ratdorsymerr,pl_ratdorlim,pl_ratdorstr,pl_ratdorformat,pl_ratdor_solnid,pl_ratdor_reflink,pl_imppar,pl_impparerr1,pl_impparerr2,pl_impparsymerr,pl_impparlim,pl_impparstr,pl_impparformat,pl_imppar_solnid,pl_imppar_reflink,pl_cmassj,pl_cmassjerr1,pl_cmassjerr2,pl_cmassjsymerr,pl_cmassjlim,pl_cmassjstr,pl_cmassjformat,pl_cmassj_solnid,pl_cmassj_reflink,pl_cmasse,pl_cmasseerr1,pl_cmasseerr2,pl_cmassesymerr,pl_cmasselim,pl_cmassestr,pl_cmasseformat,pl_cmasse_solnid,pl_cmasse_reflink,pl_massj,pl_massjerr1,pl_massjerr2,pl_massjsymerr,pl_massjlim,pl_massjstr,pl_massjformat,pl_massj_solnid,pl_massj_reflink,pl_masse,pl_masseerr1,pl_masseerr2,pl_massesymerr,pl_masselim,pl_massestr,pl_masseformat,pl_masse_solnid,pl_masse_reflink,pl_bmassj,pl_bmassjerr1,pl_bmassjerr2,pl_bmassjsymerr,pl_bmassjlim,pl_bmassjstr,pl_bmassjformat,pl_bmassj_solnid,pl_bmassj_reflink,pl_bmasse,pl_bmasseerr1,pl_bmasseerr2,pl_bmassesymerr,pl_bmasselim,pl_bmassestr,pl_bmasseformat,pl_bmasse_solnid,pl_bmasse_reflink,pl_bmassprov,pl_msinij,pl_msinijerr1,pl_msinijerr2,pl_msinijsymerr,pl_msinijlim,pl_msinijstr,pl_msinijformat,pl_msinij_solnid,pl_msinij_reflink,pl_msinie,pl_msinieerr1,pl_msinieerr2,pl_msiniesymerr,pl_msinielim,pl_msiniestr,pl_msinieformat,pl_msinie_solnid,pl_msinie_reflink,st_teff,st_tefferr1,st_tefferr2,st_teffsymerr,st_tefflim,st_teffstr,st_teffformat,st_teff_solnid,st_teff_reflink,st_met,st_meterr1,st_meterr2,st_metsymerr,st_metlim,st_metstr,st_metformat,st_met_solnid,st_met_reflink,st_radv,st_radverr1,st_radverr2,st_radvsymerr,st_radvlim,st_radvstr,st_radvformat,st_radv_solnid,st_radv_reflink,st_vsin,st_vsinerr1,st_vsinerr2,st_vsinsymerr,st_vsinlim,st_vsinstr,st_vsin_solnid,st_vsin_reflink,st_vsinformat,st_lum,st_lumerr1,st_lumerr2,st_lumsymerr,st_lumlim,st_lumstr,st_lumformat,st_lum_solnid,st_lum_reflink,st_logg,st_loggerr1,st_loggerr2,st_loggsymerr,st_logglim,st_loggstr,st_loggformat,st_logg_solnid,st_logg_reflink,st_age,st_ageerr1,st_ageerr2,st_agesymerr,st_agelim,st_agestr,st_ageformat,st_age_solnid,st_age_reflink,st_mass,st_masserr1,st_masserr2,st_masssymerr,st_masslim,st_massstr,st_massformat,st_mass_solnid,st_mass_reflink,st_dens,st_denserr1,st_denserr2,st_denssymerr,st_denslim,st_densstr,st_densformat,st_dens_solnid,st_dens_reflink,st_rad,st_raderr1,st_raderr2,st_radsymerr,st_radlim,st_radstr,st_radformat,st_rad_solnid,st_rad_reflink,systemid,ttv_flag,ptv_flag,tran_flag,rv_flag,ast_flag,obm_flag,micro_flag,etv_flag,ima_flag,pul_flag,disc_refid,sy_snum,sy_pnum,sy_mnum,st_nphot,st_nrvc,st_nspec,pl_nespec,pl_ntranspec,pl_nnotes,sy_pm,sy_pmerr1,sy_pmerr2,sy_pmsymerr,sy_pmlim,sy_pmstr,sy_pmformat,sy_pm_solnid,sy_pm_reflink,sy_pmra,sy_pmraerr1,sy_pmraerr2,sy_pmrasymerr,sy_pmralim,sy_pmrastr,sy_pmraformat,sy_pmra_solnid,sy_pmra_reflink,sy_pmdec,sy_pmdecerr1,sy_pmdecerr2,sy_pmdecsymerr,sy_pmdeclim,sy_pmdecstr,sy_pmdecformat,sy_pmdec_solnid,sy_pmdec_reflink,sy_plx,sy_plxerr1,sy_plxerr2,sy_plxsymerr,sy_plxstr,sy_plxformat,sy_plx_solnid,sy_plx_reflink,sy_dist,sy_disterr1,sy_disterr2,sy_distsymerr,sy_distlim,sy_diststr,sy_distformat,sy_dist_solnid,sy_dist_reflink,sy_bmag,sy_bmagerr1,sy_bmagerr2,sy_bmaglim,sy_bmagsymerr,sy_bmagstr,sy_bmagformat,sy_bmag_solnid,sy_bmag_reflink,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_vmaglim,sy_vmagsymerr,sy_vmagstr,sy_vmagformat,sy_vmag_solnid,sy_vmag_reflink,sy_jmag,sy_jmagerr1,sy_jmagerr2,sy_jmaglim,sy_jmagsymerr,sy_jmagstr,sy_jmagformat,sy_jmag_solnid,sy_jmag_reflink,sy_hmag,sy_hmagerr1,sy_hmagerr2,sy_hmaglim,sy_hmagsymerr,sy_hmagstr,sy_hmagformat,sy_hmag_solnid,sy_hmag_reflink,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_kmaglim,sy_kmagsymerr,sy_kmagstr,sy_kmagformat,sy_kmag_solnid,sy_kmag_reflink,sy_umag,pl_projobliq_solnid,pl_projobliq_reflink,x,y,z,htm20,gaia_dr2_id,gaia_dr3_id,cb_flag,pl_angsep,pl_angseperr1,pl_angseperr2,pl_angseplim,pl_angsepformat,pl_angsepstr,pl_angsepsymerr,pl_angsep_reflink,pl_ndispec,Masse_10^24kg,Gravity_G_earth,Score_roch,pl_type,sim_earth,pl_insol_calc,eau_possible,st_spectype_group
5,3.2547,Kepler-280 c,c,2.490197,Kepler-280,NaN,NaN,TIC 159716174,2014-03,2014.0,tran,Transit,Space,Kepler,Kepler CCD Array,0.95 m Kepler Telescope,<a refstr=ROWE_ET_AL__2014 href=https://ui.ads...,291.390533,4.244056e-09,-4.244056e-09,1,19h25m33.73s,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,42.180473,4.884667e-09,-4.884667e-09,1,+42d10m49.70s,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,74.40417,NaN,NaN,NaN,74.40417,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,12.02527,NaN,NaN,NaN,12.02527,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,306.44327,NaN,NaN,NaN,306.44327,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,62.93884,NaN,NaN,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,62.93884,4.807091,0.000009,-0.000009,1.0,0.0,4.807091&plusmn;0.000009,NaN,3347.1,<a refstr=ROWE_ET_AL__2014 href=https://ui.ads...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.056,NaN,NaN,0.0,0.0,0.056,NaN,3347.1,<a refstr=ROWE_ET_AL__2014 href=https://ui.ads...,86.65,NaN,NaN,NaN,0.0,86.65,NaN,4440.69309,<a refstr=Q1_Q17_DR25_KOI_TABLE href=https://e...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0,NaN,4440.69309,<a refstr=Q1_Q17_DR25_KOI_TABLE href=https://e...,1088.0,NaN,NaN,NaN,0.0,1088,NaN,4440.69309,<a refstr=Q1_Q17_DR25_KOI_TABLE href=https://e...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,279.085,10.032,-9.68,0.0,0.0,"<div><span class=supersubNumber"">279.085</span...",NaN,4194.1,<a refstr=BERGER_ET_AL__2018 href=https://ui.a...,3.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,14.419,NaN,NaN,NaN,0.0,14.419,NaN,720.2,<a refstr=LATHAM_ET_AL__2005 href=https://ui.a...,14.242,NaN,NaN,0.0,0.0,14.242,NaN,720.2,<a refstr=LATHAM_ET_AL__2005 href=https://ui.a...,14.169,NaN,NaN,NaN,0.0,14.169,NaN,720.2,<a refstr=LATHAM_ET_AL__2005 href=https://ui.a...,12.837,0.024,-0.024,NaN,1.0,12.837&plusmn;0.024,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,12.89,0.024,-0.024,NaN,1.0,12.890&plusmn;0.024,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,13.062,NaN,NaN,NaN,0.0,13.062,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,9.309,NaN,NaN,NaN,0.0,9.309,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,14.989,NaN,NaN,NaN,0.0,14.989,NaN,720.2,<a refstr=LATHAM_ET_AL__2005 href=https://ui.a...,14.4574,0.000269,-0.000269,NaN,1.0,14.457400&plusmn;0.000269,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,13.9604,0.0081,-0.0081,NaN,1.0,13.9604&plusmn;0.0081,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,Kepler-280,0,NaN,BJD,[M/H],NaN,NaN,NaN,0.0,14.466,NaN,NaN,NaN,0.0,14.466,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3.18,NaN,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0.04505,0.00189,-0.00189,NaN,0.0,0.04505&plusmn0.00189,NaN,4440.69309,<a refstr=Q1_Q17_DR25_KOI_TABLE href=https://e...,2.454968e+06,0.00104,-0.00104,1.0,0.0,2454967.64249&plusmn;0.00104,NaN,3347.1,<a refstr=ROWE_ET_AL__2014 href=https://ui.ads...,0.901,0.076,-0.076,1.0,0.0,0.901&plusmn;0.076,NaN,3347.1,<a refstr=ROWE_ET_AL__2014 href=https://ui.ads...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.179,0.087,-0.087,1.0,0.0,0.179&plusmn;0.087,NaN,3347.1,<a refstr=ROWE_ET_AL__2014 href=https://ui.ads...,2.01,0.97,-0.97,1.0,0.0,2.01&plusmn;0.97,NaN,3347.1,<a refstr=ROWE_ET_AL__2014 href=https://ui.ads...,0.0197,0.000671,-0.000655,0.0,0.0,"<div><span class=supersubNumber"">0.019700</spa...",NaN,5531.1,<a refstr=FULTON__AMP__PETIGURA_2018 href=http...,13.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,NaN,0,3.8,-3.8,NaN,0.0,13.5&plusmn;3.8,NaN,4436.14593,<a refstr=Q1_Q8_KOI_TABLE href=https://exoplan...,0.68,0.09,-0.09,1.0,0.0,0.68&plusmn;0.09,NaN,3347.1,<a refstr=ROWE_ET_AL__2014 href=https://ui.ads...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0148,NaN,NaN,NaN,0.0,0.0148,NaN,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,4.7,NaN,NaN,NaN,0.0,4.7,NaN,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,M-R relationship,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5744.0,200.0,-200.0,1.0,0.0,5744&plusmn;200,NaN,3347.1,<a refstr=ROWE_ET_AL__2014 href=https://ui.ads...,0.1213,0.0129,-0.0129,1.0,0.0,0.1212530&plusmn;0.0128615,NaN,4400.1,<a refstr=GAJDO_SCARON__ET_AL__2019 href=https...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.06437,NaN,NaN,0.0,0.0,-0.06436836,NaN,4400.1,<a refstr=GAJDO_SCARON__ET_AL__2019 href=https...,4.537,0.3,-0.3,1.0,0.0,4.537&plusmn;0.300,NaN,3347.1,<a refstr=ROWE_ET_AL__2014 href=https://ui.ads...,5.62,2.5,-2.53,0.0,0.0,"<div><span class=supersubNumber"">5.62</span><s...",NaN,5531.1,<a refstr=FULTON__AMP__PETIGURA_2018 href=http...,0.962,0.038,-0.034,0.0,0.0,"<div><span class=supersubNumber"">0.962</span><...",NaN,5531.1,<a refstr=FULTON__AMP__PETIGURA_2018 href=http...,1.08,0.08,-0.08,0.0,0.0,1.08&plusmn;0.08,NaN,5531.1,<a refstr=FULTON__AMP__PETIGURA_2018 href=http...,0.886,0.426,-0.426,1.0,0.0,0.886&plusmn;0.426,NaN,3347.1,<a refstr=ROWE_ET_AL__2014 href=https://ui.ads...,1.490197,0,0,1,0,0,0,0,0,0,0,3347,1,2,0,0,0,0,0,0,1,22.744663,0.032004,-0.032004,1.0,NaN,22.7446632&plusmn;0.0320036,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,3.48556,0.031536,-0.031536,1.0,NaN,3.4855600&plusmn;0.0315358,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,-22.476,0.032015,-0.032015,1.0,NaN,-22.4760000&plusmn;0.0320148,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,1.2528,0.018416,-0.018416,1.0,1.2528000&plusmn;0.0184161,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,780.361,11.302,-11.302,1.0,0.0,780.361&plusmn;11.302,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,15.295,0.067,-0.067,NaN,1.0,15.295&plusmn;0.067,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,14.35,0.092,-0.092,0.0,1.0,14.350&plusmn;0.092,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,13.289,0.023,-0.023,0.0,1.0,13.289&plusmn;0.023,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,12.914,0.024,-0.024,0.0,1.0,12.914&plusmn;0.024,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,12.844,0.022,-0.022,0.0,1.0,12.844&plusmn;0.022,NaN,4400.1,<a refstr=STASSUN_ET_AL__2019 href=https://ui....,NaN,NaN,NaN,0.270272,-0.689988,0.671468,-369621197,Gaia DR2 2101761079737564672,Gaia DR3 2101761079737564672,0,0.0718,NaN,NaN,0.0,NaN,0.0718,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0,28.0684,9.447,0.391597,Gazeuse/Mixte,0.192846,-20.526148,0,Unknown

In [48]:
subset = df[df["pl_name"] == "Kepler-280 c"]
subset.duplicated()

5    False
6     True
dtype: bool

In [49]:
df = df.drop_duplicates()

In [50]:
df.shape

(6153, 683)

In [56]:
df.describe()

,objectid,hostid,disc_year,ra,raerr1,raerr2,rasymerr,ra_solnid,dec,decerr1,decerr2,decsymerr,dec_solnid,glon,glonerr1,glonerr2,glonsymerr,glonstr,glon_solnid,glat,glaterr1,glaterr2,glatsymerr,glatstr,glat_solnid,elon,elonerr1,elonerr2,elonsymerr,elonstr,elon_solnid,elat,elaterr1,elaterr2,elatsymerr,elat_solnid,elatstr,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbpersymerr,pl_orbperlim,pl_orbperformat,pl_orbper_solnid,pl_orblpererr1,pl_orblper,pl_orblpererr2,pl_orblpersymerr,pl_orblperlim,pl_orblperformat,pl_orblper_solnid,pl_orbsmax,pl_orbsmaxerr1,pl_orbsmaxerr2,pl_orbsmaxsymerr,pl_orbsmaxlim,pl_orbsmaxformat,pl_orbsmax_solnid,pl_orbincl,pl_orbinclerr1,pl_orbinclerr2,pl_orbinclsymerr,pl_orbincllim,pl_orbinclformat,pl_orbincl_solnid,pl_orbtper,pl_orbtpererr1,pl_orbtpererr2,pl_orbtpersymerr,pl_orbtperlim,pl_orbtperformat,pl_orbtper_solnid,pl_orbeccen,pl_orbeccenerr1,pl_orbeccenerr2,pl_orbeccensymerr,pl_orbeccenlim,pl_orbeccenformat,pl_orbeccen_solnid,pl_eqt,pl_eqterr1,pl_eqterr2,pl_eqtsymerr,pl_eqtlim,pl_eqtformat,pl_eqt_solnid,pl_occdep,pl_occdeperr1,pl_occdeperr2,pl_occdepsymerr,pl_occdeplim,pl_occdepformat,pl_occdep_solnid,pl_insol,pl_insolerr1,pl_insolerr2,pl_insolsymerr,pl_insollim,pl_insolformat,pl_insol_solnid,pl_dens,pl_denserr1,sy_umagerr1,sy_umagerr2,sy_umaglim,sy_umagsymerr,sy_umagformat,sy_umag_solnid,sy_rmag,sy_rmagerr1,sy_rmagerr2,sy_rmaglim,sy_rmagsymerr,sy_rmagformat,sy_rmag_solnid,sy_imag,sy_imagerr1,sy_imagerr2,sy_imaglim,sy_imagsymerr,sy_imagformat,sy_imag_solnid,sy_zmag,sy_zmagerr1,sy_zmagerr2,sy_zmaglim,sy_zmagsymerr,sy_zmagformat,sy_zmag_solnid,sy_w1mag,sy_w1magerr1,sy_w1magerr2,sy_w1maglim,sy_w1magsymerr,sy_w1magformat,sy_w1mag_solnid,sy_w2mag,sy_w2magerr1,sy_w2magerr2,sy_w2maglim,sy_w2magsymerr,sy_w2magformat,sy_w2mag_solnid,sy_w3mag,sy_w3magerr1,sy_w3magerr2,sy_w3maglim,sy_w3magsymerr,sy_w3magformat,sy_w3mag_solnid,sy_w4mag,sy_w4magerr1,sy_w4magerr2,sy_w4maglim,sy_w4magsymerr,sy_w4magformat,sy_w4mag_solnid,sy_gmag,sy_gmagerr1,sy_gmagerr2,sy_gmaglim,sy_gmagsymerr,sy_gmagformat,sy_gmag_solnid,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2,sy_gaiamaglim,sy_gaiamagsymerr,sy_gaiamagformat,sy_gaiamag_solnid,sy_tmag,sy_tmagerr1,sy_tmagerr2,sy_tmaglim,sy_tmagsymerr,sy_tmagformat,sy_tmag_solnid,pl_controv_flag,st_spectype_solnid,sy_plxlim,sy_kepmag,sy_kepmagerr1,sy_kepmagerr2,sy_kepmaglim,sy_kepmagsymerr,sy_kepmagstr,sy_kepformat,sy_kepmag_solnid,st_rotp,st_rotperr1,st_rotperr2,st_rotpsymerr,st_rotplim,st_rotpformat,st_rotp_solnid,pl_projobliq,pl_projobliqerr1,pl_projobliqerr2,pl_projobliqsymerr,pl_projobliqlim,pl_projobliqformat,pl_denserr2,pl_denssymerr,pl_denslim,pl_densformat,pl_dens_solnid,pl_trandep,pl_trandeperr1,pl_trandeperr2,pl_trandepsymerr,pl_trandeplim,pl_trandepformat,pl_trandep_solnid,pl_tranmid,pl_tranmiderr1,pl_tranmiderr2,pl_tranmidsymerr,pl_tranmidlim,pl_tranmidformat,pl_tranmid_solnid,pl_trandur,pl_trandurerr1,pl_trandurerr2,pl_trandursymerr,pl_trandurlim,pl_trandurformat,pl_trandur_solnid,pl_rvamp,pl_rvamperr1,pl_rvamperr2,pl_rvampsymerr,pl_rvamplim,pl_rvampformat,pl_rvamp_solnid,pl_radj,pl_radjerr1,pl_radjerr2,pl_radjsymerr,pl_radjlim,pl_radjformat,pl_radj_solnid,pl_rade,pl_radeerr1,pl_radeerr2,pl_radesymerr,pl_radelim,pl_radeformat,pl_rade_solnid,pl_ratror,pl_ratrorerr1,pl_ratrorerr2,pl_ratrorsymerr,pl_ratrorlim,pl_ratrorformat,pl_ratror_solnid,pl_ratdor,pl_trueobliq,pl_trueobliqerr1,pl_trueobliqerr2,pl_trueobliqsymerr,pl_trueobliqlim,pl_trueobliqformat,pl_trueobliq_solnid,st_log_rhk,st_log_rhkerr1,st_log_rhkerr2,st_log_rhksymerr,st_log_rhklim,st_log_rhkformat,st_log_rhk_solnid,st_metn,sy_icmag,sy_icmagerr1,sy_icmagerr2,sy_icmagsymerr,sy_icmagformat,sy_icmag_solnid,pl_pubdate,dkin_flag,pl_ratdorerr1,pl_ratdorerr2,pl_ratdorsymerr,pl_ratdorlim,pl_ratdorformat,pl_ratdor_solnid,pl_imppar,pl_impparerr1,pl_impparerr2,pl_impparsymerr,pl_impparlim,pl_impparformat,pl_imppar_solnid,pl_cmassj,pl_cmassjerr1,pl_cmassjerr2,pl_cmassjsymerr,pl_cmassjlim,pl_cmassjformat,pl_cmassj_solnid,pl_cmasse,pl_cmasseerr1,pl_cmasseerr2,pl_cmassesymerr,pl_cmasselim,pl_cmasseformat,pl_cmasse_solnid,pl_massj,pl_massjerr1,pl_massjerr2,pl_massjsymerr,pl_massjlim,pl_massjformat,pl_massj_solnid,pl_masse,pl_masseerr1,pl_masseerr2,pl_massesymerr,pl_masselim,pl_masseformat,pl_masse_solnid,pl_bmassj,pl_bmassjerr1,pl_bmassjerr2,pl_bmassjsymerr,pl_bmassjlim,pl_bmassjformat,pl_bmassj_solnid,pl_bmasse,pl_bmasseerr1,pl_bmasseerr2,pl_bmassesymerr,pl_bmasselim,pl_bmasseformat,pl_bmasse_solnid,pl_msinij,pl_msinijerr1,pl_msinijerr2,pl_msinijsymerr,pl_msinijlim,pl_msinijformat,pl_msinij_solnid,pl_msinie,pl_msinieerr1,pl_msinieerr2,pl_msiniesymerr,pl_msinielim,pl_msinieformat,pl_msinie_solnid,st_teff,st_tefferr1,st_tefferr2,st_teffsymerr,st_tefflim,st_teffformat,st_teff_solnid,st_met,st_meterr1,st_meterr2,st_metsymerr,st_metlim,st_metformat,st_met_solnid,st_radv,st_radverr1,st_radverr2,st_radvsymerr,st_radvlim,st_radvformat,st_radv_solnid,st_vsin,st_vsinerr1,st_vsinerr2,st_vsinsymerr,st_vsinlim,st_vsin_solnid,st_vsinformat,st_lum,st_lumerr1,st_lumerr2,st_lumsymerr,st_lumlim,st_lumformat,st_lum_solnid,st_logg,st_loggerr1,st_loggerr2,st_loggsymerr,st_logglim,st_loggformat,st_logg_solnid,st_age,st_ageerr1,st_ageerr2,st_agesymerr,st_agelim,st_ageformat,st_age_solnid,st_mass,st_masserr1,st_masserr2,st_masssymerr,st_masslim,st_massformat,st_mass_solnid,st_dens,st_denserr1,st_denserr2,st_denssymerr,st_denslim,st_densformat,st_dens_solnid,st_rad,st_raderr1,st_raderr2,st_radsymerr,st_radlim,st_radformat,st_rad_solnid,systemid,ttv_flag,ptv_flag,tran_flag,rv_flag,ast_flag,obm_flag,micro_flag,etv_flag,ima_flag,pul_flag,disc_refid,sy_snum,sy_pnum,sy_mnum,st_nphot,st_nrvc,st_nspec,pl_nespec,pl_ntranspec,pl_nnotes,sy_pm,sy_pmerr1,sy_pmerr2,sy_pmsymerr,sy_pmlim,sy_pmformat,sy_pm_solnid,sy_pmra,sy_pmraerr1,sy_pmraerr2,sy_pmrasymerr,sy_pmralim,sy_pmraformat,sy_pmra_solnid,sy_pmdec,sy_pmdecerr1,sy_pmdecerr2,sy_pmdecsymerr,sy_pmdeclim,sy_pmdecformat,sy_pmdec_solnid,sy_plx,sy_plxerr1,sy_plxerr2,sy_plxsymerr,sy_plxformat,sy_plx_solnid,sy_dist,sy_disterr1,sy_disterr2,sy_distsymerr,sy_distlim,sy_distformat,sy_dist_solnid,sy_bmag,sy_bmagerr1,sy_bmagerr2,sy_bmaglim,sy_bmagsymerr,sy_bmagformat,sy_bmag_solnid,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_vmaglim,sy_vmagsymerr,sy_vmagformat,sy_vmag_solnid,sy_jmag,sy_jmagerr1,sy_jmagerr2,sy_jmaglim,sy_jmagsymerr,sy_jmagformat,sy_jmag_solnid,sy_hmag,sy_hmagerr1,sy_hmagerr2,sy_hmaglim,sy_hmagsymerr,sy_hmagformat,sy_hmag_solnid,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_kmaglim,sy_kmagsymerr,sy_kmagformat,sy_kmag_solnid,sy_umag,pl_projobliq_solnid,x,y,z,htm20,cb_flag,pl_angsep,pl_angseperr1,pl_angseperr2,pl_angseplim,pl_angsepformat,pl_angsepstr,pl_angsepsymerr,pl_ndispec,Masse_10^24kg,Gravity_G_earth
count,6153.000000,6153.000000,6152.000000,6153.000000,5.867000e+03,5.867000e+03,6153.000000,6153.000000,6153.000000,5.867000e+03,5.867000e+03,6153.000000,6153.000000,6153.000000,0.0,0.0,0.0,6153.000000,6153.000000,6153.000000,0.0,0.0,0.0,6153.000000,6153.000000,6153.000000,0.0,0.0,0.0,6153.000000,6153.000000,6153.000000,0.0,0.0,0.0,6153.000000,6153.000000,5.819000e+03,5.329000e+03,5.329000e+03,5749.000000,5819.000000,0.0,5819.000000,1770.000000,2024.000000,1770.000000,2024.000000,2094.000000,0.0,2024.000000,5837.000000,3900.000000,3900.000000,4707.000000,5838.000000,0.0,5837.000000,4632.000000,2053.000000,2055.000000,2119.000000,4632.000000,0.0,4632.000000,1.051000e+03,1022.000000,1022.000000,1051.000000,1051.0,0.0,1051.000000,5215.000000,1864.000000,1864.000000,2813.000000,5215.000000,0.0,5215.000000,4590.000000,1809.000000,1809.000000,2021.000000,4590.000000,0.0,4590.000000,35.000000,32.000000,32.000000,35.00000,35.000000,0.0,35.000000,4313.000000,3636.000000,3636.000000,3853.000000,4313.0,0.0,4313.000000,6014.000000,1412.000000,727.000000,725.000000,0.0,734.000000,0.0,6153.000000,3501.000000,878.000000,725.000000,0.0,3501.000000,0.0,6153.000000,3447.000000,870.000000,725.000000,3447.0,3447.000000,0.0,6153.000000,3234.000000,732.000000,725.000000,0.0,3234.000000,0.0,6153.000000,5539.00000,5470.000000,5204.000000,0.0,5539.000000,0.0,6153.000000,5540.000000,5488.000000,5215.000000,0.0,5540.000000,0.0,6153.000000,5539.000000,4518.000000,4238.000000,0.0,5539.000000,0.0,6153.000000,5538.000000,1522.000000,1522.000000,0.0,5538.000000,0.0,6153.000000,3484.000000,867.000000,725.000000,0.0,3484.000000,0.0,6153.000000,5814.000000,5814.000000,5814.000000,0.0,5814.0,0.0,6153.000000,5865.000000,5856.000000,5856.000000,0.0,5865.000000,0.0,6153.000000,6153.000000,2308.000000,5763.0,3464.000000,0.0,0.0,0.0,3464.0,3464.000000,0.0,6153.000000,890.000000,713.000000,713.000000,890.000000,890.000000,0.0,890.000000,230.000000,228.000000,228.000000,230.000000,230.000000,0.0,1412.000000,1489.000000,6014.000000,0.0,1489.000000,4378.000000,4265.000000,4265.000000,1444.000000,4378.000000,0.0,4378.000000,4.889000e+03,4831.000000,4831.000000,4445.000000,4889.0,0.0,4889.000000,4472.000000,4374.000000,4374.000000,3758.000000,4472.000000,0.0,4472.000000,2487.000000,2406.000000,2406.000000,2487.000000,2487.000000,0.0,2487.000000,6103.000000,4222.000000,4222.000000,4530.000000,6103.000000,0.0,4604.000000,6103.000000,4222.000000,4222.000000,4530.000000,6103.000000,0.0,4604.000000,4401.000000,4362.000000,4362.000000,3658.000000,4401.0,0.0,4401.000000,4365.000000,67.000000,60.000000,60.000000,67.000000,67.000000,0.0,67.000000,660.000000,291.000000,291.000000,660.000000,660.000000,0.0,660.000000,0.0,352.000000,215.000000,18.000000,352.000000,0.0,6153.000000,0.0,6153.000000,4346.000000,4346.000000,1846.000000,4365.000000,0.0,4365.000000,4376.000000,4316.000000,4316.000000,2531.000000,4376.000000,0.0,4376.000000,84.000000,82.000000,82.000000,84.000000,84.0,0.0,84.000000,84.000000,82.000000,82.000000,84.000000,84.0,0.0,84.000000,2353.000000,2117.000000,2117.000000,2353.000000,2353.000000,0.0,2353.000000,2353.000000,2117.000000,2117.000000,2353.000000,2353.000000,0.0,2353.000000,6122.000000,2989.000000,2989.000000,3256.000000,6122.000000,0.0,0.0,6122.000000,2989.000000,2989.000000,3256.000000,6122.000000,0.0,0.0,1322.000000,1278.000000,1278.000000,1322.000000,1322.000000,0.0,1322.000000,1322.000000,1278.000000,1278.000000,1322.000000,1322.000000,0.0,1322.000000,5863.000000,5663.000000,5663.000000,5476.000000,5863.000000,0.0,5863.000000,5603.000000,5319.000000,5319.000000,5200.000000,5603.000000,0.0,5603.000000,2385.000000,2322.000000,2278.000000,2385.000000,2385.000000,0.0,2385.000000,2275.000000,1581.000000,1567.000000,2275.000000,2275.000000,2275.000000,0.0,5845.000000,3680.000000,3674.000000,5687.000000,5845.0,0.0,5687.000000,5835.000000,5657.000000,5657.000000,5441.000000,5835.000000,0.0,5835.000000,4843.000000,4588.000000,4588.000000,4443.000000,4911.000000,0.0,4843.00000,6145.000000,5877.000000,5876.000000,5665.000000,6145.0,0.0,6145.000000,5570.000000,5440.000000,5440.000000,4221.000000,5570.0,0.0,5570.000000,5839.000000,5681.000000,5680.000000,5457.000000,5839.0,0.0,5839.000000,6153.000000,6153.000000,6153.000000,6153.000000,6153.000000,6153.000000,6153.000000,6153.000000,6153.000000,6153.000000,6153.000000,6153.000000,6153.000000,6153.000000,6153.0,6153.000000,6153.000000,6153.000000,6153.000000,6153.000000,6153.000000,5851.000000,5848.000000,5838.000000,5851.000000,0.0,0.0,6153.000000,5851.000000,5848.000000,5838.000000,5851.000000,0.0,0.0,6153.000000,5851.000000,5848.000000,5838.000000,5851.000000,0.0,0.0,6153.000000,5763.000000,5763.000000,5763.000000,5763.000000,0.0,6153.000000,6126.000000,6019.000000,6019.000000,6126.000000,6126.0,0.0,6153.000000,5737.000000,5720.000000,5689.000000,0.0,5737.000000,0.0,6153.000000,5858.000000,5850.000000,5845.000000,5858.0,5858.000000,0.0,6153.000000,5850.000000,5831.000000,5831.000000,5850.000000,5850.000000,0.0,6153.000000,5865.000000,5843.000000,5843.000000,5865.000000,5865.000000,0.0,6153.000000,5871.000000,5834.000000,5823.000000,5871.000000,5871.000000,0.0,6153.000000,734.000000,230.000000,6153.000000,6153.000000,6153.000000,6.153000e+03,6153.000000,5808.000000,0.0,0.0,5808.0,0.0,5808.000000,0.0,6153.000000,6122.000000,6079.000000
mean,3.260726,2.440925,2016.990735,232.922360,2.513908e-07,-2.513908e-07,0.953519,4412.530519,18.030558,2.755340e-07,-2.755340e-07,0.953519,4412.530519,135.778322,NaN,NaN,NaN,135.778322,4412.530519,6.175746,NaN,NaN,NaN,6.175746,4412.530519,241.399947,NaN,NaN,NaN,241.399947,4412.530519,28.017966,NaN,NaN,NaN,4412.530519,28.017966,7.355626e+04,8.982891e+04,-2.051852e+04,0.688294,-0.001031,NaN,4278.111180,45.959823,110.505891,-44.619371,0.338439,-0.000478,NaN,4552.499817,15.711825,1.807315,-0.961979,0.414277,-0.000514,NaN,4506.287265,86.507090,2.434385,-2.619779,0.321850,-0.006477,NaN,4552.878104,2.454006e+06,398.271308,-502.784364,0.499524,0.0,NaN,4017.476023,0.079302,0.067847,-0.055026,0.287949,0.052733,NaN,4519.316553,912.848420,31.274704,-30.740674,0.548738,0.000654,NaN,4561.329272,0.029010,0.004534,-0.003966,0.40000,0.085714,NaN,4124.871429,417.926124,41.277250,-31.734528,0.124059,0.0,NaN,4505.668009,4.905611,39.410052,0.018667,-0.018648,NaN,0.987738,NaN,4408.064275,14.014699,0.009669,-0.003547,NaN,0.207084,NaN,2834.922458,13.837609,0.013465,-0.004005,0.0,0.210328,NaN,2861.964242,13.816294,0.006018,-0.005835,NaN,0.224181,NaN,2916.057416,10.42794,0.043829,-0.038856,NaN,0.939520,NaN,4366.250298,10.447119,0.031928,-0.029522,NaN,0.941336,NaN,4366.250298,10.247963,0.133697,-0.140955,NaN,0.765120,NaN,4366.250298,8.330683,0.174488,-0.174488,NaN,0.274828,NaN,4366.250298,14.727196,0.012146,-0.004141,NaN,0.208094,NaN,2843.376269,12.255214,0.000644,-0.000644,NaN,1.0,NaN,4413.152329,11.670753,0.021005,-0.021005,NaN,0.998295,NaN,4412.913405,0.007964,4082.445243,0.0,13.956840,NaN,NaN,NaN,0.0,13.956840,NaN,4412.530519,52.834249,9.135759,-9.070563,0.659551,0.030337,NaN,4805.781011,10.014422,12.275320,-11.438789,0.482609,0.004348,NaN,-3.291059,0.379449,0.012637,NaN,4764.564493,0.319404,0.010604,-0.009175,0.243075,-0.000457,NaN,4444.057880,2.461217e+06,11.758525,-9.714186,0.759280,0.0,NaN,4291.200594,3.861529,0.125917,-0.123894,0.732837,0.000224,NaN,4135.523467,100.667769,6.463471,-6.127089,0.621230,0.026940,NaN,4607.777616,0.521492,0.046082,-0.037026,0.409713,-0.000655,NaN,4232.298194,5.845071,0.516502,-0.414993,0.407506,-0.000655,NaN,4232.066874,0.040485,0.046315,-0.002108,0.257244,0.0,NaN,4449.358965,29.866394,48.871642,11.595667,-11.922667,0.283582,0.044776,NaN,5007.697015,-4.950965,0.079375,-0.080412,0.410606,0.001515,NaN,3635.839394,NaN,8.708540,0.218586,-2.733944,0.019886,NaN,4228.328924,NaN,0.000163,3.581138,-3.644321,0.378657,-0.000229,NaN,4543.731735,0.501744,0.245219,-0.218504,0.448044,0.000914,NaN,4360.307009,1.374747,0.216965,-0.216965,0.976190,0.0,NaN,3628.409524,436.995114,68.831152,-68.831152,0.976190,0.0,NaN,3628.409524,2.550316,0.673837,-0.462764,0.415215,0.086698,NaN,4715.925020,810.467224,214.006295,-147.060693,0.410115,0.086698,NaN,4716.383583,1.280362,0.555513,-0.399361,0.475430,0.033159,NaN,NaN,406.888917,176.427692,-126.897459,0.470209,0.033159,NaN,NaN,2.236495,0.290998,-0.256724,0.627837,0.003782,NaN,4442.342284,710.981389,92.404811,-81.489387,0.625567,0.003782,NaN,4442.218230,5397.502857,98.463216,-99.229988,0.602264,0.000171,NaN,4236.810717,0.015971,0.096960,-0.102682,0.530962,0.000000,NaN,4398.789244,-1.633294,0.522979,-0.542460,0.911111,0.001258,NaN,3715.544486,5.545739,0.706960,-0.705611,0.646154,0.137582,3833.006857,NaN,-0.144432,0.032682,-0.036197,0.035695,0.0,NaN,4378.323826,4.384277,0.082620,-0.097074,0.577835,-0.001028,NaN,4208.068139,4.380232,2.387299,-1.816323,0.269187,-0.015272,NaN,4326.93796,0.936659,0.084625,-0.078515,0.430362,0.0,NaN,4477.133599,3.114499,1.250772,-0.578620,0.261312,0.0,NaN,4709.364469,1.503337,0.188018,-0.146898,0.543156,0.0,NaN,4245.155779,1.434538,0.079311,0.000325,0.741589,0.397205,0.026004,0.006338,0.044694,0.002925,0.015927,0.001300,3945.021615,1.103689,1.773931,0.0,0.356574,0.205266,0.179587,0.124817,0.120429,0.870307,116.993213,0.162074,-0.161101,0.997778,NaN,NaN,4410.759334,9.049811,0.164455,-0.163057,0.997607,NaN,NaN,4412.530519,-25.931889,0.158680,-0.157862,0.997607,NaN,NaN,4412.530519,13.432360,0.052243,-0.052245,0.999826,NaN,4408.258944,711.442120,59.936364,-67.205041,0.236370,0.0,NaN,4406.419175,13.340022,0.079470,-0.079718,NaN,0.991633,NaN,4389.330372,12.547990,0.098142,-0.099638,0.0,0.997098,NaN,4410.202402,10.869676,0.035943,-0.035323,-0.000171,0.996410,NaN,4412.457709,10.493668,0.038270,-0.038222,-0.000171,0.994714,NaN,4412.128437,10.379823,0.041502,-0.041517,-0.000170,0.990291,NaN,4404.606075,16.274434,4553.613913,0.097297,-0.319620,0.282237,3.690117e+07,0.008776,465.337820,NaN,NaN,0.0,NaN,465.337820,NaN,0.011214,2429.940611,5077.901370

In [57]:
df.info()

<class 'pandas.DataFrame'>
Index: 6153 entries, 0 to 10869
Columns: 685 entries, objectid to Gravity_G_earth
dtypes: float64(499), int64(27), str(159)
memory usage: 32.2 MB

In [58]:
pd.set_option('display.max_rows', None)
df.isna().sum()

objectid                   0
pl_name                    0
pl_letter                  0
hostid                     0
hostname                   0
hd_name                 5110
hip_name                5017
tic_id                   289
disc_pubdate               0
disc_year                  1
disc_method                0
discoverymethod            0
disc_locale                0
disc_facility              0
disc_instrument            0
disc_telescope             0
disc_refname               0
ra                         0
raerr1                   286
raerr2                   286
rasymerr                   0
rastr                      0
ra_solnid                  0
ra_reflink                 0
dec                        0
decerr1                  286
decerr2                  286
decsymerr                  0
decstr                     0
dec_solnid                 0
dec_reflink                0
glon                       0
glonerr1                6153
glonerr2                6153
glonsymerr              6153
glonstr                    0
glon_solnid                0
glon_reflink               0
glat                       0
glaterr1                6153
glaterr2                6153
glatsymerr              6153
glatstr                    0
glat_solnid                0
glat_reflink               0
elon                       0
elonerr1                6153
elonerr2                6153
elonsymerr              6153
elonstr                    0
elon_solnid                0
elon_reflink               0
elat                       0
elaterr1                6153
elaterr2                6153
elatsymerr              6153
elat_solnid                0
elat_reflink               0
elatstr                    0
pl_orbper                334
pl_orbpererr1            824
pl_orbpererr2            824
pl_orbpersymerr          404
pl_orbperlim             334
pl_orbperstr             334
pl_orbperformat         6153
pl_orbper_solnid         334
pl_orbper_reflink        334
pl_orblpererr1          4383
pl_orblper              4129
pl_orblpererr2          4383
pl_orblpersymerr        4129
pl_orblperlim           4059
pl_orblperstr           4129
pl_orblperformat        6153
pl_orblper_solnid       4129
pl_orblper_reflink      4129
pl_orbsmax               316
pl_orbsmaxerr1          2253
pl_orbsmaxerr2          2253
pl_orbsmaxsymerr        1446
pl_orbsmaxlim            315
pl_orbsmaxstr            316
pl_orbsmaxformat        6153
pl_orbsmax_solnid        316
pl_orbsmax_reflink       316
pl_orbincl              1521
pl_orbinclerr1          4100
pl_orbinclerr2          4098
pl_orbinclsymerr        4034
pl_orbincllim           1521
pl_orbinclstr           1521
pl_orbinclformat        6153
pl_orbincl_solnid       1521
pl_orbincl_reflink      1521
pl_orbtper              5102
pl_orbtpererr1          5131
pl_orbtpererr2          5131
pl_orbtpersymerr        5102
pl_orbtperlim           5102
pl_orbtperstr           5102
pl_orbtperformat        6153
pl_orbtper_solnid       5102
pl_orbtper_reflink      5102
pl_orbeccen              938
pl_orbeccenerr1         4289
pl_orbeccenerr2         4289
pl_orbeccensymerr       3340
pl_orbeccenlim           938
pl_orbeccenstr           938
pl_orbeccenformat       6153
pl_orbeccen_solnid       938
pl_orbeccen_reflink      938
pl_eqt                  1563
pl_eqterr1              4344
pl_eqterr2              4344
pl_eqtsymerr            4132
pl_eqtlim               1563
pl_eqtstr               1563
pl_eqtformat            6153
pl_eqt_solnid           1563
pl_eqt_reflink          1563
pl_occdep               6118
pl_occdeperr1           6121
pl_occdeperr2           6121
pl_occdepsymerr         6118
pl_occdeplim            6118
pl_occdepstr            6118
pl_occdepformat         6153
pl_occdep_solnid        6118
pl_occdep_reflink       6118
pl_insol                1840
pl_insolerr1            2517
pl_insolerr2            2517
pl_insolsymerr          2300
pl_insollim             1840
pl_insolstr             1840
pl_insolformat          6153
pl_insol_solnid         1840
pl_insol_reflink        1840
pl_dens                  139
pl_denserr1             4741
sy_umagerr1             5426
sy_umagerr2             5428
sy_umaglim              6153
sy_umagsymerr           5419
sy_umagstr              5419
sy_umagformat           6153
sy_umag_solnid             0
sy_umag_reflink            0
sy_rmag                 2652
sy_rmagerr1             5275
sy_rmagerr2             5428
sy_rmaglim              6153
sy_rmagsymerr           2652
sy_rmagstr              2652
sy_rmagformat           6153
sy_rmag_solnid             0
sy_rmag_reflink            0
sy_imag                 2706
sy_imagerr1             5283
sy_imagerr2             5428
sy_imaglim              2706
sy_imagsymerr           2706
sy_imagstr              2706
sy_imagformat           6153
sy_imag_solnid             0
sy_imag_reflink            0
sy_zmag                 2919
sy_zmagerr1             5421
sy_zmagerr2             5428
sy_zmaglim              6153
sy_zmagsymerr           2919
sy_zmagstr              2919
sy_zmagformat           6153
sy_zmag_solnid             0
sy_zmag_reflink            0
sy_w1mag                 614
sy_w1magerr1             683
sy_w1magerr2             949
sy_w1maglim             6153
sy_w1magsymerr           614
sy_w1magstr              614
sy_w1magformat          6153
sy_w1mag_solnid            0
sy_w1mag_reflink           0
sy_w2mag                 613
sy_w2magerr1             665
sy_w2magerr2             938
sy_w2maglim             6153
sy_w2magsymerr           613
sy_w2magstr              613
sy_w2magformat          6153
sy_w2mag_solnid            0
sy_w2mag_reflink           0
sy_w3mag                 614
sy_w3magerr1            1635
sy_w3magerr2            1915
sy_w3maglim             6153
sy_w3magsymerr           614
sy_w3magstr              614
sy_w3magformat          6153
sy_w3mag_solnid            0
sy_w3mag_reflink           0
sy_w4mag                 615
sy_w4magerr1            4631
sy_w4magerr2            4631
sy_w4maglim             6153
sy_w4magsymerr           615
sy_w4magstr              615
sy_w4magformat          6153
sy_w4mag_solnid            0
sy_w4mag_reflink           0
sy_gmag                 2669
sy_gmagerr1             5286
sy_gmagerr2             5428
sy_gmaglim              6153
sy_gmagsymerr           2669
sy_gmagstr              2669
sy_gmagformat           6153
sy_gmag_solnid             0
sy_gmag_reflink            0
sy_gaiamag               339
sy_gaiamagerr1           339
sy_gaiamagerr2           339
sy_gaiamaglim           6153
sy_gaiamagsymerr         339
sy_gaiamagstr            339
sy_gaiamagformat        6153
sy_gaiamag_solnid          0
sy_gaiamag_reflink         0
sy_tmag                  288
sy_tmagerr1              297
sy_tmagerr2              297
sy_tmaglim              6153
sy_tmagsymerr            288
sy_tmagstr               288
sy_tmagformat           6153
sy_tmag_solnid             0
sy_tmag_reflink            0
sy_name                    0
pl_controv_flag            0
pl_orbtper_systemref    5351
pl_tranmid_systemref    1314
st_metratio              568
st_spectype             3845
st_spectype_solnid      3845
st_spectype_reflink     3845
sy_plxlim                390
sy_kepmag               2689
sy_kepmagerr1           6153
sy_kepmagerr2           6153
sy_kepmaglim            6153
sy_kepmagsymerr         2689
sy_kepmagstr            2689
sy_kepformat            6153
sy_kepmag_solnid           0
sy_kepmag_reflink          0
st_rotp                 5263
st_rotperr1             5440
st_rotperr2             5440
st_rotpsymerr           5263
st_rotplim              5263
st_rotpstr              5263
st_rotpformat           6153
st_rotp_solnid          5263
st_rotp_reflink         5263
pl_projobliq            5923
pl_projobliqerr1        5925
pl_projobliqerr2        5925
pl_projobliqsymerr      5923
pl_projobliqlim         5923
pl_projobliqstr         5923
pl_projobliqformat      6153
pl_denserr2             4741
pl_denssymerr           4664
pl_denslim               139
pl_densstr               139
pl_densformat           6153
pl_dens_solnid          4664
pl_dens_reflink          139
pl_trandep              1775
pl_trandeperr1          1888
pl_trandeperr2          1888
pl_trandepsymerr        4709
pl_trandeplim           1775
pl_trandepstr           1775
pl_trandepformat        6153
pl_trandep_solnid       1775
pl_trandep_reflink      1775
pl_tranmid              1264
pl_tranmiderr1          1322
pl_tranmiderr2          1322
pl_tranmidsymerr        1708
pl_tranmidlim           1264
pl_tranmidstr           1264
pl_tranmidformat        6153
pl_tranmid_solnid       1264
pl_tranmid_reflink      1264
pl_trandur              1681
pl_trandurerr1          1779
pl_trandurerr2          1779
pl_trandursymerr        2395
pl_trandurlim           1681
pl_trandurstr           1681
pl_trandurformat        6153
pl_trandur_solnid       1681
pl_trandur_reflink      1681
pl_rvamp                3666
pl_rvamperr1            3747
pl_rvamperr2            3747
pl_rvampsymerr          3666
pl_rvamplim             3666
pl_rvampstr             3666
pl_rvampformat          6153
pl_rvamp_solnid         3666
pl_rvamp_reflink        3666
pl_radj                   50
pl_radjerr1             1931
pl_radjerr2             1931
pl_radjsymerr           1623
pl_radjlim                50
pl_radjstr                50
pl_radjformat           6153
pl_radj_solnid          1549
pl_radj_reflink           50
pl_rade                   50
pl_radeerr1             1931
pl_radeerr2             1931
pl_radesymerr           1623
pl_radelim                50
pl_radestr                50
pl_radeformat           6153
pl_rade_solnid          1549
pl_rade_reflink           50
pl_ratror               1752
pl_ratrorerr1           1791
pl_ratrorerr2           1791
pl_ratrorsymerr         2495
pl_ratrorlim            1752
pl_ratrorstr            1752
pl_ratrorformat         6153
pl_ratror_solnid        1752
pl_ratror_reflink       1752
pl_ratdor               1788
pl_trueobliq            6086
pl_trueobliqerr1        6093
pl_trueobliqerr2        6093
pl_trueobliqsymerr      6086
pl_trueobliqlim         6086
pl_trueobliqstr         6086
pl_trueobliqformat      6153
pl_trueobliq_solnid     6086
pl_trueobliq_reflink    6086
st_log_rhk              5493
st_log_rhkerr1          5862
st_log_rhkerr2          5862
st_log_rhksymerr        5493
st_log_rhklim           5493
st_log_rhkstr           5493
st_log_rhkformat        6153
st_log_rhk_solnid       5493
st_log_rhk_reflink      5493
st_metn                 6153
sy_icmag                5801
sy_icmagerr1            5938
sy_icmagerr2            6135
sy_icmagsymerr          5801
sy_icmagstr             5801
sy_icmagformat          6153
sy_icmag_solnid            0
sy_icmag_reflink           0
pl_pubdate              6153
dkin_flag                  0
pl_ratdorerr1           1807
pl_ratdorerr2           1807
pl_ratdorsymerr         4307
pl_ratdorlim            1788
pl_ratdorstr            1788
pl_ratdorformat         6153
pl_ratdor_solnid        1788
pl_ratdor_reflink       1788
pl_imppar               1777
pl_impparerr1           1837
pl_impparerr2           1837
pl_impparsymerr         3622
pl_impparlim            1777
pl_impparstr            1777
pl_impparformat         6153
pl_imppar_solnid        1777
pl_imppar_reflink       1777
pl_cmassj               6069
pl_cmassjerr1           6071
pl_cmassjerr2           6071
pl_cmassjsymerr         6069
pl_cmassjlim            6069
pl_cmassjstr            6069
pl_cmassjformat         6153
pl_cmassj_solnid        6069
pl_cmassj_reflink       6069
pl_cmasse               6069
pl_cmasseerr1           6071
pl_cmasseerr2           6071
pl_cmassesymerr         6069
pl_cmasselim            6069
pl_cmassestr            6069
pl_cmasseformat         6153
pl_cmasse_solnid        6069
pl_cmasse_reflink       6069
pl_massj                3800
pl_massjerr1            4036
pl_massjerr2            4036
pl_massjsymerr          3800
pl_massjlim             3800
pl_massjstr             3800
pl_massjformat          6153
pl_massj_solnid         3800
pl_massj_reflink        3800
pl_masse                3800
pl_masseerr1            4036
pl_masseerr2            4036
pl_massesymerr          3800
pl_masselim             3800
pl_massestr             3800
pl_masseformat          6153
pl_masse_solnid         3800
pl_masse_reflink        3800
pl_bmassj                 31
pl_bmassjerr1           3164
pl_bmassjerr2           3164
pl_bmassjsymerr         2897
pl_bmassjlim              31
pl_bmassjstr              31
pl_bmassjformat         6153
pl_bmassj_solnid        6153
pl_bmassj_reflink          0
pl_bmasse                 31
pl_bmasseerr1           3164
pl_bmasseerr2           3164
pl_bmassesymerr         2897
pl_bmasselim              31
pl_bmassestr              31
pl_bmasseformat         6153
pl_bmasse_solnid        6153
pl_bmasse_reflink          0
pl_bmassprov               0
pl_msinij               4831
pl_msinijerr1           4875
pl_msinijerr2           4875
pl_msinijsymerr         4831
pl_msinijlim            4831
pl_msinijstr            4831
pl_msinijformat         6153
pl_msinij_solnid        4831
pl_msinij_reflink       4831
pl_msinie               4831
pl_msinieerr1           4875
pl_msinieerr2           4875
pl_msiniesymerr         4831
pl_msinielim            4831
pl_msiniestr            4831
pl_msinieformat         6153
pl_msinie_solnid        4831
pl_msinie_reflink       4831
st_teff                  290
st_tefferr1              490
st_tefferr2              490
st_teffsymerr            677
st_tefflim               290
st_teffstr               290
st_teffformat           6153
st_teff_solnid           290
st_teff_reflink          290
st_met                   550
st_meterr1               834
st_meterr2               834
st_metsymerr             953
st_metlim                550
st_metstr                550
st_metformat            6153
st_met_solnid            550
st_met_reflink           550
st_radv                 3768
st_radverr1             3831
st_radverr2             3875
st_radvsymerr           3768
st_radvlim              3768
st_radvstr              3768
st_radvformat           6153
st_radv_solnid          3768
st_radv_reflink         3768
st_vsin                 3878
st_vsinerr1             4572
st_vsinerr2             4586
st_vsinsymerr           3878
st_vsinlim              3878
st_vsinstr              3878
st_vsin_solnid          3878
st_vsin_reflink         3878
st_vsinformat           6153
st_lum                   308
st_lumerr1              2473
st_lumerr2              2479
st_lumsymerr             466
st_lumlim                308
st_lumstr                309
st_lumformat            6153
st_lum_solnid            466
st_lum_reflink           308
st_logg                  318
st_loggerr1              496
st_loggerr2              496
st_loggsymerr            712
st_logglim               318
st_loggstr               318
st_loggformat           6153
st_logg_solnid           318
st_logg_reflink          318
st_age                  1310
st_ageerr1              1565
st_ageerr2              1565
st_agesymerr            1710
st_agelim               1242
st_agestr               1310
st_ageformat            6153
st_age_solnid           1310
st_age_reflink          1310
st_mass                    8
st_masserr1              276
st_masserr2              277
st_masssymerr            488
st_masslim                 8
st_massstr                 8
st_massformat           6153
st_mass_solnid             8
st_mass_reflink            8
st_dens                  583
st_denserr1              713
st_denserr2              713
st_denssymerr           1932
st_denslim               583
st_densstr               583
st_densformat           6153
st_dens_solnid           583
st_dens_reflink          583
st_rad                   314
st_raderr1               472
st_raderr2               473
st_radsymerr             696
st_radlim                314
st_radstr                314
st_radformat            6153
st_rad_solnid            314
st_rad_reflink           314
systemid                   0
ttv_flag                   0
ptv_flag                   0
tran_flag                  0
rv_flag                    0
ast_flag                   0
obm_flag                   0
micro_flag                 0
etv_flag                   0
ima_flag                   0
pul_flag                   0
disc_refid                 0
sy_snum                    0
sy_pnum                    0
sy_mnum                    0
st_nphot                   0
st_nrvc                    0
st_nspec                   0
pl_nespec                  0
pl_ntranspec               0
pl_nnotes                  0
sy_pm                    302
sy_pmerr1                305
sy_pmerr2                315
sy_pmsymerr              302
sy_pmlim                6153
sy_pmstr                 302
sy_pmformat             6153
sy_pm_solnid               0
sy_pm_reflink              0
sy_pmra                  302
sy_pmraerr1              305
sy_pmraerr2              315
sy_pmrasymerr            302
sy_pmralim              6153
sy_pmrastr               302
sy_pmraformat           6153
sy_pmra_solnid             0
sy_pmra_reflink            0
sy_pmdec                 302
sy_pmdecerr1             305
sy_pmdecerr2             315
sy_pmdecsymerr           302
sy_pmdeclim             6153
sy_pmdecstr              302
sy_pmdecformat          6153
sy_pmdec_solnid            0
sy_pmdec_reflink           0
sy_plx                   390
sy_plxerr1               390
sy_plxerr2               390
sy_plxsymerr             390
sy_plxstr                390
sy_plxformat            6153
sy_plx_solnid              0
sy_plx_reflink             0
sy_dist                   27
sy_disterr1              134
sy_disterr2              134
sy_distsymerr             27
sy_distlim                27
sy_diststr                27
sy_distformat           6153
sy_dist_solnid             0
sy_dist_reflink            0
sy_bmag                  416
sy_bmagerr1              433
sy_bmagerr2              464
sy_bmaglim              6153
sy_bmagsymerr            416
sy_bmagstr               416
sy_bmagformat           6153
sy_bmag_solnid             0
sy_bmag_reflink            0
sy_vmag                  295
sy_vmagerr1              303
sy_vmagerr2              308
sy_vmaglim               295
sy_vmagsymerr            295
sy_vmagstr               295
sy_vmagformat           6153
sy_vmag_solnid             0
sy_vmag_reflink            0
sy_jmag                  303
sy_jmagerr1              322
sy_jmagerr2              322
sy_jmaglim               303
sy_jmagsymerr            303
sy_jmagstr               303
sy_jmagformat           6153
sy_jmag_solnid             0
sy_jmag_reflink            0
sy_hmag                  288
sy_hmagerr1              310
sy_hmagerr2              310
sy_hmaglim               288
sy_hmagsymerr            288
sy_hmagstr               288
sy_hmagformat           6153
sy_hmag_solnid             0
sy_hmag_reflink            0
sy_kmag                  282
sy_kmagerr1              319
sy_kmagerr2              330
sy_kmaglim               282
sy_kmagsymerr            282
sy_kmagstr               282
sy_kmagformat           6153
sy_kmag_solnid             0
sy_kmag_reflink            0
sy_umag                 5419
pl_projobliq_solnid     5923
pl_projobliq_reflink    5923
x                          0
y                          0
z                          0
htm20                      0
gaia_dr2_id              340
gaia_dr3_id              374
cb_flag                    0
pl_angsep                345
pl_angseperr1           6153
pl_angseperr2           6153
pl_angseplim             345
pl_angsepformat         6153
pl_angsepstr             345
pl_angsepsymerr         6153
pl_angsep_reflink        345
pl_ndispec                 0
Masse_10^24kg             31
Gravity_G_earth           74
dtype: int64

In [59]:
df["Masse_10^24kg"] = df["pl_bmasse"].apply(lambda x: x * 5.972)
df["Masse_10^24kg"]

0           21.320040
1           65.692000
2            2.609764
3           60.317200
4          111.676400
5           28.068400
7           35.772280
8           39.773520
10          39.773520
11         512.481805
12          21.558920
13          48.970400
18          56.315960
19         359.514400
20          80.024800
22         150.494400
23          44.551120
24          48.074600
25          32.965440
26          26.455960
28          21.558920
32          34.995920
33          42.580360
34          27.590640
36          15.945240
37           8.719120
38          22.633880
40          15.945240
42          76.441600
43          15.706360
46          59.182520
51         584.061600
54          37.623600
56          13.735600
57       41110.710520
58        2600.268520
59        4103.650603
60        1328.656532
61       17902.607998
63        4612.336247
65         131.981200
66        2600.268520
67       18506.194654
69        1803.167684
70       37958.032000
71        1879.090534
72        5105.837244
74         624.468570
75        1328.602784
77        1552.720000
79       21048.851480
80        2543.428218
81         821.868969
82        3985.802380
83          29.680840
87        4319.090742
91        3606.335369
93         665.400240
95        2087.811200
97        1613.299968
98        5371.541628
100       2486.485796
103       7402.514964
106         40.788760
110         87.191200
114      16664.447960
115       1404.494960
116       1290.694917
117       6054.877624
119       6871.052351
121      40655.166360
123       9888.557040
124       4612.115880
125       2828.022684
126       8104.764223
127       2334.639335
129       1632.267040
131      25907.730400
132       3739.219097
134       9794.096722
136      10388.143933
137         66.468360
141        107.376560
142       3397.411080
143         62.108800
144         19.707600
146        103.912800
148        284.700170
150       1043.899628
151          0.119440
154         23.290800
157         19.707600
158       6586.041040
159        958.488084
160       1677.833400
161        398.577252
163      18410.601040
164       1954.940172
165       1537.377932
166         32.846000
167      41753.656040
168       4956.760000
169         66.229480
170       4422.325720
171      14234.859200
172         50.164800
173       2482.584288
174       1176.758712
175       2960.917600
176       6396.250880
177        417.562240
178        103.315600
181         41.206800
184        428.789600
185         52.673040
188       5864.802600
189      17271.621200
190       2144.831259
191        146.146784
192       6529.397814
193      27103.450212
195         97.940800
198       2218.765216
199       4764.158829
200      13855.637200
202      11346.800000
203      13914.760000
204        816.174727
205      14424.768800
206         95.552000
207        139.744800
208       4744.754000
210       9490.356233
212        149.300000
214       5618.099280
215        907.242352
216         28.187840
221         22.753320
223        316.516000
227       4896.860840
229               NaN
230         23.888000
234       9110.741984
236         23.888000
241         53.748000
246      23855.070392
247      30369.292160
248         33.920960
253      32848.020994
255         24.485200
257        662.892000
260       3718.185116
262       3190.541000
264      11957.138400
266         33.741800
268      28547.134630
270      11198.676484
272         48.373200
276         24.724080
280        271.128800
283        256.796000
288      14614.678400
290        400.124000
291      16779.033918
292      17120.602644
294       1981.515572
295       1637.976272
296       1136.901584
297       3416.402040
298          2.627680
300         38.041640
302       2125.850451
303       7041.879620
305          3.911660
307      11388.484560
308        728.584000
309        137.953200
312      17079.920000
313       1174.906102
316         48.970400
318      12479.353968
319      15184.569973
320        716.640000
321        816.139492
322       7592.203600
324        449.828956
325      19682.998827
331       7610.955680
332      24295.311957
335        986.932720
336        512.457320
337          7.405280
342       6073.524000
343         63.303200
346      26192.415640
349      17290.791320
352        664.324936
354       9095.557414
356         15.168880
361         43.595600
367         11.346800
373       8920.376400
376        948.950800
381         10.988480
382      11388.006800
383      18790.300800
384       7166.400000
385      21447.243600
386         40.609600
389        175.576800
392        238.335951
397      12906.949168
400       1693.014224
401        668.093612
403      20902.000000
404       1176.782600
405      54093.002440
406      17423.668320
407        219.422030
410       5788.229616
415       3348.197679
417      13229.054960
419         97.642200
420       6795.095063
421         12.720360
423         53.509120
425        816.133520
426        645.334320
427        632.034676
428        633.032000
432         62.706000
436        241.047836
437        692.752000
438        102.491464
440         28.068400
442      11103.716793
443       2410.478360
444        474.475400
445       1119.821664
446        209.020000
450        106.898800
452       2866.560000
453       6588.205297
455       7212.670737
456        214.992000
461         50.523120
462      17614.189453
463       4650.097800
464       1134.680000
467       5314.482800
468       7971.939192
469       1898.080760
470       4612.313129
471       1015.240000
472        178.562800
474         50.224520
478        360.332564
481          2.329080
486         24.365760
487         50.403680
488         52.255000
490      12868.923052
491        716.042800
493         50.762000
497         33.264040
502         21.976960
507        713.648028
510        118.842800
512          2.974056
514      11388.604000
517      26573.130640
518         52.255000
521       2087.878371
523         57.331200
528         23.350520
533       1558.692000
535        806.220000
538        212.006000
542      17671.043306
544        992.653896
546       6073.858432
547        214.992000
552       1498.972000
553      19929.161200
554         39.773520
556         33.980680
558         88.982800
561          8.420520
564         97.343600
567         16.721600
570        289.642000
573        569.424228
574      11198.676484
575         18.214600
579         13.735600
582        605.487762
583         74.650000
586         25.679600
589       1786.093995
590        383.999600
593         50.762000
596         11.824560
599         88.385600
602       1898.021040
603       1062.896560
604        105.107200
607       4384.403520
608         88.982800
611         80.622000
616        394.152000
618         14.093920
620         12.839800
622          6.449760
624       7971.939192
625       2353.620142
626        569.400340
627         13.437000
628         15.945240
629       2592.765323
630         33.741800
632         29.501680
633         63.303200
635         43.715040
637       1936.122400
639      19169.522800
640       1195.713840
641        474.176800
643        170.202000
645         43.416440
647         21.081160
651         11.167640
653         80.622000
654       1080.932000
657       2258.610400
658       2600.268520
659         36.548640
661         46.283000
663         57.570080
665         31.711320
667         27.829520
669         14.631400
671        131.981200
674       2353.620142
675       1480.502993
676      19360.326715
678       1442.541378
679         75.247200
682         19.886760
684          3.822080
686         28.068400
688        143.328000
691       1613.368646
692       3972.683031
693       2032.844494
694       9489.508000
695         33.443200
697         11.824560
701         37.086120
703         36.548640
707         45.148320
715         10.809320
723        115.856800
726         40.370720
729         18.214600
731        186.923600
732         11.944000
738         47.776000
744        149.300000
750         37.384720
753         36.309760
756         13.556440
757         17.318800
763       1222.364009
764       2562.409026
765       7763.600000
766       1641.762520
768        334.432000
770         66.289200
772      24968.513960
776         14.631400
780         22.693600
785       9736.748800
787       2144.724360
789         32.189080
791        776.360000
794         33.443200
799         16.124400
804       4270.517480
806      20878.112000
807         75.247200
809      31584.063846
810        251.421200
813         38.161080
815        364.292000
819         30.696080
822         17.079920
824        149.300000
825         17.438240
829         34.458440
832      11919.445047
833        525.765735
834       6320.608931
835       1499.483800
836       3416.402040
837       1195.790879
838         45.446920
839         99.135200
842         62.706000
846         40.072120
848         34.458440
850         55.360440
854      46500.978000
855        873.106400
856       2030.838320
857       3606.353444
858       9850.989770
859        326.012598
862          8.719120
865         18.453480
868         40.609600
871          5.338968
872         29.023920
875         16.303560
877          1.534804
879         31.711320
882         20.065920
884         23.051920
886       6035.896817
888         60.317200
890         13.914760
894       1537.445416
895      11944.000000
899      17916.000000
903      18980.807600
907         45.984400
909         40.370720
912         24.126880
915         63.900400
917         23.469960
919         13.735600
921       1486.197235
922        975.613511
923       1822.157530
924       2695.274679
925       3226.737292
926       1098.988760
927        968.021188
928         42.665808
931         15.348040
933         25.261560
935         17.677120
937         18.035440
941         14.989720
945         45.685800
948          9.853800
950         41.445680
952         29.979440
955         14.452240
957      12529.168299
960         29.979440
962         18.632640
964         22.574160
968         12.839800
970         25.858760
974        655.725600
976         44.252520
979         44.849720
981         23.469960
983          6.449760
985          2.729204
987         27.112880
991         11.824560
994         17.438240
996        182.743200
1000        23.051920
1002        29.262800
1004        17.259080
1006        26.874000
1008        16.661880
1010        27.590640
1012        83.010800
1013        34.995920
1015        37.922200
1017        25.022680
1019         2.848644
1021     43465.831547
1022        66.289200
1025         8.420520
1028         6.509480
1031        50.762000
1033        11.466240
1038        18.453480
1040        15.348040
1042       126.009200
1043       314.724400
1044        35.772280
1046       564.354000
1048        14.810560
1050        17.318800
1053        13.198120
1055      1385.598955
1056        17.079920
1058        90.774400
1061        19.110400
1064      1527.955012
1065      5694.213740
1066        26.635120
1068        22.156120
1069        20.065920
1071         6.199832
1075        19.229840
1077        32.726560
1082       307.489083
1085        68.080800
1087        42.281760
1090        50.463400
1092        10.212120
1094     28528.010836
1096        45.148320
1098              NaN
1099       318.904800
1100        44.252520
1101       142.133600
1103      1934.928000
1106        20.483960
1109        19.050680
1112        11.466240
1114     14478.487469
1116        23.231080
1119        51.657800
1122              NaN
1123              NaN
1124        10.809320
1126        33.980680
1130        15.706360
1133        25.022680
1135        26.157360
1138        16.303560
1140        24.604640
1143       621.088000
1145       142.730800
1151        17.079920
1154        14.989720
1158     21448.205087
1159        29.023920
1161        24.604640
1165        98.538000
1167              NaN
1168         9.256600
1170        16.482720
1172      5447.464478
1174        17.677120
1177       910.861384
1182     47318.916178
1184        37.026400
1188        20.663120
1190        24.588283
1193        50.224520
1194        27.590640
1196        39.773520
1199         4.473028
1202        29.023920
1205        19.886760
1208      1278.008000
1210        22.156120
1213        14.273080
1216        40.370720
1220        14.093920
1223        37.922200
1226        16.661880
1230        53.807720
1232        47.776000
1236        31.950200
1240        11.466240
1243              NaN
1244              NaN
1245         4.138596
1249        18.811800
1251        57.570080
1253       100.926800
1256        34.458440
1260        43.416440
1265        43.117840
1269        24.365760
1272         5.398688
1276        28.665600
1279         3.380152
1282        14.810560
1287        41.804000
1290         6.031720
1294        11.167640
1298        13.914760
1302        53.807720
1307         3.822080
1309         3.583200
1313        18.035440
1318        10.809320
1321        22.574160
1325        85.399600
1327        18.453480
1329        12.362040
1332        42.580360
1334        27.590640
1337              NaN
1340        47.178800
1341      1465.188396
1345        24.843520
1349        14.452240
1352         1.618412
1354        45.446920
1357        31.711320
1359         1.881180
1362        33.443200
1366         8.181640
1368        30.218320
1370         9.853800
1373        34.995920
1376        19.647880
1379         6.031720
1382         5.016480
1385        20.245080
1387        49.866200
1390        20.902000
1393        79.427600
1395         9.017720
1398         2.496296
1400        12.362040
1402       266.351200
1405        41.744280
1408        19.886760
1411        51.060600
1414        13.556440
1417        16.124400
1419        18.811800
1423        21.738080
1426        22.156120
1429        58.525600
1431        17.079920
1433        32.189080
1436         7.405280
1438        12.839800
1440        19.886760
1443        12.182880
1445        18.035440
1448         5.595764
1451        12.362040
1453        19.886760
1456         8.420520
1458      2262.512266
1459      1024.958473
1460        69.334920
1464       262.768000
1465       808.582404
1466       117.051200
1468        40.072120
1472        75.844400
1474         3.822080
1476        15.348040
1479         6.210880
1482        19.229840
1485        13.914760
1487        16.482720
1492        17.856280
1494        36.309760
1498        15.348040
1502        42.878960
1507        24.604640
1511        20.902000
1513         6.449760
1515        40.609600
1518        43.595600
1521        87.788400
1524        25.261560
1527        32.427960
1530        33.980680
1533        10.809320
1536       173.188000
1541        48.373200
1545        72.261200
1547      2752.076760
1548      8958.000000
1549        30.934960
1551        61.511600
1553        31.472440
1555        25.500440
1558       161.244000
1560      1803.176722
1561        25.679600
1562        96.149200
1563        28.307280
1565        22.156120
1568        18.214600
1570        44.849720
1573        51.060600
1575        19.886760
1577      2638.332256
1578       312.613901
1579       111.986204
1581     24105.625652
1583        19.647880
1585        30.934960
1587        47.477400
1590        33.741800
1593       128.995200
1597        22.574160
1599        34.219560
1604        16.124400
1607        31.472440
1611        85.399600
1614        52.553600
1617        56.017360
1619              NaN
1622              NaN
1625        36.548640
1629        17.259080
1631       150.494400
1634        33.443200
1637        16.900760
1640        48.373200
1644      1129.311172
1645        74.052800
1649        16.303560
1651       389.104606
1652     13723.055113
1654       340.404000
1657      2106.859084
1658              NaN
1661        16.124400
1663         3.672780
1665        59.720000
1668        37.623600
1670        60.914400
1673        48.970400
1676      2353.608346
1677        23.888000
1679        34.637600
1682      2866.087582
1683       229.922000
1684        44.790000
1685      1860.119145
1686        19.886760
1688        18.453480
1692        48.492640
1695        45.208040
1697         1.732661
1701        50.164800
1707       291.433600
1708       228.130400
1709        74.052800
1711      1860.109822
1712        62.108800
1713              NaN
1714        25.500440
1717        55.539600
1721        34.219560
1723      2054.368000
1725     23888.000000
1727       550.439240
1728        13.556440
1729        54.345200
1733       744.043929
1735        65.692000
1738       876.570160
1742        19.647880
1746        36.309760
1748        27.829520
1750       269.934400
1753        69.872400
1755        47.357960
1760        58.824200
1762        29.740560
1764     17802.010222
1765        93.760400
1768        15.706360
1770        52.852200
1772        31.651600
1776        17.916000
1780        17.856280
1782        13.198120
1784       109.287600
1786        47.477400
1788        91.968800
1791     12324.176604
1794       100.329600
1796        48.373200
1797      1715.856407
1799      1387.497036
1800        34.458440
1803        27.590640
1805        48.373200
1809        49.269000
1811         9.256600
1813        32.726560
1818        17.259080
1821        26.874000
1824       143.925200
1826        31.651600
1830        57.271480
1832        36.070880
1834        57.868680
1836        38.698560
1838        38.161080
1840        10.510720
1843        49.567600
1845        19.349280
1848        95.552000
1849       149.897200
1850       126.009200
1852        36.011160
1855       381.512321
1857       227.533200
1858      2799.655089
1862        24.604640
1863      1188.192600
1864      6643.249363
1865              NaN
1866      2048.396000
1867        21.976960
1870       246.749262
1872     10116.770451
1873        25.261560
1874        94.357600
1877        37.922200
1880        47.178800
1882        10.212120
1887        19.886760
1888        51.777240
1890        43.416440
1893        39.892960
1896       220.964000
1897      1620.890380
1898      3682.276674
1899        20.304800
1902      1594.344840
1903      8199.708883
1904        21.797800
1906      9794.047632
1909      1142.644618
1910        49.567600
1911       400.476348
1912       373.906920
1913      1746.234299
1914       721.270689
1915      1976.732000
1916      2277.685496
1917       569.424228
1918      6206.724085
1919      4479.448142
1920       105.704400
1921        45.327480
1922       123.620400
1923        40.072120
1924        33.443200
1925       154.674800
1926       200.659200
1928        14.093920
1929      5810.756000
1931        11.944000
1932        93.640960
1936              NaN
1937       140.457976
1938      3321.641330
1940      3929.007480
1941        31.173840
1942     43595.600000
1943     17916.000000
1944       716.640000
1945        27.829520
1950     22776.854959
1951     24466.138369
1952              NaN
1953        43.845446
1954      7592.284986
1956      1767.113188
1957        90.774400
1959      1687.385338
1960      6889.998625
1961       378.027600
1962       683.256520
1964        24.485200
1968        35.234800
1972        29.979440
1977      2013.863686
1978     10970.906793
1979      1765.144040
1981       892.037640
1982        65.094800
1986        17.677120
1991        23.231080
1996        26.276800
2002      1708.272684
2003        26.993440
2005        40.012400
2007      5656.280665
2008       812.378565
2010      4270.660305
2011      1176.758712
2012     25054.540455
2013       197.399410
2014      1328.649873
2015       918.671088
2016      1750.030461
2017        67.423880
2020      1385.592010
2021     35626.797299
2023       205.436800
2024        33.443200
2026      5732.175165
2028      1765.206259

In [60]:
df["Gravity_G_earth"] = df["pl_bmasse"] * df["pl_rade"]
df["Gravity_G_earth"]

0             6.104700
1            36.555356
2             0.349600
3            31.815000
4            84.909307
5             9.447000
7            13.896800
8            16.450200
10           16.450200
11          952.536510
12            6.209200
13           22.878000
18           28.572900
19          543.606000
20           49.848000
22           95.079600
23           19.694400
24           22.218000
25           12.199200
26            8.603348
28            9.855300
32           13.419400
33           18.324100
34            9.193800
36            3.844800
37            1.635200
38            5.385590
40            3.844800
42           46.464000
43            3.760900
46           30.919200
51          175.062000
54           15.057000
56            3.036000
57        77925.861200
58         5921.576000
59         9281.207741
60         3114.734000
61        37471.969185
63        10271.947770
65          110.500000
66         5921.576000
67        38735.337103
69         4166.730416
70       213561.600000
71         4342.171696
72        11285.507640
74         1307.075875
75         3114.608000
77         3614.000000
79        43704.916000
80         5792.133920
81         1967.971577
82         8943.361000
83            8.299900
87         9618.872550
91         8091.911242
93         1448.460000
95         4789.520000
97         3755.001600
98        11872.797972
100        5662.459280
103       16113.981000
106          17.143300
110          57.232000
114       34880.375000
115        3292.520000
116        3025.741600
117       13281.797870
119       14957.079800
121       82372.323000
123       21194.496000
124        8827.274700
125        6440.239200
126       17506.942143
127        5355.753330
129        3799.148000
131       53359.860000
132        8390.076340
134       20992.035840
136       22265.278355
137          33.390000
141          79.651400
142        7680.015000
143          33.384000
144           3.329700
146          64.519200
148         375.182575
150        1996.549109
151           0.006760
154           7.020000
157           5.379000
158       16189.397600
159        1726.947720
160        3029.483850
161         640.713600
163       39046.998120
164        4990.138644
165        2568.131656
166          12.155000
167       82338.321576
168       10956.000000
169          36.929700
170       11870.375300
171       30033.360000
172          23.772000
173        4123.783680
174        2760.811506
175        6693.300000
176       14030.624000
177         446.788800
178          94.977000
181          13.800000
184         718.000000
185          22.596840
188       12864.855000
189       36151.250000
190        4549.028357
191          97.936944
192       15073.888936
193       55822.578300
195         114.472000
198        4905.655712
199       10610.065711
200       29233.260000
202       24320.000000
203       29358.000000
204        1761.684174
205       29516.188000
206          66.240000
207         121.212000
208        8580.600000
210       20499.932252
212         134.500000
214       12293.590320
215        2637.717508
216           9.520240
221           7.543800
223         151.580000
227       10823.604000
229                NaN
230          36.000000
234       19679.934961
236           2.160000
241          11.790000
246       49132.177800
247       62040.416000
248          12.780000
253       67104.128621
255           4.510000
257         320.790000
260        8342.880200
262        7212.375000
264                NaN
266          12.656000
268       58317.991040
270       24002.521600
272           2.997000
276           6.292800
280          83.536000
283         104.490000
288                NaN
290         291.249000
291       43460.338889
292       30559.527482
294        4760.680748
295        2382.635612
296        3352.260548
297        7665.738000
298           0.333960
300          15.351700
302        5438.456205
303       15328.940900
305           0.567885
307       26719.173525
308         524.600000
309         203.280000
312       35750.000000
313        2773.974553
316          17.794000
318       26538.478800
319       32037.103426
320         733.200000
321        1470.609021
322       16526.900000
324         770.027029
325                NaN
331       21283.148000
332       50038.904398
335        2333.471200
336        1039.159100
337           1.326800
342       13322.700000
343          34.450000
346       21490.763000
349       11581.240000
352        1446.119252
354                NaN
356           3.556000
361          22.776000
367           3.420000
373        7916.610000
376         317.800000
381           2.197496
382       24408.320000
383       39330.000000
384       15600.000000
385       50921.042700
386          17.000000
389         174.048000
392         107.754030
397        8428.851600
400        4531.336128
401        1557.468062
403       43400.000000
404        2252.281500
405      107787.463000
406       36469.500000
407         202.079900
410         794.766960
415        7568.765684
417       28132.786000
419          68.506500
420       14791.734062
421           2.683800
423          26.342400
425        1761.547400
426        1320.493200
427         894.214767
428        1194.620000
432          17.955000
436         329.362080
437        1542.800000
438          73.968220
440           9.447000
442       23798.991116
443        4887.959300
444         870.930900
445        2446.469064
446         229.600000
450          94.870000
452        6528.000000
453       14451.689449
455       15700.723306
456          63.000000
461          22.588200
462       49987.512351
463       11430.582000
464        1998.800000
467       10474.123000
468       17353.518000
469        4386.054000
470       10271.896286
471        2414.000000
472          89.999000
474          23.800300
478          44.046010
481           1.248000
486           7.548000
487          23.952720
488          25.375000
490       27366.932813
491         145.079000
493          13.260000
497          22.391400
502           6.403200
507        1613.236500
510          93.729000
512           0.413340
514       17271.699000
517       54730.326000
518          25.375000
521        4702.271282
523          42.816000
528          20.918500
533        3627.900000
535         283.500000
538          98.690000
542       36987.280865
544        2360.295600
546       13323.433600
547          57.960000
552        3488.900000
553       41380.040000
554          16.450200
556          12.802500
558          59.004000
561           1.565100
564          45.640000
567           4.480000
570         139.195000
573        1111.517619
574       21859.846500
575           4.758000
579           3.036000
582        1134.182603
583          32.750000
586          10.191000
589        4495.522321
590         225.693000
593          24.225000
596           2.415600
599          58.460000
602        3883.760400
603        2573.590800
604          14.731200
607        7743.919680
608          41.720000
611          27.000000
616         215.160000
618           3.162400
620           2.730500
622           1.112400
624       17353.518000
625        6096.246631
626        1143.186550
627           2.931750
628           3.844800
629        6973.578952
630          12.656000
632          10.225800
633          34.450000
635          19.105200
637        4373.458000
639       37780.523000
640        2154.367200
641         343.008000
643          65.550000
645          18.902000
647           6.001000
651           2.244000
653          50.490000
654        1773.800000
657        4833.396000
658        8050.730900
659          14.382000
661          20.925000
663          29.594800
665          11.469600
667           9.320000
669           3.356500
671         143.871000
674        5389.435428
675        5196.344867
676       45058.910813
678        2555.920514
679          45.360000
682           5.461200
684           0.569600
686           9.447000
688          37.200000
691        3664.089329
692       11878.094092
693        3964.302401
694       20498.100000
695          12.488000
697           2.415600
701          14.717700
703          14.382000
707          20.109600
715           2.153900
723          90.016000
726          16.832400
729           4.758000
731         192.182000
732           4.980000
738          33.520000
744          83.250000
750          14.898800
753          14.227200
756           2.973700
757           8.323000
763        2409.000685
764        6194.573190
765       16900.000000
766        3821.249000
768         484.400000
770          36.963000
772       15134.966600
776           3.356500
780           6.726000
785       20869.120000
787        4920.081000
789          11.750200
791        1846.000000
794          12.488000
799           3.915000
804        9510.697000
806       43350.400000
807          45.360000
809       64522.032640
810         275.334000
813          15.399900
815         150.060000
819          10.896800
822           4.290000
824         134.500000
825           4.438400
829          13.097900
832       25347.781664
833         994.716069
834       14200.385715
835        3124.005769
836        7438.054140
837        3658.389239
838          20.318700
839          48.140000
842          37.800000
846          16.640800
848          13.097900
850          27.810000
854       87278.878500
855        2081.888000
856        4840.754100
857        8799.514481
858       21113.976734
859         136.475468
862           1.635200
865           4.851300
868          17.000000
871           0.873438
872           9.963000
875           3.985800
877           0.177330
879          11.469600
882           5.544000
884           6.909400
886       13240.162140
888          31.815000
890           3.098900
894        3944.711903
895       26000.000000
899       39000.000000
903       41681.910699
907          19.119100
909          16.832400
912           7.433600
915          34.882000
917           7.113300
919           3.036000
921        4435.275928
922        2636.861797
923        4548.672101
924        6323.537734
925        8176.067099
926        2143.166284
927        2598.172434
928          22.361684
931           3.623700
933           7.994700
935           4.528800
937           4.681000
941           3.488900
945          20.502000
948           1.914000
950          17.558200
952          10.491800
955           3.291200
957                NaN
960          10.491800
962           4.929600
964           6.690600
968           2.730500
970           8.313600
974         229.482000
976          19.488300
979          19.901500
981           7.113300
983           1.112400
985           0.370170
987           8.943800
991           2.415600
994           4.438400
996          74.664000
1000          6.909400
1002         10.094000
1004          4.363900
1006          8.820000
1008          4.129200
1010          9.193800
1012         63.523000
1013         13.419400
1015         15.240000
1017          7.877200
1019          0.391140
1021      87339.246244
1022         35.409000
1025          1.565100
1028          1.373400
1031         24.225000
1033          2.323200
1038          4.851300
1040          3.623700
1042        102.757000
1043        440.045000
1044         13.896800
1046        179.550000
1048          3.422400
1050         12.470000
1053          2.850900
1055       3094.792805
1056          4.290000
1058         35.112000
1061          6.880000
1064       4189.940477
1065      12490.656395
1066          8.697000
1068          6.492500
1069          5.544000
1071          1.619514
1075          5.184200
1077         12.056000
1082        424.264910
1085         38.532000
1087         18.124800
1090         23.998000
1092          2.000700
1094      58278.923678
1096         20.109600
1098               NaN
1099        449.094000
1100         19.488300
1101        124.474000
1103        913.680000
1106          5.728100
1109          5.104000
1112          2.323200
1114      30547.378116
1116          7.002000
1119         24.912000
1122               NaN
1123               NaN
1124          2.153900
1126         12.802500
1130          3.760900
1133          7.877200
1135          8.453400
1138          3.985800
1140          7.663200
1143       1300.000000
1145        125.236000
1151          4.290000
1154          3.488900
1158      44534.116389
1159          9.963000
1161          7.663200
1165         69.465000
1167               NaN
1168          1.767000
1170          4.057200
1172      12040.611371
1174          4.528800
1177        364.527580
1182      95081.546238
1184         19.530000
1188          5.812800
1190          6.258237
1193         22.984530
1194          9.193800
1196         16.450200
1199          0.696570
1202          9.963000
1205          5.461200
1208       2996.000000
1210          6.492500
1213          3.226500
1216         16.832400
1220          3.162400
1223         15.240000
1226          4.129200
1230         26.579500
1232         22.000000
1236         11.609500
1240          2.323200
1243               NaN
1244               NaN
1245          0.630630
1249          5.008500
1251         29.594800
1253         31.265000
1256         13.097900
1260         18.902000
1265         18.699800
1269          7.548000
1272          0.885920
1276         14.688000
1279          0.486760
1282          3.422400
1287         17.290000
1290          1.020100
1294          2.244000
1298          3.098900
1302         26.579500
1307          0.569600
1309          0.762000
1313          4.681000
1318          2.153900
1321          6.690600
1325         55.484000
1327          4.851300
1329          2.566800
1332         18.324100
1334          9.193800
1337               NaN
1340         21.567000
1341        721.308420
1345          7.779200
1349          3.291200
1352          0.189700
1354         20.318700
1357         11.469600
1359          0.229950
1362         12.488000
1366          1.507000
1368         10.626000
1370          1.914000
1373         13.419400
1376          5.362700
1379          1.020100
1382          0.806400
1385          5.627400
1387         23.547000
1390          5.915000
1393         49.343000
1395          1.706300
1398          0.330220
1400          2.566800
1402         67.792000
1405         17.754600
1408          5.461200
1411         24.453000
1414          2.973700
1417          3.915000
1419          5.008500
1423          6.297200
1426          6.492500
1429         30.380000
1431          4.290000
1433         11.750200
1436          1.326800
1438          2.730500
1440          5.461200
1443          2.509200
1445          4.681000
1448          0.927630
1451          2.566800
1453          5.461200
1456          1.565100
1458       5223.277794
1459       2333.530025
1460         39.822300
1464        194.920000
1465       1036.554305
1466         91.336000
1468         16.640800
1472         45.847000
1474          0.569600
1476          3.623700
1479          1.060800
1482          5.184200
1485          3.098900
1487          4.057200
1492          4.604600
1494         14.227200
1498          3.623700
1502         18.524400
1507          7.663200
1511          5.915000
1513          1.112400
1515         17.000000
1518          8.395000
1521         17.199000
1524          7.994700
1527         11.891700
1530         12.802500
1533          2.153900
1536        170.230000
1541         22.437000
1545         42.471000
1547       4857.148200
1548      19350.000000
1549         11.033400
1551         32.857000
1553         11.330500
1555          8.113000
1558        111.565325
1560       6024.282991
1561          4.687000
1562         66.976000
1563          9.574800
1565          6.492500
1568          4.758000
1570         19.901500
1573         24.453000
1575          5.461200
1577       7923.125589
1578        769.233249
1579        150.015008
1581      49648.224300
1583          5.362700
1585         11.033400
1587         21.783000
1590         12.656000
1593         65.448000
1597          4.725000
1599         12.949800
1604         10.827000
1607         11.330500
1611         55.341000
1614         17.336000
1617         28.327600
1619               NaN
1622               NaN
1625         14.382000
1629          4.363900
1631        136.332000
1634         12.488000
1637          4.216700
1640         22.437000
1644       2526.578461
1645         31.210800
1649          3.658200
1651        985.930864
1652      29183.322159
1654         79.230000
1657       4634.569754
1658               NaN
1661          3.915000
1663          0.541200
1665         31.400000
1668         15.057000
1670         32.334000
1673         22.878000
1676       6352.422917
1677          7.316000
1679         18.038000
1682       8069.136067
1683        163.347265
1684          7.612500
1685       4364.131676
1686          5.461200
1688          4.851300
1692         22.534102
1695         13.421610
1697          0.204542
1701         21.898800
1707        150.792000
1708        263.962000
1709         35.340000
1711       4074.325897
1712         35.724000
1713               NaN
1714          8.113000
1717         27.249000
1721         12.949800
1723               NaN
1725      49200.000000
1727       1271.024300
1728          2.973700
1729         22.304996
1733       1731.783424
1735         36.410000
1738        377.224600
1742          5.362700
1746         14.227200
1748          9.320000
1750        102.604000
1753         21.294000
1755         16.177200
1760         30.633500
1762         10.358400
1764      37261.407866
1765         64.213000
1768          5.575600
1770         25.842000
1772          4.346000
1776          4.830000
1780          4.604600
1782          2.850900
1784         23.607000
1786         21.783000
1788         62.216000
1791      26208.480052
1794         71.568000
1796         22.437000
1797       3146.457185
1799       3018.822001
1800         13.097900
1803          9.193800
1805          7.695000
1809          6.930000
1811          1.767000
1813         12.056000
1818          4.363900
1821          8.820000
1824         46.513000
1826          6.519000
1830         29.345400
1832         14.073200
1834         29.845200
1836         15.746400
1838         15.399900
1840          2.076800
1843         31.775565
1845          4.762800
1848         99.264000
1849        298.439000
1850        102.765440
1852         14.049900
1855        597.310817
1857        262.890000
1858               NaN
1862          7.663200
1863       2140.939519
1864       3237.082325
1865               NaN
1866       3978.800000
1867          6.403200
1870         85.114447
1872      26792.669065
1873          7.994700
1874         64.780000
1877         15.240000
1880         21.567000
1882          2.000700
1887          5.461200
1888         25.004280
1890         18.902000
1893         16.526320
1896        136.275362
1897       4511.731545
1898      10781.720901
1899          5.644000
1902       5956.100700
1903      17037.000053
1904          6.325450
1906      20991.930626
1909       3620.184383
1910         17.596000
1911        720.817191
1912        698.289330
1913       6063.471112
1914       1001.790879
1915       3736.990000
1916       5225.099011
1917       1132.892957
1918      15144.427554
1919      11182.076947
1920         47.736900
1921         20.240674
1922         99.567000
1923         16.640800
1924         12.488000
1925        142.450000
1926        215.040000
1928          3.162400
1929      12746.300000
1931          2.397612
1932         55.350400
1936               NaN
1937        161.868316
1938       7508.733750
1940       8815.924353
1941         11.170800
1942      87600.000000
1943      55941.000000
1944       1632.000000
1945          9.320000
1950      47292.866962

In [61]:
df["Score_roch"] = df["pl_dens"] * (1/df["pl_rade"])**3
df["Score_roch"]

C:\Users\berna\AppData\Local\Temp\ipykernel_13096\3466090409.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["Score_roch"] = df["pl_dens"] * (1/df["pl_rade"])**3

0        7.839669e-01
1        4.495820e-02
2        9.160156e+00
3        5.694929e-02
4        1.175037e-02
5        3.915966e-01
7        2.114170e-01
8        1.612558e-01
10       1.612558e-01
11       2.522610e-04
12       7.664419e-01
13       9.531423e-02
18       6.686288e-02
19       6.097939e-04
20       2.777840e-02
22       4.393914e-02
23       1.211973e-01
24       9.988311e-02
25       2.603332e-01
26       4.532593e-01
28       4.423383e-02
32       2.231662e-01
33       1.360857e-01
34       4.085984e-01
36       1.644349e+00
37       4.064265e+00
38       2.517246e+00
40       1.644349e+00
42       3.073247e-02
43       1.689347e+00
46       5.893717e-02
51       1.633731e+01
54       1.860544e-01
56       2.391338e+00
57       1.819972e-02
58       3.780627e-04
59       5.803290e-04
60       1.625364e-04
61       4.316160e-03
63       7.650989e-04
65       7.776000e-03
66       3.780627e-04
67       4.464640e-03
69       2.401000e-04
70       2.427962e-05
71       2.503737e-04
72       8.869689e-04
74       1.505280e-04
75       1.625364e-04
77       1.980921e-04
79       5.349770e-03
80       3.697143e-04
81       8.857102e-05
82       6.317266e-04
83       1.202371e+00
87       7.183429e-04
91       5.735413e-04
93       1.269914e-04
95       2.905085e-04
97       2.059116e-04
98       9.347956e-04
100      3.617634e-04
103      1.411015e-03
106      1.498743e-01
110      2.207971e-02
114      4.019200e-03
115      1.716472e-04
116      1.577988e-04
117      1.103158e-03
119      1.310878e-03
121      1.191040e-02
123      2.069473e-03
124      1.888471e-03
125      4.094685e-04
126      1.616443e-03
127      3.247318e-04
129      2.081457e-04
131      6.878514e-03
132      5.943218e-04
134      2.050400e-03
136      2.174377e-03
137      7.814815e-02
141      1.311275e-02
142      5.161815e-04
143      5.230353e-02
144      6.717004e+00
146      2.412603e-02
148      1.101666e-03
150      4.362046e-04
151      7.380653e+01
154      6.292867e-01
157      9.675005e-01
158      6.954157e-04
159      6.421747e-04
160      9.331835e-04
161      4.690665e-04
163      4.104380e-03
164      1.185639e-04
165      1.410129e-03
166      2.594067e-01
167      1.438752e-02
168      8.608815e-04
169      4.468392e-02
170      2.403447e-04
171      3.274384e-03
172      9.000588e-02
173      2.397071e-03
174      1.454295e-04
175      4.511507e-04
176      1.165433e-03
177      6.132215e-03
178      3.565619e-03
181      6.125000e-01
184      3.950000e-04
185      1.711472e-01
188      1.067572e-03
189      4.167680e-03
190      4.640617e-04
191      2.979903e-02
192      8.776309e-04
193      7.200945e-03
195      7.939579e-04
198      3.866103e-04
199      7.906022e-04
200      3.184401e-03
202      2.374649e-03
203      3.199399e-03
204      1.811497e-04
205      4.000454e-03
206      1.747514e-02
207      6.655067e-03
208      2.778413e-03
210      1.895943e-03
212      5.663981e-03
214      1.039586e-03
215      3.285899e-05
216      3.850963e-01
221      2.086986e-01
223      4.274663e-01
227      8.521858e-04
229               NaN
230      4.115226e-05
234      1.821410e-03
236               NaN
241               NaN
246      6.341130e-03
247      8.480886e-03
248      2.405487e-01
253      9.141734e-03
255      6.536439e+00
257      4.888645e-02
260      5.901657e-04
262      4.836661e-04
264               NaN
266      2.455642e-01
268      7.985250e-03
270      2.341270e-03
272      1.735337e+04
276      1.623096e+00
280      3.210528e+00
283      1.149913e+00
288               NaN
290      3.895660e-02
291      6.079175e-04
292      6.018460e-03
294      2.065170e-04
295      3.661017e-03
296      3.479762e-05
297      5.444486e-04
298      1.264736e+01
300      1.786031e-01
302      1.514278e-04
303      1.342740e-03
305      8.469968e+00
307      1.385142e-03
308               NaN
309      2.788082e-04
312      4.121600e-03
313      1.376987e-04
316      9.051605e-01
318      2.738746e-03
319      3.489344e-03
320      1.315218e-02
321      4.839042e-04
322      1.447428e-03
324      3.650308e-04
325               NaN
331      3.456818e-04
332      6.448607e-03
335      9.946126e-05
336      8.446151e-05
337      4.538616e+00
342      1.107606e-03
343      4.952208e-02
346               NaN
349               NaN
352      1.265362e-04
354               NaN
356      1.854956e+00
361      4.214501e-02
367      2.949246e-01
373      4.903377e-03
376      4.125000e-02
381      3.487029e+00
382      2.384186e-03
383      4.531200e-03
384      1.365498e-03
385      2.427556e-03
386      1.529600e-01
389      3.754675e-03
392      2.641874e-02
397      1.298066e-03
400      9.305232e-05
401      8.523598e-05
403      5.297321e-03
404      5.089497e-04
405      1.750577e-02
406      4.203520e-03
407      4.688204e-03
410      2.720506e+00
415      5.080526e-04
417      2.899848e-03
419      1.658509e-02
420      1.297223e-03
421      2.924450e+00
423      7.634133e-02
425      1.774291e-04
426      1.424819e-04
427      1.598140e-03
428      2.535916e-04
432      2.019915e+00
436      7.545941e-04
437      1.151899e-04
438      1.473840e-02
440      3.915966e-01
442      2.322197e-03
443      5.743383e-04
444      2.049719e-04
445      2.246821e-04
446      2.125395e-03
450      4.439907e-03
452      4.174193e-04
453      1.201019e-03
455      1.374602e-03
456      6.885131e+00
461      1.187339e-01
462      7.395142e-04
463      4.267324e-04
464      7.644389e-04
467      1.839890e-03
468      1.520255e-03
469      2.530372e-04
470      7.650989e-04
471      1.138551e-04
472      2.207481e-01
474      9.000588e-02
478      2.519170e+02
481      3.967285e-03
486      5.590982e-01
487      8.880939e-02
488      8.077412e-02
490      2.821738e-03
491      2.099843e+02
493      3.239898e+00
497      1.231436e-02
502      7.289261e-01
507      1.085200e-04
510      1.004909e-02
512      8.377245e+00
514      1.884408e-02
517      7.039729e-03
518      8.077412e-02
521               NaN
523      1.014467e-02
528      1.632596e-03
533      1.988368e-04
535      3.617320e-01
538      4.700965e-01
542      4.259840e-03
544      1.114104e-04
546      1.107606e-03
547               NaN
552      1.913898e-04
553      5.045567e-03
554      1.612558e-01
556      2.405487e-01
558      2.125633e-02
561      4.145855e+00
564      3.462099e-02
567      2.880859e-01
570      4.780053e-01
573      2.209365e-04
574      4.418729e-03
575      1.161622e+00
579      2.391338e+00
582      2.850235e-04
583      4.893040e-01
586      1.329622e-01
589      1.531145e-04
590      4.851755e-02
593      8.726032e-02
596      3.298734e+00
599      2.141818e-02
602      5.096468e-04
603      1.091463e-04
604      1.313150e+02
607      2.931218e-03
608      1.225401e-01
611      2.125000e-01
616      4.444961e-01
618      2.240136e+00
620      2.816856e+00
622      4.969219e+00
624      1.520255e-03
625      1.680554e-04
626      1.856489e-04
627      2.526845e+00
628      1.644349e+00
629      1.392319e-04
630      2.455642e-01
632      3.449931e-01
633      4.952208e-02
635      1.271121e-01
637      2.969557e-04
639      6.746263e-03
640      7.063921e-04
641      3.200136e-02
643      6.410783e-01
645      1.291534e-01
647      8.039894e-01
651      3.443287e+00
653      2.714398e-02
654      1.126231e-03
657      5.078241e-04
658      6.327749e-05
659      1.995704e-01
661      1.097394e-01
663      6.324642e-02
665      2.877642e-01
667      4.000000e-01
669      2.037838e+00
671      1.602062e-03
674      2.236742e-04
675      8.904067e-06
676      2.457992e-03
678      9.436810e-04
679      3.172154e-02
682      9.408417e-01
684      7.078325e+00
686      3.915966e-01
688      9.506227e+00
691      2.817725e-04
692      1.210239e-04
693      7.539881e-04
694      1.895943e-03
695      2.497843e-01
697      3.298734e+00
701      1.923069e-01
703      1.995704e-01
707      1.174214e-01
715      3.501153e+00
723      1.071100e-02
726      1.561058e-01
729      1.161622e+00
731      3.209842e-03
732      4.469419e-02
738      7.884714e-03
744      1.083246e-01
750      1.891513e-01
753      2.037009e-01
756      2.468761e+00
757      2.791890e-02
763      4.250742e-04
764      2.592068e-04
765      1.479290e-03
766      2.092627e-04
768      7.339142e-04
770      4.468392e-02
772      3.478229e+00
776      2.037838e+00
780      6.798632e-01
785      2.036095e-03
787      2.982865e-04
789      2.760556e-01
791      8.696296e-05
794      2.497843e-01
799      1.597441e+00
804      7.098418e-04
806      5.297321e-03
807      3.172154e-02
809      8.811310e-03
810      2.956462e-03
813      1.793175e-01
815      1.511392e+00
819      3.106591e-01
822      1.380741e+00
824      5.663981e-03
825      1.301324e+00
829      2.316817e-01
832      2.611816e-03
833      2.322549e-04
834      1.035040e-03
835      3.281312e-04
836      6.960829e-04
837      3.164418e-05
838      1.155817e-01
839      3.649186e-02
842      2.657750e-02
846      1.586574e-01
848      2.316817e-01
850      7.000000e-02
854      2.158604e-02
855      1.004311e-04
856      2.392085e-04
857      3.749103e-04
858      2.059937e-03
859      1.177528e+00
862      4.064265e+00
865      1.134398e+00
868      1.529600e-01
871      5.651021e+00
872      3.598323e-01
875      1.548776e+00
877      1.308944e+01
879      2.877642e-01
882      9.149345e-01
884      6.451232e-01
886      1.098710e-03
888      5.694929e-02
890      2.312299e+00
894      1.111870e-04
895      2.275831e-03
899      3.413746e-03
903      3.431490e-03
907      1.770268e-01
909      1.561058e-01
912      5.714741e-01
915      4.906775e-02
917      6.138548e-01
919      2.391338e+00
921      4.274875e-05
922      5.540741e-05
923      1.659996e-04
924      3.017501e-04
925      2.626271e-04
926      4.051657e-04
927      5.827772e-05
928      9.766586e-02
931      1.797932e+00
933      5.095338e-01
935      1.267598e+00
937      1.197677e+00
941      1.913898e+00
945      1.132536e-01
948      3.722221e+00
950      1.451130e-01
952      3.308020e-01
955      2.102998e+00
957               NaN
960      3.308020e-01
962      1.102854e+00
964      6.762565e-01
968      2.816856e+00
970      4.747179e-01
974      7.240401e+00
976      1.231348e-01
979      1.192931e-01
981      6.138548e-01
983      4.969219e+00
985      8.900329e+00
987      4.264017e-01
991      3.298734e+00
994      1.301324e+00
996      7.985250e-01
1000     6.451232e-01
1002     3.523295e-01
1004     1.338968e+00
1006     4.356178e-01
1008     1.459070e+00
1010     4.085984e-01
1012     8.381879e-03
1013     2.231662e-01
1015     1.822917e-01
1017     5.222229e-01
1019     8.614936e+00
1021     1.336806e-02
1022     5.791430e-02
1025     4.145855e+00
1028     1.264762e+00
1031     8.726032e-02
1033     3.364265e+00
1038     1.134398e+00
1040     1.797932e+00
1042     8.657911e-03
1043     8.536836e-04
1044     2.114170e-01
1046     1.103659e+01
1048     1.974832e+00
1050     1.257751e-03
1053     2.636619e+00
1055     2.233235e-04
1056     1.380741e+00
1058     5.500393e-01
1061     1.780975e-01
1064     7.878161e-05
1065     1.036435e-03
1066     4.464000e-01
1068     7.090379e-01
1069     9.149345e-01
1071     1.211669e-02
1075     1.015987e+00
1077     2.657776e-01
1082     9.044173e-04
1085     4.195318e-02
1087     1.382828e-01
1090     8.862189e-02
1092     3.665055e+00
1094     7.985250e-03
1096     1.174214e-01
1098              NaN
1099     8.288175e-04
1100     1.231348e-01
1101     6.389121e-03
1103     2.318761e+00
1106     8.695721e-01
1109     1.044922e+00
1112     3.364265e+00
1114     3.329374e-03
1116     6.292867e-01
1119     8.330587e-02
1122              NaN
1123              NaN
1124     3.501153e+00
1126     2.405487e-01
1130     1.689347e+00
1133     5.222229e-01
1135     4.659860e-01
1138     1.548776e+00
1140     5.470208e-01
1143     1.500160e-04
1145     6.345662e-03
1151     1.380741e+00
1154     1.913898e+00
1158     5.454668e-03
1159     3.598323e-01
1161     5.470208e-01
1165     1.634984e-02
1167              NaN
1168     3.881086e+00
1170     1.501642e+00
1172     9.478393e-04
1174     1.267598e+00
1177     2.343993e-01
1182     1.458333e-02
1184     5.534959e-02
1188     8.457004e-01
1190     1.640903e+00
1193     1.107107e-01
1194     4.085984e-01
1196     1.612558e-01
1199     6.365333e+00
1202     3.598323e-01
1205     9.408417e-01
1208     1.563411e-04
1210     7.090379e-01
1213     2.170401e+00
1216     1.561058e-01
1220     2.240136e+00
1223     1.822917e-01
1226     1.459070e+00
1230     7.517809e-02
1232     1.014576e-01
1236     2.818469e-01
1240     3.364265e+00
1243              NaN
1244              NaN
1245     6.701426e+00
1249     1.072225e+00
1251     6.324642e-02
1253     7.738930e-01
1256     2.316817e-01
1260     1.291534e-01
1265     1.312307e-01
1269     5.590982e-01
1272     5.609907e+00
1276     3.214366e-02
1279     7.688002e+00
1282     1.974832e+00
1287     2.189894e-01
1290     5.231481e+00
1294     3.443287e+00
1298     2.312299e+00
1302     7.517809e-02
1307     7.078325e+00
1309     7.811039e-01
1313     1.197677e+00
1318     3.501153e+00
1321     6.762565e-01
1325     2.311206e-02
1327     1.134398e+00
1329     3.131189e+00
1332     1.360857e-01
1334     4.085984e-01
1337              NaN
1340     1.046867e-01
1341     2.085614e-02
1345     5.352334e-01
1349     2.102998e+00
1352     1.265306e+01
1354     1.155817e-01
1357     2.877642e-01
1359     1.143909e+01
1362     2.497843e-01
1366     4.252442e+00
1368     3.239391e-01
1370     3.722221e+00
1373     2.231662e-01
1376     9.628824e-01
1379     5.231481e+00
1382     5.900065e+00
1385     8.897544e-01
1387     9.141270e-02
1390     8.245613e-01
1393     2.800363e-02
1395     3.985038e+00
1398     9.451585e+00
1400     3.131189e+00
1402     1.987580e+01
1405     1.427956e-01
1408     9.408417e-01
1411     8.592073e-02
1414     2.468761e+00
1417     1.597441e+00
1419     1.072225e+00
1423     7.455023e-01
1426     7.090379e-01
1429     6.075660e-02
1431     1.380741e+00
1433     2.760556e-01
1436     4.538616e+00
1438     2.816856e+00
1440     9.408417e-01
1443     3.235051e+00
1445     1.197677e+00
1448     5.472540e+00
1451     3.131189e+00
1453     9.408417e-01
1456     4.145855e+00
1458     3.014471e-04
1459     1.476023e-04
1460     3.915387e-02
1464     3.220675e-02
1465     3.788665e-03
1466     1.047486e-02
1468     1.586574e-01
1472     3.145865e-02
1474     7.078325e+00
1476     1.797932e+00
1479     5.079117e+00
1482     1.015987e+00
1485     2.312299e+00
1487     1.501642e+00
1492     1.232112e+00
1494     2.037009e-01
1498     1.797932e+00
1502     1.339272e-01
1507     5.470208e-01
1511     8.245613e-01
1513     4.969219e+00
1515     1.529600e-01
1518     1.735843e+01
1521     3.146828e+01
1524     5.095338e-01
1527     2.703871e-01
1530     2.405487e-01
1533     3.501153e+00
1536     3.895937e-03
1541     9.833474e-02
1545     3.561225e-02
1547     1.793484e-03
1548     1.788801e-03
1549     3.052694e-01
1551     5.360153e-02
1553     2.928044e-01
1555     4.986150e-01
1558     2.962442e-02
1560     2.631393e-05
1561              NaN
1562     1.708540e-02
1563     3.833831e-01
1565     7.090379e-01
1568     1.161622e+00
1570     1.192931e-01
1573     8.592073e-02
1575     9.408417e-01
1577     7.662345e-05
1578     3.056772e-05
1579     6.640625e-04
1581     6.394869e-03
1583     9.628824e-01
1585     3.052694e-01
1587     1.030586e-01
1590     2.455642e-01
1593     3.990204e-04
1597     5.376000e+00
1599     2.365034e-01
1604     1.550840e-03
1607     2.928044e-01
1611     2.346421e-02
1614     8.266438e-01
1617     6.789234e-02
1619              NaN
1622              NaN
1625     1.995704e-01
1629     1.338968e+00
1631     5.526068e-03
1634     2.497843e-01
1637     1.420820e+00
1640     9.833474e-02
1644     1.924402e-04
1645     2.696614e-01
1649     2.576780e+00
1651     2.684005e-05
1652     3.007250e-03
1654              NaN
1657     3.749192e-04
1658              NaN
1661     1.597441e+00
1663     7.278362e+00
1665     5.717212e-02
1668     1.860544e-01
1670     5.525033e-02
1673     9.531423e-02
1676     1.241733e-04
1677     5.867503e-01
1679     3.656887e-02
1682     1.227690e-04
1683     3.613730e-02
1684              NaN
1685     2.399459e-04
1686     9.408417e-01
1688     1.134398e+00
1692     9.778981e-02
1695     1.363601e+00
1697     1.298506e+01
1701              NaN
1707     3.199606e-01
1708     1.927627e-03
1709     1.252747e-01
1711     3.395492e-04
1712     3.947660e-02
1713              NaN
1714     4.986150e-01
1717     7.712566e-02
1721     2.365034e-01
1723              NaN
1725     6.341130e-03
1727     6.101367e-05
1728     2.468761e+00
1729     2.302064e-01
1733     9.495018e-05
1735     4.605030e-02
1738     7.069389e-03
1742     9.628824e-01
1746     2.037009e-01
1748     4.000000e-01
1750     1.812418e+00
1753     1.779859e+00
1755     5.983747e-01
1760     5.983997e-02
1762     3.378186e-01
1764     4.295680e-03
1765     1.841623e-02
1768     4.722858e-02
1770     7.832241e-02
1772              NaN
1776     6.459958e-01
1780     1.232112e+00
1782     2.636619e+00
1784     2.180102e+01
1786     1.030586e-01
1788     1.941180e-02
1791     2.704572e-03
1794     1.539282e-02
1796     9.833474e-02
1797     9.136907e-04
1799     2.826285e-04
1800     2.316817e-01
1803     4.085984e-01
1805              NaN
1809     1.310941e+02
1811     3.881086e+00
1813     2.657776e-01
1818     1.338968e+00
1821     4.356178e-01
1824     1.349273e-01
1826     8.436928e+00
1830     6.421752e-02
1832     2.071255e-01
1834     6.229013e-02
1836     1.728355e-01
1838     1.793175e-01
1840     3.584836e+00
1843     1.443575e-02
1845     1.744045e+00
1848              NaN
1849     4.878298e-05
1850     8.655778e-03
1852     2.071255e-01
1855     5.248346e-04
1857     1.939064e-03
1858              NaN
1862     5.470208e-01
1863     7.062698e-04
1864              NaN
1865              NaN
1866     7.751958e-04
1867     7.289261e-01
1870     9.837773e-01
1872     5.914720e-04
1873     5.095338e-01
1874     1.828180e-02
1877     1.822917e-01
1880     1.046867e-01
1882     3.665055e+00
1887     9.408417e-01
1888     8.295973e-02
1890     1.291534e-01
1893     1.598145e-01
1896     4.002977e-02
1897     7.576193e-05
1898     1.402771e-04
1899     8.919405e-01
1902     1.179703e-05
1903     2.067539e-03
1904     7.397160e-01
1906     2.050400e-03
1909     2.288304e-05
1910     5.037716e-01
1911     2.570151e-04
1912     1.802042e-04
1913     2.242922e-05
1914     1.314212e-03
1915     8.755657e-04
1916     3.169538e-04
1917     2.053861e-04
1918     6.011492e-04
1919     3.772739e-04
1920     6.881624e-02
1921     1.160040e-01
1922     9.165685e-03
1923     1.586574e-01
1924     2.497843e-01
1925     5.138993e-03
1926     2.685547e-03
1928     2.240136e+00
1929     1.058676e-03
1931     3.691565e+00
1932     4.433130e-02
1936              NaN
1937     1.236230e-03
1938     5.039882e-04
1940     6.234144e-04
1941     2.989691e-01
1942     1.342593e-02
1943     3.917480e-04
1944     1.041561e-04
1945     1.500000e-01
1950     5.769360e-03
1951     8.849477e-03
1952              NaN
1953     1.584798e+00
1954     1.447428e-03
1956     5.137697e-04
1957     1.227026e-02
1959     2.552585e-04
1960     3.058607e-05
1961     5.370750e-04
1962     1.186973e-04
1964     1.246808e-02
1968     1.204378e-02
1972     2.081204e-01
1977     2.682575e-04
1978     2.293587e-03
1979     2.351534e-04
1981     9.609443e-05
1982     3.422533e-02
1986     1.144747e+00
1991     5.486968e-01
1996     3.779087e-02
2002     2.271769e-04
2003     2.316550e-01
2005     1.108732e-01
2007     9.826224e-04
2008     8.754510e-05
2010     7.098418e-04
2011     1.376987e-04
2012     6.230339e-03
2013     1.459010e-04
2014     6.658435e-05
2015     5.625205e-04
2016     3.623387e-04
2017     3.636812e-01
2020     2.566360e-04
2021     1.044277e-02
2023     8.242435e-03
2024     3.559836e+00
2026              NaN
2028     2.645388e-04

In [62]:
df["pl_type"] = df["Score_roch"].apply(lambda x: "Rocheuse" if x > 3.5 else "Gazeuse/Mixte")
df["pl_type"].value_counts()

C:\Users\berna\AppData\Local\Temp\ipykernel_13096\1822608203.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["pl_type"] = df["Score_roch"].apply(lambda x: "Rocheuse" if x > 3.5 else "Gazeuse/Mixte")

pl_type
Gazeuse/Mixte    5652
Rocheuse          501
Name: count, dtype: int64

In [63]:
df["sim_earth"] = (
    (1 - np.abs((df["pl_rade"] - 1) / (df["pl_rade"] + 1))) ** 0.57 *
    (1 - np.abs((df["pl_dens"] - 5.51) / (df["pl_dens"] + 5.51))) ** 1.07 *
    (1 - np.abs((df["Gravity_G_earth"] - 1) / (df["Gravity_G_earth"] + 1))) ** 0.70 *
    (1 - np.abs((df["pl_eqt"] - 288) / (df["pl_eqt"] + 288))) ** 5.58
) ** 0.25

C:\Users\berna\AppData\Local\Temp\ipykernel_13096\4252760722.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["sim_earth"] = (

In [64]:
df["sim_earth"].isna().sum()

np.int64(1661)

In [65]:
df["pl_rade"].isna().sum()

np.int64(50)

In [66]:
df["pl_dens"].isna().sum()

np.int64(139)

In [67]:
df["Gravity_G_earth"].isna().sum()

np.int64(74)

In [68]:
df["pl_eqt"].isna().sum()

np.int64(1563)

In [69]:
def impute_planets(df, max_iter=10):
    df = df.copy()

    for _ in range(max_iter):
        before_na = df[["Gravity_G_earth", "pl_dens", "pl_rade"]].isna().sum().sum()

        # g = rho * R
        mask_g = df["Gravity_G_earth"].isna() & df["pl_dens"].notna() & df["pl_rade"].notna()
        df.loc[mask_g, "Gravity_G_earth"] = df.loc[mask_g, "pl_dens"] * df.loc[mask_g, "pl_rade"]

        # rho = g / R
        mask_d = df["pl_dens"].isna() & df["Gravity_G_earth"].notna() & df["pl_rade"].notna()
        df.loc[mask_d, "pl_dens"] = df.loc[mask_d, "Gravity_G_earth"] / df.loc[mask_d, "pl_rade"]

        # R = g / rho
        mask_r = df["pl_rade"].isna() & df["Gravity_G_earth"].notna() & df["pl_dens"].notna()
        df.loc[mask_r, "pl_rade"] = df.loc[mask_r, "Gravity_G_earth"] / df.loc[mask_r, "pl_dens"]

        after_na = df[["Gravity_G_earth", "pl_dens", "pl_rade"]].isna().sum().sum()

        # stop si plus aucun progrès
        if after_na == before_na:
            break

    return df

In [ ]:
#def impute_planets(df):
#    df = df.copy()

##    # -------- PASS 1 --------
#    df["Gravity_1"] = np.where(
        df["Gravity_G_earth"].isna() & df["pl_dens"].notna() & df["pl_rade"].notna(),
        df["pl_dens"] * df["pl_rade"],
        df["Gravity_G_earth"]
    )

#    df["dens_1"] = np.where(
#        df["pl_dens"].isna() & df["Gravity_G_earth"].notna() & df["pl_rade"].notna(),
#        df["Gravity_G_earth"] / df["pl_rade"],
#        df["pl_dens"]
 #    )

#    df["rade_1"] = np.where(
#        df["pl_rade"].isna() & df["Gravity_G_earth"].notna() & df["pl_dens"].notna(),
#        df["Gravity_G_earth"] / df["pl_dens"],
 #       df["pl_rade"]
#     )

    # -------- PASS 2 --------
#    df["Gravity_2"] = np.where(
#        df["Gravity_1"].isna() & df["dens_1"].notna() & df["rade_1"].notna(),
#        df["dens_1"] * df["rade_1"],
#        df["Gravity_1"]
#     )

#    df["dens_2"] = np.where(
#        df["dens_1"].isna() & df["Gravity_1"].notna() & df["rade_1"].notna(),
#        df["Gravity_1"] / df["rade_1"],
#        df["dens_1"]
 #    )

#    df["rade_2"] = np.where(
#        df["rade_1"].isna() & df["Gravity_1"].notna() & df["dens_1"].notna(),
#        df["Gravity_1"] / df["dens_1"],
#        df["rade_1"]
#     )

    # -------- PASS 3 --------
#    df["Gravity_3"] = np.where(
#        df["Gravity_2"].isna() & df["dens_2"].notna() & df["rade_2"].notna(),
#        df["dens_2"] * df["rade_2"],
#        df["Gravity_2"]
#     )

#    df["dens_3"] = np.where(
        df["dens_2"].isna() & df["Gravity_2"].notna() & df["rade_2"].notna(),
        df["Gravity_2"] / df["rade_2"],
        df["dens_2"]
    )

#    df["rade_3"] = np.where(
#        df["rade_2"].isna() & df["Gravity_2"].notna() & df["dens_2"].notna(),
#        df["Gravity_2"] / df["dens_2"],
#        df["rade_2"]
#     )

    # -------- PASS 4 --------
 #    df["Gravity_4"] = np.where(
  #       df["Gravity_3"].isna() & df["dens_3"].notna() & df["rade_3"].notna(),
#         df["dens_3"] * df["rade_3"],
 #        df["Gravity_3"]
#     )

 #    df["dens_4"] = np.where(
 #        df["dens_3"].isna() & df["Gravity_3"].notna() & df["rade_3"].notna(),
 #        df["Gravity_3"] / df["rade_3"],
 #        df["dens_3"]
 #    )

 #    df["rade_4"] = np.where(
 #        df["rade_3"].isna() & df["Gravity_3"].notna() & df["dens_3"].notna(),
  #       df["Gravity_3"] / df["dens_3"],
  #       df["rade_3"]
 #    )

  #   # -------- FINAL --------
  #   df["Gravity_final"] = df["Gravity_4"]
  #   df["pl_dens_final"] = df["dens_4"]
  #   df["pl_rade_final"] = df["rade_4"]

  #   return df

In [70]:
df = impute_planets(df)

In [71]:
df["sim_earth"] = (
    (1 - np.abs((df["pl_rade"] - 1) / (df["pl_rade"] + 1))) ** 0.57 *
    (1 - np.abs((df["pl_dens"] - 5.51) / (df["pl_dens"] + 5.51))) ** 1.07 *
    (1 - np.abs((df["Gravity_G_earth"] - 1) / (df["Gravity_G_earth"] + 1))) ** 0.70 *
    (1 - np.abs((df["pl_eqt"] - 288) / (df["pl_eqt"] + 288))) ** 5.58
) ** 0.25

In [72]:
df["pl_rade"].isna().sum()

np.int64(50)

In [73]:
df["sim_earth"].isna().sum()

np.int64(1599)

In [74]:
df["pl_insol"].isna().sum()

np.int64(1840)

In [75]:
df["pl_insol_calc"] = df["st_lum"] / (df["pl_orbsmax"] ** 2)

# Remplacer les valeurs manquantes uniquement
df["pl_insol"] = df["pl_insol"].fillna(df["pl_insol_calc"])

In [76]:
df["pl_insol"].isna().sum()

np.int64(534)

In [77]:
df["pl_eqt"] = df["pl_eqt"].fillna(255 * (df["pl_insol"] ** 0.25))

In [78]:
df["pl_eqt"].isna().sum()

np.int64(863)

In [79]:
df["sim_earth"] = (
    (1 - np.abs((df["pl_rade"] - 1) / (df["pl_rade"] + 1))) ** 0.57 *
    (1 - np.abs((df["pl_dens"] - 5.51) / (df["pl_dens"] + 5.51))) ** 1.07 *
    (1 - np.abs((df["Gravity_G_earth"] - 1) / (df["Gravity_G_earth"] + 1))) ** 0.70 *
    (1 - np.abs((df["pl_eqt"] - 288) / (df["pl_eqt"] + 288))) ** 5.58
) ** 0.25

In [80]:
df["sim_earth"].isna().sum()

np.int64(911)

In [81]:
df["eau_possible"] = df["pl_insol"].between(0.5, 1.5).astype(int)
df["eau_possible"].isna().sum()

np.int64(0)

In [82]:
df[["eau_possible","pl_type"]].value_counts()

eau_possible  pl_type
0             Gazeuse/Mixte    5457
              Rocheuse          487
1             Gazeuse/Mixte     195
              Rocheuse           14
Name: count, dtype: int64

In [83]:
df["st_spectype"].value_counts()

st_spectype
G0 V                 65
G5 V                 62
K0                   61
M0 V                 55
G5                   54
M1 V                 50
K0 V                 44
G                    44
F8 V                 43
K2 V                 43
G8 V                 42
G9 V                 41
G2 V                 40
K3 V                 40
K0 III               39
G3 V                 38
F8                   36
G0                   36
K                    35
G6 V                 30
M                    27
F7 V                 25
K4 V                 25
F                    25
G1 V                 24
K7 V                 24
M2.5 V               23
K1 V                 22
F6 V                 22
K V                  22
G V                  22
G4 V                 21
M3.0 V               21
F9                   20
M0                   20
M4                   20
G2                   20
K5 V                 19
K1 III               19
M3.5 V               18
M1.5 V               18
M4.5 V               18
M2 V                 18
M1                   16
M3                   16
F5 V                 16
G3                   16
M V                  16
M3 V                 15
K1                   14
G9                   14
G4                   13
G8                   13
K2.5 V               13
K2                   13
K2 III               12
K3                   12
K7                   12
M1.0 V               12
F9 V                 11
K6 V                 11
F6                   11
G8 IV                11
K0 IV                10
K5                   10
M4 V                 10
M5.5 V               10
M2                    9
K4                    9
M3.5                  8
F5                    8
G7 V                  8
F7                    8
G7                    8
G6                    7
K1 IV                 7
M2.5                  7
G5 IV                 7
M0.0 V                7
M8.0 V                7
F V                   7
M0.5 V                7
K0 III-IV             7
G5V                   6
G2 IV                 6
G3 IV                 6
K0.0 V                6
G8 III                6
M5.0 V                6
M2.0 V                6
G5 IV/V               6
G0 IV                 6
K2V                   6
K3 III                5
M3.0                  5
G8/K0 IV              5
K8 V                  5
K3 IV                 5
G0V                   5
G3 IV-V               5
K4 III                5
G5IV                  5
K0V                   5
G2/G3 V               5
G9 III                5
F9.5 V                5
F3 V                  4
M2.5V                 4
K5 III                4
A5 V                  4
K4.5 V                4
WD                    4
G8.5V                 4
K0.5 V                4
M0.0                  4
M6 V                  4
G1                    4
M3.5-4 V              4
M0.5                  4
M2V                   4
K3V                   4
M4.0 V                4
K2 III-IV             4
K3.5 V                4
G3/G5 V               3
G9 V CN+1             3
M5                    3
F4                    3
F6 IV-V               3
A                     3
M5 V                  3
F4 V                  3
G1.5 V                3
M(6.1 +/- 0.7) V      3
G2V                   3
A8 V                  3
K0 III/IV             3
F7/F8V                3
G4 IV                 3
F6 IV                 3
G8 IV/V               3
G7 III                3
F7V                   3
M7.0 V                3
K7V                   3
K2 II                 2
G3/5V                 2
G2/3V                 2
B                     2
K7/M0 V               2
M1 III                2
G8 IV (+ G)           2
K0 IV-V               2
G2 IV-V               2
M4.0                  2
B9 V                  2
K9 V                  2
K6                    2
M4 +/- 0.5            2
G9 IV                 2
F9-F9.5               2
K6-K7                 2
K4/5V                 2
K3 VC                 2
K5.5                  2
M3.0V                 2
K7/M0                 2
F1 V                  2
K4.5                  2
M4.5+/-0.5            2
F2                    2
M1.0                  2
G3 III                2
G8 III/IV             2
G5 III                2
K7.5 V                2
F9 IV                 2
A2 V                  2
M3.5+/-0.5            2
F5V-G0V               2
G7 IV                 2
F8 IV                 2
F0                    2
K2 III/IV             2
A5V                   2
M1.5V                 2
K0/1 III              2
M0 III                2
DC                    2
F9V                   2
K1III(+M)             2
G3 IV/V               2
M0&plusmn;0.5         2
M2&plusmn;0.5         2
K7e V                 1
M2/3 V                1
G8/K0                 1
G0/2 V                1
K1 IIIb Fe-0.5        1
F8 IV/V               1
M8.5                  1
K1/2III               1
K1 IV-V               1
G1-1.5 V              1
M7.25                 1
K2III                 1
DQ                    1
L1.5                  1
M7                    1
sdBV                  1
A8 III                1
M2 III                1
M6.5+/-0.5            1
A5                    1
M1.5                  1
K4/5 V                1
M3.5 +/- 1.0          1
G9/K0                 1
M5V                   1
K1/2 V                1
G8/9 IV               1
M6                    1
M3.5 Ve               1
M1.0+/-0.5            1
F2 V                  1
K1.5+/-1              1
G3V                   1
M5.0+0.5-0.5          1
G8/G9                 1
M5.5+/-0.5            1
K1/2V                 1
K7-M0 V               1
G1/2 V                1
B9 Vne                1
A1 IV-V               1
B2 IV                 1
K0 IV/V               1
K2 VC                 1
G3/5 V                1
A8                    1
B9.5-A0               1
K6-M1                 1
K3-K4 V               1
F3                    1
M6.5                  1
A0 V                  1
F9 D                  1
M2.5 III              1
G5 III/IV             1
M0.5-1.0 V            1
G0Vvar                1
G8/K0 III             1
G0/1 V                1
Am C                  1
M0V:                  1
K1-K2                 1
G1 IV                 1
M4.5                  1
K3/4 IV               1
M4 +/- 0.5 V          1
K9 V/M0 V             1
M2.5e                 1
M9                    1
M0.5 Ve               1
Be9.5/AO              1
M3+/-1                1
M0.5+/-0.5 V          1
K1/K2 V               1
G9 IV-V               1
G2/G3 IV/V            1
M5.0                  1
M5.5/M6               1
M2V:                  1
G0 VI                 1
M3.3                  1
K1 V(P)               1
K2 IV                 1
G8V                   1
K1V                   1
G7 IV/V               1
G2/3 V                1
M4.0+/-0.5            1
A7 V                  1
G6 IV                 1
M8                    1
G7 IV-V               1
G7 V Fe-1 CH-0.5      1
F5V                   1
K1.5 V                1
M1+/-0.5              1
M9-L1                 1
K5/M0V                1
B2.5 V                1
G2/G3                 1
K5V                   1
F8/G0 IV/V            1
G6/8 V                1
G8 V+                 1
F5-F8 V               1
M7.5                  1
G6 III                1
G4 II-III             1
M2+/-0.5              1
A9/F0                 1
F9/G0                 1
G1V                   1
M4.5 Ve               1
m3 V                  1
M4.5V-M5V             1
K1 III-IV             1
F5 IV                 1
F8 V CH+0.4           1
K5e                   1
K0IIIvar              1
M2.0V                 1
B9 IV                 1
M4+/-0.5              1
M4.0&plusmn;1.0 V     1
M(3.5+/-0.5) V        1
M 4.5V                1
A5-A6                 1
F0 IV                 1
A8Ve                  1
T8.5                  1
M1&plusmn;0.5         1
Name: count, dtype: int64

In [84]:
def map_spectral_type(x):
    if pd.isna(x):
        return "Unknown"
    
    x = str(x).upper()

    if "WD" in x or "DQ" in x or "DC" in x:
        return "White Dwarf"

    if "O" in x:
        return "O"
    if "B" in x:
        return "B"
    if "A" in x:
        return "A"
    if "F" in x:
        return "F"
    if "G" in x:
        return "G"
    if "K" in x:
        return "K"
    if "M" in x:
        return "M"

    return "Other"


df["st_spectype_group"] = df["st_spectype"].apply(map_spectral_type)

In [85]:
df["st_spectype_group"].value_counts()

st_spectype_group
Unknown        3845
G               778
K               645
M               551
F               287
A                26
B                11
White Dwarf       7
Other             2
O                 1
Name: count, dtype: int64

In [86]:
def mass_limits(star):
    if star == "M":
        return 2.5, 4.0
    elif star == "K":
        return 1.0, 4.0
    elif star in ["G", "F"]:
        return 0.6, 4.0
    else:
        return None, None  # O, B, A → exclu


def compute_habitability(df):
    df = df.copy()

    # --------------------------
    # 1. Exclusion étoiles (O, B, A)
    # --------------------------
    df["star_allowed"] = ~df["st_spectype_group"].isin(["O", "B", "A"])

    # --------------------------
    # 2. Conditions de base
    # --------------------------
    rocky_ok = df["pl_type"] == "Rocheuse"
    water_ok = df["eau_possible"] == 1
    gravity_ok = df["Gravity_G_earth"] >= 0.8

    # --------------------------
    # 3. UTILISATION DIRECTE masse (corrigé)
    # --------------------------
    mass = df["pl_bmasse"]

    # --------------------------
    # 4. Limites dynamiques selon étoile
    # --------------------------
    min_mass, max_mass = zip(*df["st_spectype_group"].apply(mass_limits))
    df["min_mass"] = min_mass
    df["max_mass"] = max_mass

    df["mass_ok"] = (
        (mass >= df["min_mass"]) &
        (mass <= df["max_mass"])
    )

    # --------------------------
    # 5. Condition finale
    # --------------------------
    df["pt_habitable"] = (
        df["star_allowed"] &
        rocky_ok &
        water_ok &
        gravity_ok &
        df["mass_ok"]
    ).astype(int)

    return df