In [1]:
import pandas as pd
import numpy as np
import requests
#dfs = pd.read_csv(
#    "https://raw.githubusercontent.com/dylanmalis-collab/Exoplanet_Life/refs/heads/Machine_Learning/PSCompPars_2026.03.19_06.16.51.csv")
#dfs.head()

In [2]:
url = "https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+*+from+pscomppars&format=csv"

df = pd.read_csv(url)

df.head()

C:\Users\berna\AppData\Local\Temp\ipykernel_13096\1871774090.py:3: DtypeWarning: Columns (0: hd_name, 1: hip_name, 2: pl_orbtperstr, 3: pl_orbtper_reflink, 4: pl_occdepstr, 5: pl_occdep_reflink, 6: pl_orbtper_systemref, 7: pl_projobliqstr, 8: pl_trueobliqstr, 9: pl_trueobliq_reflink, 10: st_log_rhkstr, 11: st_log_rhk_reflink, 12: sy_icmagstr, 13: pl_cmassjstr, 14: pl_cmassj_reflink, 15: pl_cmassestr, 16: pl_cmasse_reflink, 17: pl_msinijstr, 18: pl_msinij_reflink, 19: pl_msiniestr, 20: pl_msinie_reflink, 21: pl_projobliq_reflink) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

,objectid,pl_name,pl_letter,hostid,hostname,hd_name,hip_name,tic_id,disc_pubdate,disc_year,...,cb_flag,pl_angsep,pl_angseperr1,pl_angseperr2,pl_angseplim,pl_angsepformat,pl_angsepstr,pl_angsepsymerr,pl_angsep_reflink,pl_ndispec
0,3.2390,Kepler-1167 b,b,2.136990,Kepler-1167,NaN,NaN,TIC 273875149,2016-05,2016.0,...,0,0.0213,NaN,NaN,0.0,NaN,0.0213,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
1,3.1444,Kepler-1740 b,b,2.433343,Kepler-1740,NaN,NaN,TIC 138479461,2022-02,2021.0,...,0,0.0734,NaN,NaN,0.0,NaN,0.0734,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
2,3.4135,Kepler-1581 b,b,2.442550,Kepler-1581,NaN,NaN,TIC 121215710,2016-05,2016.0,...,0,0.1390,NaN,NaN,0.0,NaN,0.1390,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
3,3.6590,Kepler-644 b,b,2.512738,Kepler-644,NaN,NaN,TIC 271669616,2016-05,2016.0,...,0,0.0352,NaN,NaN,0.0,NaN,0.0352,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
4,3.1575,Kepler-1752 b,b,2.507010,Kepler-1752,NaN,NaN,TIC 417655835,2022-02,2021.0,...,0,0.2800,NaN,NaN,0.0,NaN,0.2800,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0

In [3]:
df[df["pl_bmasse"] <= 5]

,objectid,pl_name,pl_letter,hostid,hostname,hd_name,hip_name,tic_id,disc_pubdate,disc_year,...,cb_flag,pl_angsep,pl_angseperr1,pl_angseperr2,pl_angseplim,pl_angsepformat,pl_angsepstr,pl_angsepsymerr,pl_angsep_reflink,pl_ndispec
0,3.23900,Kepler-1167 b,b,2.136990,Kepler-1167,NaN,NaN,TIC 273875149,2016-05,2016.0,...,0,0.0213,NaN,NaN,0.0,NaN,0.0213,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
2,3.41350,Kepler-1581 b,b,2.442550,Kepler-1581,NaN,NaN,TIC 121215710,2016-05,2016.0,...,0,0.1390,NaN,NaN,0.0,NaN,0.1390,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
5,3.25470,Kepler-280 c,c,2.490197,Kepler-280,NaN,NaN,TIC 159716174,2014-03,2014.0,...,0,0.0718,NaN,NaN,0.0,NaN,0.0718,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
10,3.73100,Kepler-560 b,b,2.542238,Kepler-560,NaN,NaN,TIC 239275865,2017-06,2016.0,...,0,0.8220,NaN,NaN,0.0,NaN,0.8220,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
19,3.42540,Kepler-1600 c,c,2.430178,Kepler-1600,NaN,NaN,TIC 137151626,2022-02,2021.0,...,0,0.0675,NaN,NaN,0.0,NaN,0.0675,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6132,3.12827,HD 39194 b,b,2.552480,HD 39194,HD 39194,HIP 27080,TIC 389506883,2021-10,2021.0,...,0,2.2300,NaN,NaN,0.0,NaN,2.2300,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
6140,3.15006,TOI-2267 b,b,2.574829,TOI-2267 A,NaN,NaN,TIC 459837008,2025-10,2025.0,...,0,0.9090,NaN,NaN,0.0,NaN,0.9090,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
6142,3.14549,LHS 1903 b,b,2.574401,LHS 1903,NaN,HIP 34730,TIC 318022259,2026-02,2026.0,...,0,0.7440,NaN,NaN,0.0,NaN,0.7440,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
6144,3.13072,TOI-2411 b,b,2.573046,TOI-2411,NaN,NaN,TIC 10837041,2022-02,2022.0,...,0,0.2420,NaN,NaN,0.0,NaN,0.2420,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0
6151,3.12528,LTT 3780 b,b,2.104399,LTT 3780,NaN,NaN,TIC 36724087,2020-07,2020.0,...,0,0.5440,NaN,NaN,0.0,NaN,0.5440,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0

In [4]:
df.shape

(6153, 683)

In [5]:
df.describe()

,objectid,hostid,disc_year,ra,raerr1,raerr2,rasymerr,ra_solnid,dec,decerr1,...,htm20,cb_flag,pl_angsep,pl_angseperr1,pl_angseperr2,pl_angseplim,pl_angsepformat,pl_angsepstr,pl_angsepsymerr,pl_ndispec
count,6153.000000,6153.000000,6152.000000,6153.000000,5.867000e+03,5.867000e+03,6153.000000,6153.000000,6153.000000,5.867000e+03,...,6.153000e+03,6153.000000,5808.000000,0.0,0.0,5808.0,0.0,5808.000000,0.0,6153.000000
mean,3.260726,2.440925,2016.990735,232.922360,2.513908e-07,-2.513908e-07,0.953519,4412.530519,18.030558,2.755340e-07,...,3.690117e+07,0.008776,465.337820,NaN,NaN,0.0,NaN,465.337820,NaN,0.011214
std,0.211449,0.177544,4.967697,91.672676,4.639604e-06,4.639604e-06,0.210542,246.745164,37.081209,5.033487e-06,...,1.261981e+09,0.093277,13894.238358,NaN,NaN,0.0,NaN,13894.238358,NaN,0.228150
min,3.100000,2.100330,1992.000000,0.185606,0.000000e+00,-1.630689e-04,0.000000,94.100000,-88.121111,0.000000e+00,...,-2.146451e+09,0.000000,0.003530,NaN,NaN,0.0,NaN,0.003530,NaN,0.000000
25%,3.122400,2.338290,2014.000000,173.301406,5.176236e-09,-1.094297e-08,1.000000,4400.100000,-11.166116,5.722056e-09,...,-1.049857e+09,0.000000,0.116000,NaN,NaN,0.0,NaN,0.116000,NaN,0.000000
50%,3.179900,2.512827,2016.000000,284.919421,6.912111e-09,-6.912111e-09,1.000000,4400.100000,39.120939,7.219917e-09,...,1.471824e+07,0.000000,0.283000,NaN,NaN,0.0,NaN,0.283000,NaN,0.000000
75%,3.312900,2.572954,2021.000000,293.230233,1.094297e-08,-5.176236e-09,1.000000,4400.100000,45.383869,9.683694e-09,...,1.170219e+09,0.000000,1.402500,NaN,NaN,0.0,NaN,1.402500,NaN,0.000000
max,3.999000,2.999700,2026.000000,359.974984,1.630689e-04,0.000000e+00,1.000000,5939.110000,86.860343,1.630689e-04,...,2.147324e+09,1.000000,689000.000000,NaN,NaN,0.0,NaN,689000.000000,NaN,8.000000

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6153 entries, 0 to 6152
Columns: 683 entries, objectid to pl_ndispec
dtypes: float64(497), int64(27), str(159)
memory usage: 32.1 MB

In [7]:
pd.set_option('display.max_rows', None)
df.isna().sum()

objectid                   0
pl_name                    0
pl_letter                  0
hostid                     0
hostname                   0
hd_name                 5110
hip_name                5017
tic_id                   289
disc_pubdate               0
disc_year                  1
disc_method                0
discoverymethod            0
disc_locale                0
disc_facility              0
disc_instrument            0
disc_telescope             0
disc_refname               0
ra                         0
raerr1                   286
raerr2                   286
rasymerr                   0
rastr                      0
ra_solnid                  0
ra_reflink                 0
dec                        0
decerr1                  286
decerr2                  286
decsymerr                  0
decstr                     0
dec_solnid                 0
dec_reflink                0
glon                       0
glonerr1                6153
glonerr2                6153
glonsymerr              6153
glonstr                    0
glon_solnid                0
glon_reflink               0
glat                       0
glaterr1                6153
glaterr2                6153
glatsymerr              6153
glatstr                    0
glat_solnid                0
glat_reflink               0
elon                       0
elonerr1                6153
elonerr2                6153
elonsymerr              6153
elonstr                    0
elon_solnid                0
elon_reflink               0
elat                       0
elaterr1                6153
elaterr2                6153
elatsymerr              6153
elat_solnid                0
elat_reflink               0
elatstr                    0
pl_orbper                334
pl_orbpererr1            824
pl_orbpererr2            824
pl_orbpersymerr          404
pl_orbperlim             334
pl_orbperstr             334
pl_orbperformat         6153
pl_orbper_solnid         334
pl_orbper_reflink        334
pl_orblpererr1          4383
pl_orblper              4129
pl_orblpererr2          4383
pl_orblpersymerr        4129
pl_orblperlim           4059
pl_orblperstr           4129
pl_orblperformat        6153
pl_orblper_solnid       4129
pl_orblper_reflink      4129
pl_orbsmax               316
pl_orbsmaxerr1          2253
pl_orbsmaxerr2          2253
pl_orbsmaxsymerr        1446
pl_orbsmaxlim            315
pl_orbsmaxstr            316
pl_orbsmaxformat        6153
pl_orbsmax_solnid        316
pl_orbsmax_reflink       316
pl_orbincl              1521
pl_orbinclerr1          4100
pl_orbinclerr2          4098
pl_orbinclsymerr        4034
pl_orbincllim           1521
pl_orbinclstr           1521
pl_orbinclformat        6153
pl_orbincl_solnid       1521
pl_orbincl_reflink      1521
pl_orbtper              5102
pl_orbtpererr1          5131
pl_orbtpererr2          5131
pl_orbtpersymerr        5102
pl_orbtperlim           5102
pl_orbtperstr           5102
pl_orbtperformat        6153
pl_orbtper_solnid       5102
pl_orbtper_reflink      5102
pl_orbeccen              938
pl_orbeccenerr1         4289
pl_orbeccenerr2         4289
pl_orbeccensymerr       3340
pl_orbeccenlim           938
pl_orbeccenstr           938
pl_orbeccenformat       6153
pl_orbeccen_solnid       938
pl_orbeccen_reflink      938
pl_eqt                  1563
pl_eqterr1              4344
pl_eqterr2              4344
pl_eqtsymerr            4132
pl_eqtlim               1563
pl_eqtstr               1563
pl_eqtformat            6153
pl_eqt_solnid           1563
pl_eqt_reflink          1563
pl_occdep               6118
pl_occdeperr1           6121
pl_occdeperr2           6121
pl_occdepsymerr         6118
pl_occdeplim            6118
pl_occdepstr            6118
pl_occdepformat         6153
pl_occdep_solnid        6118
pl_occdep_reflink       6118
pl_insol                1840
pl_insolerr1            2517
pl_insolerr2            2517
pl_insolsymerr          2300
pl_insollim             1840
pl_insolstr             1840
pl_insolformat          6153
pl_insol_solnid         1840
pl_insol_reflink        1840
pl_dens                  139
pl_denserr1             4741
sy_umagerr1             5426
sy_umagerr2             5428
sy_umaglim              6153
sy_umagsymerr           5419
sy_umagstr              5419
sy_umagformat           6153
sy_umag_solnid             0
sy_umag_reflink            0
sy_rmag                 2652
sy_rmagerr1             5275
sy_rmagerr2             5428
sy_rmaglim              6153
sy_rmagsymerr           2652
sy_rmagstr              2652
sy_rmagformat           6153
sy_rmag_solnid             0
sy_rmag_reflink            0
sy_imag                 2706
sy_imagerr1             5283
sy_imagerr2             5428
sy_imaglim              2706
sy_imagsymerr           2706
sy_imagstr              2706
sy_imagformat           6153
sy_imag_solnid             0
sy_imag_reflink            0
sy_zmag                 2919
sy_zmagerr1             5421
sy_zmagerr2             5428
sy_zmaglim              6153
sy_zmagsymerr           2919
sy_zmagstr              2919
sy_zmagformat           6153
sy_zmag_solnid             0
sy_zmag_reflink            0
sy_w1mag                 614
sy_w1magerr1             683
sy_w1magerr2             949
sy_w1maglim             6153
sy_w1magsymerr           614
sy_w1magstr              614
sy_w1magformat          6153
sy_w1mag_solnid            0
sy_w1mag_reflink           0
sy_w2mag                 613
sy_w2magerr1             665
sy_w2magerr2             938
sy_w2maglim             6153
sy_w2magsymerr           613
sy_w2magstr              613
sy_w2magformat          6153
sy_w2mag_solnid            0
sy_w2mag_reflink           0
sy_w3mag                 614
sy_w3magerr1            1635
sy_w3magerr2            1915
sy_w3maglim             6153
sy_w3magsymerr           614
sy_w3magstr              614
sy_w3magformat          6153
sy_w3mag_solnid            0
sy_w3mag_reflink           0
sy_w4mag                 615
sy_w4magerr1            4631
sy_w4magerr2            4631
sy_w4maglim             6153
sy_w4magsymerr           615
sy_w4magstr              615
sy_w4magformat          6153
sy_w4mag_solnid            0
sy_w4mag_reflink           0
sy_gmag                 2669
sy_gmagerr1             5286
sy_gmagerr2             5428
sy_gmaglim              6153
sy_gmagsymerr           2669
sy_gmagstr              2669
sy_gmagformat           6153
sy_gmag_solnid             0
sy_gmag_reflink            0
sy_gaiamag               339
sy_gaiamagerr1           339
sy_gaiamagerr2           339
sy_gaiamaglim           6153
sy_gaiamagsymerr         339
sy_gaiamagstr            339
sy_gaiamagformat        6153
sy_gaiamag_solnid          0
sy_gaiamag_reflink         0
sy_tmag                  288
sy_tmagerr1              297
sy_tmagerr2              297
sy_tmaglim              6153
sy_tmagsymerr            288
sy_tmagstr               288
sy_tmagformat           6153
sy_tmag_solnid             0
sy_tmag_reflink            0
sy_name                    0
pl_controv_flag            0
pl_orbtper_systemref    5351
pl_tranmid_systemref    1314
st_metratio              568
st_spectype             3845
st_spectype_solnid      3845
st_spectype_reflink     3845
sy_plxlim                390
sy_kepmag               2689
sy_kepmagerr1           6153
sy_kepmagerr2           6153
sy_kepmaglim            6153
sy_kepmagsymerr         2689
sy_kepmagstr            2689
sy_kepformat            6153
sy_kepmag_solnid           0
sy_kepmag_reflink          0
st_rotp                 5263
st_rotperr1             5440
st_rotperr2             5440
st_rotpsymerr           5263
st_rotplim              5263
st_rotpstr              5263
st_rotpformat           6153
st_rotp_solnid          5263
st_rotp_reflink         5263
pl_projobliq            5923
pl_projobliqerr1        5925
pl_projobliqerr2        5925
pl_projobliqsymerr      5923
pl_projobliqlim         5923
pl_projobliqstr         5923
pl_projobliqformat      6153
pl_denserr2             4741
pl_denssymerr           4664
pl_denslim               139
pl_densstr               139
pl_densformat           6153
pl_dens_solnid          4664
pl_dens_reflink          139
pl_trandep              1775
pl_trandeperr1          1888
pl_trandeperr2          1888
pl_trandepsymerr        4709
pl_trandeplim           1775
pl_trandepstr           1775
pl_trandepformat        6153
pl_trandep_solnid       1775
pl_trandep_reflink      1775
pl_tranmid              1264
pl_tranmiderr1          1322
pl_tranmiderr2          1322
pl_tranmidsymerr        1708
pl_tranmidlim           1264
pl_tranmidstr           1264
pl_tranmidformat        6153
pl_tranmid_solnid       1264
pl_tranmid_reflink      1264
pl_trandur              1681
pl_trandurerr1          1779
pl_trandurerr2          1779
pl_trandursymerr        2395
pl_trandurlim           1681
pl_trandurstr           1681
pl_trandurformat        6153
pl_trandur_solnid       1681
pl_trandur_reflink      1681
pl_rvamp                3666
pl_rvamperr1            3747
pl_rvamperr2            3747
pl_rvampsymerr          3666
pl_rvamplim             3666
pl_rvampstr             3666
pl_rvampformat          6153
pl_rvamp_solnid         3666
pl_rvamp_reflink        3666
pl_radj                   50
pl_radjerr1             1931
pl_radjerr2             1931
pl_radjsymerr           1623
pl_radjlim                50
pl_radjstr                50
pl_radjformat           6153
pl_radj_solnid          1549
pl_radj_reflink           50
pl_rade                   50
pl_radeerr1             1931
pl_radeerr2             1931
pl_radesymerr           1623
pl_radelim                50
pl_radestr                50
pl_radeformat           6153
pl_rade_solnid          1549
pl_rade_reflink           50
pl_ratror               1752
pl_ratrorerr1           1791
pl_ratrorerr2           1791
pl_ratrorsymerr         2495
pl_ratrorlim            1752
pl_ratrorstr            1752
pl_ratrorformat         6153
pl_ratror_solnid        1752
pl_ratror_reflink       1752
pl_ratdor               1788
pl_trueobliq            6086
pl_trueobliqerr1        6093
pl_trueobliqerr2        6093
pl_trueobliqsymerr      6086
pl_trueobliqlim         6086
pl_trueobliqstr         6086
pl_trueobliqformat      6153
pl_trueobliq_solnid     6086
pl_trueobliq_reflink    6086
st_log_rhk              5493
st_log_rhkerr1          5862
st_log_rhkerr2          5862
st_log_rhksymerr        5493
st_log_rhklim           5493
st_log_rhkstr           5493
st_log_rhkformat        6153
st_log_rhk_solnid       5493
st_log_rhk_reflink      5493
st_metn                 6153
sy_icmag                5801
sy_icmagerr1            5938
sy_icmagerr2            6135
sy_icmagsymerr          5801
sy_icmagstr             5801
sy_icmagformat          6153
sy_icmag_solnid            0
sy_icmag_reflink           0
pl_pubdate              6153
dkin_flag                  0
pl_ratdorerr1           1807
pl_ratdorerr2           1807
pl_ratdorsymerr         4307
pl_ratdorlim            1788
pl_ratdorstr            1788
pl_ratdorformat         6153
pl_ratdor_solnid        1788
pl_ratdor_reflink       1788
pl_imppar               1777
pl_impparerr1           1837
pl_impparerr2           1837
pl_impparsymerr         3622
pl_impparlim            1777
pl_impparstr            1777
pl_impparformat         6153
pl_imppar_solnid        1777
pl_imppar_reflink       1777
pl_cmassj               6069
pl_cmassjerr1           6071
pl_cmassjerr2           6071
pl_cmassjsymerr         6069
pl_cmassjlim            6069
pl_cmassjstr            6069
pl_cmassjformat         6153
pl_cmassj_solnid        6069
pl_cmassj_reflink       6069
pl_cmasse               6069
pl_cmasseerr1           6071
pl_cmasseerr2           6071
pl_cmassesymerr         6069
pl_cmasselim            6069
pl_cmassestr            6069
pl_cmasseformat         6153
pl_cmasse_solnid        6069
pl_cmasse_reflink       6069
pl_massj                3800
pl_massjerr1            4036
pl_massjerr2            4036
pl_massjsymerr          3800
pl_massjlim             3800
pl_massjstr             3800
pl_massjformat          6153
pl_massj_solnid         3800
pl_massj_reflink        3800
pl_masse                3800
pl_masseerr1            4036
pl_masseerr2            4036
pl_massesymerr          3800
pl_masselim             3800
pl_massestr             3800
pl_masseformat          6153
pl_masse_solnid         3800
pl_masse_reflink        3800
pl_bmassj                 31
pl_bmassjerr1           3164
pl_bmassjerr2           3164
pl_bmassjsymerr         2897
pl_bmassjlim              31
pl_bmassjstr              31
pl_bmassjformat         6153
pl_bmassj_solnid        6153
pl_bmassj_reflink          0
pl_bmasse                 31
pl_bmasseerr1           3164
pl_bmasseerr2           3164
pl_bmassesymerr         2897
pl_bmasselim              31
pl_bmassestr              31
pl_bmasseformat         6153
pl_bmasse_solnid        6153
pl_bmasse_reflink          0
pl_bmassprov               0
pl_msinij               4831
pl_msinijerr1           4875
pl_msinijerr2           4875
pl_msinijsymerr         4831
pl_msinijlim            4831
pl_msinijstr            4831
pl_msinijformat         6153
pl_msinij_solnid        4831
pl_msinij_reflink       4831
pl_msinie               4831
pl_msinieerr1           4875
pl_msinieerr2           4875
pl_msiniesymerr         4831
pl_msinielim            4831
pl_msiniestr            4831
pl_msinieformat         6153
pl_msinie_solnid        4831
pl_msinie_reflink       4831
st_teff                  290
st_tefferr1              490
st_tefferr2              490
st_teffsymerr            677
st_tefflim               290
st_teffstr               290
st_teffformat           6153
st_teff_solnid           290
st_teff_reflink          290
st_met                   550
st_meterr1               834
st_meterr2               834
st_metsymerr             953
st_metlim                550
st_metstr                550
st_metformat            6153
st_met_solnid            550
st_met_reflink           550
st_radv                 3768
st_radverr1             3831
st_radverr2             3875
st_radvsymerr           3768
st_radvlim              3768
st_radvstr              3768
st_radvformat           6153
st_radv_solnid          3768
st_radv_reflink         3768
st_vsin                 3878
st_vsinerr1             4572
st_vsinerr2             4586
st_vsinsymerr           3878
st_vsinlim              3878
st_vsinstr              3878
st_vsin_solnid          3878
st_vsin_reflink         3878
st_vsinformat           6153
st_lum                   308
st_lumerr1              2473
st_lumerr2              2479
st_lumsymerr             466
st_lumlim                308
st_lumstr                309
st_lumformat            6153
st_lum_solnid            466
st_lum_reflink           308
st_logg                  318
st_loggerr1              496
st_loggerr2              496
st_loggsymerr            712
st_logglim               318
st_loggstr               318
st_loggformat           6153
st_logg_solnid           318
st_logg_reflink          318
st_age                  1310
st_ageerr1              1565
st_ageerr2              1565
st_agesymerr            1710
st_agelim               1242
st_agestr               1310
st_ageformat            6153
st_age_solnid           1310
st_age_reflink          1310
st_mass                    8
st_masserr1              276
st_masserr2              277
st_masssymerr            488
st_masslim                 8
st_massstr                 8
st_massformat           6153
st_mass_solnid             8
st_mass_reflink            8
st_dens                  583
st_denserr1              713
st_denserr2              713
st_denssymerr           1932
st_denslim               583
st_densstr               583
st_densformat           6153
st_dens_solnid           583
st_dens_reflink          583
st_rad                   314
st_raderr1               472
st_raderr2               473
st_radsymerr             696
st_radlim                314
st_radstr                314
st_radformat            6153
st_rad_solnid            314
st_rad_reflink           314
systemid                   0
ttv_flag                   0
ptv_flag                   0
tran_flag                  0
rv_flag                    0
ast_flag                   0
obm_flag                   0
micro_flag                 0
etv_flag                   0
ima_flag                   0
pul_flag                   0
disc_refid                 0
sy_snum                    0
sy_pnum                    0
sy_mnum                    0
st_nphot                   0
st_nrvc                    0
st_nspec                   0
pl_nespec                  0
pl_ntranspec               0
pl_nnotes                  0
sy_pm                    302
sy_pmerr1                305
sy_pmerr2                315
sy_pmsymerr              302
sy_pmlim                6153
sy_pmstr                 302
sy_pmformat             6153
sy_pm_solnid               0
sy_pm_reflink              0
sy_pmra                  302
sy_pmraerr1              305
sy_pmraerr2              315
sy_pmrasymerr            302
sy_pmralim              6153
sy_pmrastr               302
sy_pmraformat           6153
sy_pmra_solnid             0
sy_pmra_reflink            0
sy_pmdec                 302
sy_pmdecerr1             305
sy_pmdecerr2             315
sy_pmdecsymerr           302
sy_pmdeclim             6153
sy_pmdecstr              302
sy_pmdecformat          6153
sy_pmdec_solnid            0
sy_pmdec_reflink           0
sy_plx                   390
sy_plxerr1               390
sy_plxerr2               390
sy_plxsymerr             390
sy_plxstr                390
sy_plxformat            6153
sy_plx_solnid              0
sy_plx_reflink             0
sy_dist                   27
sy_disterr1              134
sy_disterr2              134
sy_distsymerr             27
sy_distlim                27
sy_diststr                27
sy_distformat           6153
sy_dist_solnid             0
sy_dist_reflink            0
sy_bmag                  416
sy_bmagerr1              433
sy_bmagerr2              464
sy_bmaglim              6153
sy_bmagsymerr            416
sy_bmagstr               416
sy_bmagformat           6153
sy_bmag_solnid             0
sy_bmag_reflink            0
sy_vmag                  295
sy_vmagerr1              303
sy_vmagerr2              308
sy_vmaglim               295
sy_vmagsymerr            295
sy_vmagstr               295
sy_vmagformat           6153
sy_vmag_solnid             0
sy_vmag_reflink            0
sy_jmag                  303
sy_jmagerr1              322
sy_jmagerr2              322
sy_jmaglim               303
sy_jmagsymerr            303
sy_jmagstr               303
sy_jmagformat           6153
sy_jmag_solnid             0
sy_jmag_reflink            0
sy_hmag                  288
sy_hmagerr1              310
sy_hmagerr2              310
sy_hmaglim               288
sy_hmagsymerr            288
sy_hmagstr               288
sy_hmagformat           6153
sy_hmag_solnid             0
sy_hmag_reflink            0
sy_kmag                  282
sy_kmagerr1              319
sy_kmagerr2              330
sy_kmaglim               282
sy_kmagsymerr            282
sy_kmagstr               282
sy_kmagformat           6153
sy_kmag_solnid             0
sy_kmag_reflink            0
sy_umag                 5419
pl_projobliq_solnid     5923
pl_projobliq_reflink    5923
x                          0
y                          0
z                          0
htm20                      0
gaia_dr2_id              340
gaia_dr3_id              374
cb_flag                    0
pl_angsep                345
pl_angseperr1           6153
pl_angseperr2           6153
pl_angseplim             345
pl_angsepformat         6153
pl_angsepstr             345
pl_angsepsymerr         6153
pl_angsep_reflink        345
pl_ndispec                 0
dtype: int64

In [8]:
df["Masse_(10^24kg)"] = df["pl_bmasse"].apply(lambda x: x * 5.972)
df["Masse_(10^24kg)"]

C:\Users\berna\AppData\Local\Temp\ipykernel_13096\824584936.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["Masse_(10^24kg)"] = df["pl_bmasse"].apply(lambda x: x * 5.972)

0          21.320040
1          65.692000
2           2.609764
3          60.317200
4         111.676400
5          28.068400
6          35.772280
7          39.773520
8          39.773520
9         512.481805
10         21.558920
11         48.970400
12         56.315960
13        359.514400
14         80.024800
15        150.494400
16         44.551120
17         48.074600
18         32.965440
19         26.455960
20         21.558920
21         34.995920
22         42.580360
23         27.590640
24         15.945240
25          8.719120
26         22.633880
27         15.945240
28         76.441600
29         15.706360
30         59.182520
31        584.061600
32         37.623600
33         13.735600
34      41110.710520
35       2600.268520
36       4103.650603
37       1328.656532
38      17902.607998
39       4612.336247
40        131.981200
41       2600.268520
42      18506.194654
43       1803.167684
44      37958.032000
45       1879.090534
46       5105.837244
47        624.468570
48       1328.602784
49       1552.720000
50      21048.851480
51       2543.428218
52        821.868969
53       3985.802380
54         29.680840
55       4319.090742
56       3606.335369
57        665.400240
58       2087.811200
59       1613.299968
60       5371.541628
61       2486.485796
62       7402.514964
63         40.788760
64         87.191200
65      16664.447960
66       1404.494960
67       1290.694917
68       6054.877624
69       6871.052351
70      40655.166360
71       9888.557040
72       4612.115880
73       2828.022684
74       8104.764223
75       2334.639335
76       1632.267040
77      25907.730400
78       3739.219097
79       9794.096722
80      10388.143933
81         66.468360
82        107.376560
83       3397.411080
84         62.108800
85         19.707600
86        103.912800
87        284.700170
88       1043.899628
89          0.119440
90         23.290800
91         19.707600
92       6586.041040
93        958.488084
94       1677.833400
95        398.577252
96      18410.601040
97       1954.940172
98       1537.377932
99         32.846000
100     41753.656040
101      4956.760000
102        66.229480
103      4422.325720
104     14234.859200
105        50.164800
106      2482.584288
107      1176.758712
108      2960.917600
109      6396.250880
110       417.562240
111       103.315600
112        41.206800
113       428.789600
114        52.673040
115      5864.802600
116     17271.621200
117      2144.831259
118       146.146784
119      6529.397814
120     27103.450212
121        97.940800
122      2218.765216
123      4764.158829
124     13855.637200
125     11346.800000
126     13914.760000
127       816.174727
128     14424.768800
129        95.552000
130       139.744800
131      4744.754000
132      9490.356233
133       149.300000
134      5618.099280
135       907.242352
136        28.187840
137        22.753320
138       316.516000
139      4896.860840
140              NaN
141        23.888000
142      9110.741984
143        23.888000
144        53.748000
145     23855.070392
146     30369.292160
147        33.920960
148     32848.020994
149        24.485200
150       662.892000
151      3718.185116
152      3190.541000
153     11957.138400
154        33.741800
155     28547.134630
156     11198.676484
157        48.373200
158        24.724080
159       271.128800
160       256.796000
161     14614.678400
162       400.124000
163     16779.033918
164     17120.602644
165      1981.515572
166      1637.976272
167      1136.901584
168      3416.402040
169         2.627680
170        38.041640
171      2125.850451
172      7041.879620
173         3.911660
174     11388.484560
175       728.584000
176       137.953200
177     17079.920000
178      1174.906102
179        48.970400
180     12479.353968
181     15184.569973
182       716.640000
183       816.139492
184      7592.203600
185       449.828956
186     19682.998827
187      7610.955680
188     24295.311957
189       986.932720
190       512.457320
191         7.405280
192      6073.524000
193        63.303200
194     26192.415640
195     17290.791320
196       664.324936
197      9095.557414
198        15.168880
199        43.595600
200        11.346800
201      8920.376400
202       948.950800
203        10.988480
204     11388.006800
205     18790.300800
206      7166.400000
207     21447.243600
208        40.609600
209       175.576800
210       238.335951
211     12906.949168
212      1693.014224
213       668.093612
214     20902.000000
215      1176.782600
216     54093.002440
217     17423.668320
218       219.422030
219      5788.229616
220      3348.197679
221     13229.054960
222        97.642200
223      6795.095063
224        12.720360
225        53.509120
226       816.133520
227       645.334320
228       632.034676
229       633.032000
230        62.706000
231       241.047836
232       692.752000
233       102.491464
234        28.068400
235     11103.716793
236      2410.478360
237       474.475400
238      1119.821664
239       209.020000
240       106.898800
241      2866.560000
242      6588.205297
243      7212.670737
244       214.992000
245        50.523120
246     17614.189453
247      4650.097800
248      1134.680000
249      5314.482800
250      7971.939192
251      1898.080760
252      4612.313129
253      1015.240000
254       178.562800
255        50.224520
256       360.332564
257         2.329080
258        24.365760
259        50.403680
260        52.255000
261     12868.923052
262       716.042800
263        50.762000
264        33.264040
265        21.976960
266       713.648028
267       118.842800
268         2.974056
269     11388.604000
270     26573.130640
271        52.255000
272      2087.878371
273        57.331200
274        23.350520
275      1558.692000
276       806.220000
277       212.006000
278     17671.043306
279       992.653896
280      6073.858432
281       214.992000
282      1498.972000
283     19929.161200
284        39.773520
285        33.980680
286        88.982800
287         8.420520
288        97.343600
289        16.721600
290       289.642000
291       569.424228
292     11198.676484
293        18.214600
294        13.735600
295       605.487762
296        74.650000
297        25.679600
298      1786.093995
299       383.999600
300        50.762000
301        11.824560
302        88.385600
303      1898.021040
304      1062.896560
305       105.107200
306      4384.403520
307        88.982800
308        80.622000
309       394.152000
310        14.093920
311        12.839800
312         6.449760
313      7971.939192
314      2353.620142
315       569.400340
316        13.437000
317        15.945240
318      2592.765323
319        33.741800
320        29.501680
321        63.303200
322        43.715040
323      1936.122400
324     19169.522800
325      1195.713840
326       474.176800
327       170.202000
328        43.416440
329        21.081160
330        11.167640
331        80.622000
332      1080.932000
333      2258.610400
334      2600.268520
335        36.548640
336        46.283000
337        57.570080
338        31.711320
339        27.829520
340        14.631400
341       131.981200
342      2353.620142
343      1480.502993
344     19360.326715
345      1442.541378
346        75.247200
347        19.886760
348         3.822080
349        28.068400
350       143.328000
351      1613.368646
352      3972.683031
353      2032.844494
354      9489.508000
355        33.443200
356        11.824560
357        37.086120
358        36.548640
359        45.148320
360        10.809320
361       115.856800
362        40.370720
363        18.214600
364       186.923600
365        11.944000
366        47.776000
367       149.300000
368        37.384720
369        36.309760
370        13.556440
371        17.318800
372      1222.364009
373      2562.409026
374      7763.600000
375      1641.762520
376       334.432000
377        66.289200
378     24968.513960
379        14.631400
380        22.693600
381      9736.748800
382      2144.724360
383        32.189080
384       776.360000
385        33.443200
386        16.124400
387      4270.517480
388     20878.112000
389        75.247200
390     31584.063846
391       251.421200
392        38.161080
393       364.292000
394        30.696080
395        17.079920
396       149.300000
397        17.438240
398        34.458440
399     11919.445047
400       525.765735
401      6320.608931
402      1499.483800
403      3416.402040
404      1195.790879
405        45.446920
406        99.135200
407        62.706000
408        40.072120
409        34.458440
410        55.360440
411     46500.978000
412       873.106400
413      2030.838320
414      3606.353444
415      9850.989770
416       326.012598
417         8.719120
418        18.453480
419        40.609600
420         5.338968
421        29.023920
422        16.303560
423         1.534804
424        31.711320
425        20.065920
426        23.051920
427      6035.896817
428        60.317200
429        13.914760
430      1537.445416
431     11944.000000
432     17916.000000
433     18980.807600
434        45.984400
435        40.370720
436        24.126880
437        63.900400
438        23.469960
439        13.735600
440      1486.197235
441       975.613511
442      1822.157530
443      2695.274679
444      3226.737292
445      1098.988760
446       968.021188
447        42.665808
448        15.348040
449        25.261560
450        17.677120
451        18.035440
452        14.989720
453        45.685800
454         9.853800
455        41.445680
456        29.979440
457        14.452240
458     12529.168299
459        29.979440
460        18.632640
461        22.574160
462        12.839800
463        25.858760
464       655.725600
465        44.252520
466        44.849720
467        23.469960
468         6.449760
469         2.729204
470        27.112880
471        11.824560
472        17.438240
473       182.743200
474        23.051920
475        29.262800
476        17.259080
477        26.874000
478        16.661880
479        27.590640
480        83.010800
481        34.995920
482        37.922200
483        25.022680
484         2.848644
485     43465.831547
486        66.289200
487         8.420520
488         6.509480
489        50.762000
490        11.466240
491        18.453480
492        15.348040
493       126.009200
494       314.724400
495        35.772280
496       564.354000
497        14.810560
498        17.318800
499        13.198120
500      1385.598955
501        17.079920
502        90.774400
503        19.110400
504      1527.955012
505      5694.213740
506        26.635120
507        22.156120
508        20.065920
509         6.199832
510        19.229840
511        32.726560
512       307.489083
513        68.080800
514        42.281760
515        50.463400
516        10.212120
517     28528.010836
518        45.148320
519              NaN
520       318.904800
521        44.252520
522       142.133600
523      1934.928000
524        20.483960
525        19.050680
526        11.466240
527     14478.487469
528        23.231080
529        51.657800
530              NaN
531              NaN
532        10.809320
533        33.980680
534        15.706360
535        25.022680
536        26.157360
537        16.303560
538        24.604640
539       621.088000
540       142.730800
541        17.079920
542        14.989720
543     21448.205087
544        29.023920
545        24.604640
546        98.538000
547              NaN
548         9.256600
549        16.482720
550      5447.464478
551        17.677120
552       910.861384
553     47318.916178
554        37.026400
555        20.663120
556        24.588283
557        50.224520
558        27.590640
559        39.773520
560         4.473028
561        29.023920
562        19.886760
563      1278.008000
564        22.156120
565        14.273080
566        40.370720
567        14.093920
568        37.922200
569        16.661880
570        53.807720
571        47.776000
572        31.950200
573        11.466240
574              NaN
575              NaN
576         4.138596
577        18.811800
578        57.570080
579       100.926800
580        34.458440
581        43.416440
582        43.117840
583        24.365760
584         5.398688
585        28.665600
586         3.380152
587        14.810560
588        41.804000
589         6.031720
590        11.167640
591        13.914760
592        53.807720
593         3.822080
594         3.583200
595        18.035440
596        10.809320
597        22.574160
598        85.399600
599        18.453480
600        12.362040
601        42.580360
602        27.590640
603              NaN
604        47.178800
605      1465.188396
606        24.843520
607        14.452240
608         1.618412
609        45.446920
610        31.711320
611         1.881180
612        33.443200
613         8.181640
614        30.218320
615         9.853800
616        34.995920
617        19.647880
618         6.031720
619         5.016480
620        20.245080
621        49.866200
622        20.902000
623        79.427600
624         9.017720
625         2.496296
626        12.362040
627       266.351200
628        41.744280
629        19.886760
630        51.060600
631        13.556440
632        16.124400
633        18.811800
634        21.738080
635        22.156120
636        58.525600
637        17.079920
638        32.189080
639         7.405280
640        12.839800
641        19.886760
642        12.182880
643        18.035440
644         5.595764
645        12.362040
646        19.886760
647         8.420520
648      2262.512266
649      1024.958473
650        69.334920
651       262.768000
652       808.582404
653       117.051200
654        40.072120
655        75.844400
656         3.822080
657        15.348040
658         6.210880
659        19.229840
660        13.914760
661        16.482720
662        17.856280
663        36.309760
664        15.348040
665        42.878960
666        24.604640
667        20.902000
668         6.449760
669        40.609600
670        43.595600
671        87.788400
672        25.261560
673        32.427960
674        33.980680
675        10.809320
676       173.188000
677        48.373200
678        72.261200
679      2752.076760
680      8958.000000
681        30.934960
682        61.511600
683        31.472440
684        25.500440
685       161.244000
686      1803.176722
687        25.679600
688        96.149200
689        28.307280
690        22.156120
691        18.214600
692        44.849720
693        51.060600
694        19.886760
695      2638.332256
696       312.613901
697       111.986204
698     24105.625652
699        19.647880
700        30.934960
701        47.477400
702        33.741800
703       128.995200
704        22.574160
705        34.219560
706        16.124400
707        31.472440
708        85.399600
709        52.553600
710        56.017360
711              NaN
712              NaN
713        36.548640
714        17.259080
715       150.494400
716        33.443200
717        16.900760
718        48.373200
719      1129.311172
720        74.052800
721        16.303560
722       389.104606
723     13723.055113
724       340.404000
725      2106.859084
726              NaN
727        16.124400
728         3.672780
729        59.720000
730        37.623600
731        60.914400
732        48.970400
733      2353.608346
734        23.888000
735        34.637600
736      2866.087582
737       229.922000
738        44.790000
739      1860.119145
740        19.886760
741        18.453480
742        48.492640
743        45.208040
744         1.732661
745        50.164800
746       291.433600
747       228.130400
748        74.052800
749      1860.109822
750        62.108800
751              NaN
752        25.500440
753        55.539600
754        34.219560
755      2054.368000
756     23888.000000
757       550.439240
758        13.556440
759        54.345200
760       744.043929
761        65.692000
762       876.570160
763        19.647880
764        36.309760
765        27.829520
766       269.934400
767        69.872400
768        47.357960
769        58.824200
770        29.740560
771     17802.010222
772        93.760400
773        15.706360
774        52.852200
775        31.651600
776        17.916000
777        17.856280
778        13.198120
779       109.287600
780        47.477400
781        91.968800
782     12324.176604
783       100.329600
784        48.373200
785      1715.856407
786      1387.497036
787        34.458440
788        27.590640
789        48.373200
790        49.269000
791         9.256600
792        32.726560
793        17.259080
794        26.874000
795       143.925200
796        31.651600
797        57.271480
798        36.070880
799        57.868680
800        38.698560
801        38.161080
802        10.510720
803        49.567600
804        19.349280
805        95.552000
806       149.897200
807       126.009200
808        36.011160
809       381.512321
810       227.533200
811      2799.655089
812        24.604640
813      1188.192600
814      6643.249363
815              NaN
816      2048.396000
817        21.976960
818       246.749262
819     10116.770451
820        25.261560
821        94.357600
822        37.922200
823        47.178800
824        10.212120
825        19.886760
826        51.777240
827        43.416440
828        39.892960
829       220.964000
830      1620.890380
831      3682.276674
832        20.304800
833      1594.344840
834      8199.708883
835        21.797800
836      9794.047632
837      1142.644618
838        49.567600
839       400.476348
840       373.906920
841      1746.234299
842       721.270689
843      1976.732000
844      2277.685496
845       569.424228
846      6206.724085
847      4479.448142
848       105.704400
849        45.327480
850       123.620400
851        40.072120
852        33.443200
853       154.674800
854       200.659200
855        14.093920
856      5810.756000
857        11.944000
858        93.640960
859              NaN
860       140.457976
861      3321.641330
862      3929.007480
863        31.173840
864     43595.600000
865     17916.000000
866       716.640000
867        27.829520
868     22776.854959
869     24466.138369
870              NaN
871        43.845446
872      7592.284986
873      1767.113188
874        90.774400
875      1687.385338
876      6889.998625
877       378.027600
878       683.256520
879        24.485200
880        35.234800
881        29.979440
882      2013.863686
883     10970.906793
884      1765.144040
885       892.037640
886        65.094800
887        17.677120
888        23.231080
889        26.276800
890      1708.272684
891        26.993440
892        40.012400
893      5656.280665
894       812.378565
895      4270.660305
896      1176.758712
897     25054.540455
898       197.399410
899      1328.649873
900       918.671088
901      1750.030461
902        67.423880
903      1385.592010
904     35626.797299
905       205.436800
906        33.443200
907      5732.175165
908      1765.206259
909      5428.309120
910      5352.345280
911       495.399078
912       157.063600
913       470.593600
914        68.678000
915        71.664000
916        88.385600
917        33.980680
918      1157.823460
919      4498.451401
920      2961.005986
921      6035.896817
922        12.541200
923        40.908200
924     10268.616912
925      1973.994096
926        44.312240
927        25.261560
928      4137.816057
929     16892.834095
930      8541.005100
931     13912.371200
932      4327.442584
933       183.937600
934        66.408640
935       182.214840
936       664.324936
937     14994.762848
938        18.334040
939       351.143181
940       210.811600
941        37.026400
942      1374.210470
943        88.982800
944      9148.703409
945        33.443200
946       141.297520
947        21.200600
948       340.404000
949      7166.400000
950        18.632640
951        14.273080

In [9]:
df["Gravity_G_earth"] = df["pl_bmasse"] * df["pl_rade"]
df["Gravity_G_earth"]

C:\Users\berna\AppData\Local\Temp\ipykernel_13096\3916410666.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["Gravity_G_earth"] = df["pl_bmasse"] * df["pl_rade"]

0            6.104700
1           36.555356
2            0.349600
3           31.815000
4           84.909307
5            9.447000
6           13.896800
7           16.450200
8           16.450200
9          952.536510
10           6.209200
11          22.878000
12          28.572900
13         543.606000
14          49.848000
15          95.079600
16          19.694400
17          22.218000
18          12.199200
19           8.603348
20           9.855300
21          13.419400
22          18.324100
23           9.193800
24           3.844800
25           1.635200
26           5.385590
27           3.844800
28          46.464000
29           3.760900
30          30.919200
31         175.062000
32          15.057000
33           3.036000
34       77925.861200
35        5921.576000
36        9281.207741
37        3114.734000
38       37471.969185
39       10271.947770
40         110.500000
41        5921.576000
42       38735.337103
43        4166.730416
44      213561.600000
45        4342.171696
46       11285.507640
47        1307.075875
48        3114.608000
49        3614.000000
50       43704.916000
51        5792.133920
52        1967.971577
53        8943.361000
54           8.299900
55        9618.872550
56        8091.911242
57        1448.460000
58        4789.520000
59        3755.001600
60       11872.797972
61        5662.459280
62       16113.981000
63          17.143300
64          57.232000
65       34880.375000
66        3292.520000
67        3025.741600
68       13281.797870
69       14957.079800
70       82372.323000
71       21194.496000
72        8827.274700
73        6440.239200
74       17506.942143
75        5355.753330
76        3799.148000
77       53359.860000
78        8390.076340
79       20992.035840
80       22265.278355
81          33.390000
82          79.651400
83        7680.015000
84          33.384000
85           3.329700
86          64.519200
87         375.182575
88        1996.549109
89           0.006760
90           7.020000
91           5.379000
92       16189.397600
93        1726.947720
94        3029.483850
95         640.713600
96       39046.998120
97        4990.138644
98        2568.131656
99          12.155000
100      82338.321576
101      10956.000000
102         36.929700
103      11870.375300
104      30033.360000
105         23.772000
106       4123.783680
107       2760.811506
108       6693.300000
109      14030.624000
110        446.788800
111         94.977000
112         13.800000
113        718.000000
114         22.596840
115      12864.855000
116      36151.250000
117       4549.028357
118         97.936944
119      15073.888936
120      55822.578300
121        114.472000
122       4905.655712
123      10610.065711
124      29233.260000
125      24320.000000
126      29358.000000
127       1761.684174
128      29516.188000
129         66.240000
130        121.212000
131       8580.600000
132      20499.932252
133        134.500000
134      12293.590320
135       2637.717508
136          9.520240
137          7.543800
138        151.580000
139      10823.604000
140               NaN
141         36.000000
142      19679.934961
143          2.160000
144         11.790000
145      49132.177800
146      62040.416000
147         12.780000
148      67104.128621
149          4.510000
150        320.790000
151       8342.880200
152       7212.375000
153               NaN
154         12.656000
155      58317.991040
156      24002.521600
157          2.997000
158          6.292800
159         83.536000
160        104.490000
161               NaN
162        291.249000
163      43460.338889
164      30559.527482
165       4760.680748
166       2382.635612
167       3352.260548
168       7665.738000
169          0.333960
170         15.351700
171       5438.456205
172      15328.940900
173          0.567885
174      26719.173525
175        524.600000
176        203.280000
177      35750.000000
178       2773.974553
179         17.794000
180      26538.478800
181      32037.103426
182        733.200000
183       1470.609021
184      16526.900000
185        770.027029
186               NaN
187      21283.148000
188      50038.904398
189       2333.471200
190       1039.159100
191          1.326800
192      13322.700000
193         34.450000
194      21490.763000
195      11581.240000
196       1446.119252
197               NaN
198          3.556000
199         22.776000
200          3.420000
201       7916.610000
202        317.800000
203          2.197496
204      24408.320000
205      39330.000000
206      15600.000000
207      50921.042700
208         17.000000
209        174.048000
210        107.754030
211       8428.851600
212       4531.336128
213       1557.468062
214      43400.000000
215       2252.281500
216     107787.463000
217      36469.500000
218        202.079900
219        794.766960
220       7568.765684
221      28132.786000
222         68.506500
223      14791.734062
224          2.683800
225         26.342400
226       1761.547400
227       1320.493200
228        894.214767
229       1194.620000
230         17.955000
231        329.362080
232       1542.800000
233         73.968220
234          9.447000
235      23798.991116
236       4887.959300
237        870.930900
238       2446.469064
239        229.600000
240         94.870000
241       6528.000000
242      14451.689449
243      15700.723306
244         63.000000
245         22.588200
246      49987.512351
247      11430.582000
248       1998.800000
249      10474.123000
250      17353.518000
251       4386.054000
252      10271.896286
253       2414.000000
254         89.999000
255         23.800300
256         44.046010
257          1.248000
258          7.548000
259         23.952720
260         25.375000
261      27366.932813
262        145.079000
263         13.260000
264         22.391400
265          6.403200
266       1613.236500
267         93.729000
268          0.413340
269      17271.699000
270      54730.326000
271         25.375000
272       4702.271282
273         42.816000
274         20.918500
275       3627.900000
276        283.500000
277         98.690000
278      36987.280865
279       2360.295600
280      13323.433600
281         57.960000
282       3488.900000
283      41380.040000
284         16.450200
285         12.802500
286         59.004000
287          1.565100
288         45.640000
289          4.480000
290        139.195000
291       1111.517619
292      21859.846500
293          4.758000
294          3.036000
295       1134.182603
296         32.750000
297         10.191000
298       4495.522321
299        225.693000
300         24.225000
301          2.415600
302         58.460000
303       3883.760400
304       2573.590800
305         14.731200
306       7743.919680
307         41.720000
308         27.000000
309        215.160000
310          3.162400
311          2.730500
312          1.112400
313      17353.518000
314       6096.246631
315       1143.186550
316          2.931750
317          3.844800
318       6973.578952
319         12.656000
320         10.225800
321         34.450000
322         19.105200
323       4373.458000
324      37780.523000
325       2154.367200
326        343.008000
327         65.550000
328         18.902000
329          6.001000
330          2.244000
331         50.490000
332       1773.800000
333       4833.396000
334       8050.730900
335         14.382000
336         20.925000
337         29.594800
338         11.469600
339          9.320000
340          3.356500
341        143.871000
342       5389.435428
343       5196.344867
344      45058.910813
345       2555.920514
346         45.360000
347          5.461200
348          0.569600
349          9.447000
350         37.200000
351       3664.089329
352      11878.094092
353       3964.302401
354      20498.100000
355         12.488000
356          2.415600
357         14.717700
358         14.382000
359         20.109600
360          2.153900
361         90.016000
362         16.832400
363          4.758000
364        192.182000
365          4.980000
366         33.520000
367         83.250000
368         14.898800
369         14.227200
370          2.973700
371          8.323000
372       2409.000685
373       6194.573190
374      16900.000000
375       3821.249000
376        484.400000
377         36.963000
378      15134.966600
379          3.356500
380          6.726000
381      20869.120000
382       4920.081000
383         11.750200
384       1846.000000
385         12.488000
386          3.915000
387       9510.697000
388      43350.400000
389         45.360000
390      64522.032640
391        275.334000
392         15.399900
393        150.060000
394         10.896800
395          4.290000
396        134.500000
397          4.438400
398         13.097900
399      25347.781664
400        994.716069
401      14200.385715
402       3124.005769
403       7438.054140
404       3658.389239
405         20.318700
406         48.140000
407         37.800000
408         16.640800
409         13.097900
410         27.810000
411      87278.878500
412       2081.888000
413       4840.754100
414       8799.514481
415      21113.976734
416        136.475468
417          1.635200
418          4.851300
419         17.000000
420          0.873438
421          9.963000
422          3.985800
423          0.177330
424         11.469600
425          5.544000
426          6.909400
427      13240.162140
428         31.815000
429          3.098900
430       3944.711903
431      26000.000000
432      39000.000000
433      41681.910699
434         19.119100
435         16.832400
436          7.433600
437         34.882000
438          7.113300
439          3.036000
440       4435.275928
441       2636.861797
442       4548.672101
443       6323.537734
444       8176.067099
445       2143.166284
446       2598.172434
447         22.361684
448          3.623700
449          7.994700
450          4.528800
451          4.681000
452          3.488900
453         20.502000
454          1.914000
455         17.558200
456         10.491800
457          3.291200
458               NaN
459         10.491800
460          4.929600
461          6.690600
462          2.730500
463          8.313600
464        229.482000
465         19.488300
466         19.901500
467          7.113300
468          1.112400
469          0.370170
470          8.943800
471          2.415600
472          4.438400
473         74.664000
474          6.909400
475         10.094000
476          4.363900
477          8.820000
478          4.129200
479          9.193800
480         63.523000
481         13.419400
482         15.240000
483          7.877200
484          0.391140
485      87339.246244
486         35.409000
487          1.565100
488          1.373400
489         24.225000
490          2.323200
491          4.851300
492          3.623700
493        102.757000
494        440.045000
495         13.896800
496        179.550000
497          3.422400
498         12.470000
499          2.850900
500       3094.792805
501          4.290000
502         35.112000
503          6.880000
504       4189.940477
505      12490.656395
506          8.697000
507          6.492500
508          5.544000
509          1.619514
510          5.184200
511         12.056000
512        424.264910
513         38.532000
514         18.124800
515         23.998000
516          2.000700
517      58278.923678
518         20.109600
519               NaN
520        449.094000
521         19.488300
522        124.474000
523        913.680000
524          5.728100
525          5.104000
526          2.323200
527      30547.378116
528          7.002000
529         24.912000
530               NaN
531               NaN
532          2.153900
533         12.802500
534          3.760900
535          7.877200
536          8.453400
537          3.985800
538          7.663200
539       1300.000000
540        125.236000
541          4.290000
542          3.488900
543      44534.116389
544          9.963000
545          7.663200
546         69.465000
547               NaN
548          1.767000
549          4.057200
550      12040.611371
551          4.528800
552        364.527580
553      95081.546238
554         19.530000
555          5.812800
556          6.258237
557         22.984530
558          9.193800
559         16.450200
560          0.696570
561          9.963000
562          5.461200
563       2996.000000
564          6.492500
565          3.226500
566         16.832400
567          3.162400
568         15.240000
569          4.129200
570         26.579500
571         22.000000
572         11.609500
573          2.323200
574               NaN
575               NaN
576          0.630630
577          5.008500
578         29.594800
579         31.265000
580         13.097900
581         18.902000
582         18.699800
583          7.548000
584          0.885920
585         14.688000
586          0.486760
587          3.422400
588         17.290000
589          1.020100
590          2.244000
591          3.098900
592         26.579500
593          0.569600
594          0.762000
595          4.681000
596          2.153900
597          6.690600
598         55.484000
599          4.851300
600          2.566800
601         18.324100
602          9.193800
603               NaN
604         21.567000
605        721.308420
606          7.779200
607          3.291200
608          0.189700
609         20.318700
610         11.469600
611          0.229950
612         12.488000
613          1.507000
614         10.626000
615          1.914000
616         13.419400
617          5.362700
618          1.020100
619          0.806400
620          5.627400
621         23.547000
622          5.915000
623         49.343000
624          1.706300
625          0.330220
626          2.566800
627         67.792000
628         17.754600
629          5.461200
630         24.453000
631          2.973700
632          3.915000
633          5.008500
634          6.297200
635          6.492500
636         30.380000
637          4.290000
638         11.750200
639          1.326800
640          2.730500
641          5.461200
642          2.509200
643          4.681000
644          0.927630
645          2.566800
646          5.461200
647          1.565100
648       5223.277794
649       2333.530025
650         39.822300
651        194.920000
652       1036.554305
653         91.336000
654         16.640800
655         45.847000
656          0.569600
657          3.623700
658          1.060800
659          5.184200
660          3.098900
661          4.057200
662          4.604600
663         14.227200
664          3.623700
665         18.524400
666          7.663200
667          5.915000
668          1.112400
669         17.000000
670          8.395000
671         17.199000
672          7.994700
673         11.891700
674         12.802500
675          2.153900
676        170.230000
677         22.437000
678         42.471000
679       4857.148200
680      19350.000000
681         11.033400
682         32.857000
683         11.330500
684          8.113000
685        111.565325
686       6024.282991
687          4.687000
688         66.976000
689          9.574800
690          6.492500
691          4.758000
692         19.901500
693         24.453000
694          5.461200
695       7923.125589
696        769.233249
697        150.015008
698      49648.224300
699          5.362700
700         11.033400
701         21.783000
702         12.656000
703         65.448000
704          4.725000
705         12.949800
706         10.827000
707         11.330500
708         55.341000
709         17.336000
710         28.327600
711               NaN
712               NaN
713         14.382000
714          4.363900
715        136.332000
716         12.488000
717          4.216700
718         22.437000
719       2526.578461
720         31.210800
721          3.658200
722        985.930864
723      29183.322159
724         79.230000
725       4634.569754
726               NaN
727          3.915000
728          0.541200
729         31.400000
730         15.057000
731         32.334000
732         22.878000
733       6352.422917
734          7.316000
735         18.038000
736       8069.136067
737        163.347265
738          7.612500
739       4364.131676
740          5.461200
741          4.851300
742         22.534102
743         13.421610
744          0.204542
745         21.898800
746        150.792000
747        263.962000
748         35.340000
749       4074.325897
750         35.724000
751               NaN
752          8.113000
753         27.249000
754         12.949800
755               NaN
756      49200.000000
757       1271.024300
758          2.973700
759         22.304996
760       1731.783424
761         36.410000
762        377.224600
763          5.362700
764         14.227200
765          9.320000
766        102.604000
767         21.294000
768         16.177200
769         30.633500
770         10.358400
771      37261.407866
772         64.213000
773          5.575600
774         25.842000
775          4.346000
776          4.830000
777          4.604600
778          2.850900
779         23.607000
780         21.783000
781         62.216000
782      26208.480052
783         71.568000
784         22.437000
785       3146.457185
786       3018.822001
787         13.097900
788          9.193800
789          7.695000
790          6.930000
791          1.767000
792         12.056000
793          4.363900
794          8.820000
795         46.513000
796          6.519000
797         29.345400
798         14.073200
799         29.845200
800         15.746400
801         15.399900
802          2.076800
803         31.775565
804          4.762800
805         99.264000
806        298.439000
807        102.765440
808         14.049900
809        597.310817
810        262.890000
811               NaN
812          7.663200
813       2140.939519
814       3237.082325
815               NaN
816       3978.800000
817          6.403200
818         85.114447
819      26792.669065
820          7.994700
821         64.780000
822         15.240000
823         21.567000
824          2.000700
825          5.461200
826         25.004280
827         18.902000
828         16.526320
829        136.275362
830       4511.731545
831      10781.720901
832          5.644000
833       5956.100700
834      17037.000053
835          6.325450
836      20991.930626
837       3620.184383
838         17.596000
839        720.817191
840        698.289330
841       6063.471112
842       1001.790879
843       3736.990000
844       5225.099011
845       1132.892957
846      15144.427554
847      11182.076947
848         47.736900
849         20.240674
850         99.567000
851         16.640800
852         12.488000
853        142.450000
854        215.040000
855          3.162400
856      12746.300000
857          2.397612
858         55.350400
859               NaN
860        161.868316
861       7508.733750
862       8815.924353
863         11.170800
864      87600.000000
865      55941.000000
866       1632.000000
867          9.320000
868      47292.866962
869      47849.727503
870               NaN
871         12.541682
872      16527.077164
873       3585.396020
874         66.120000
875       3860.684385
876      21208.468362
877        588.690000
878       1510.212000
879         14.309000
880         21.948000
881         10.491800
882       4653.603294
883      23514.334720
884       4078.866000
885       2135.991000
886         37.823000
887          4.528800
888          7.002000
889         12.931600
890       3975.813021
891          9.853600
892         17.688000
893      12502.160880
894       1945.246732
895       9511.015079
896       2778.348600
897      52198.315773
898        340.863108
899       3591.032740
900       1646.684852
901       3757.670563
902         26.587950
903       3027.155098
904      72184.234313
905        183.446716
906          8.198400
907       6526.924166
908       4008.917801

In [10]:
df["Score_roch"] = df["pl_dens"] * (1/df["pl_rade"])**3
df["Score_roch"]

C:\Users\berna\AppData\Local\Temp\ipykernel_13096\3466090409.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["Score_roch"] = df["pl_dens"] * (1/df["pl_rade"])**3

0       7.839669e-01
1       4.495820e-02
2       9.160156e+00
3       5.694929e-02
4       1.175037e-02
5       3.915966e-01
6       2.114170e-01
7       1.612558e-01
8       1.612558e-01
9       2.522610e-04
10      7.664419e-01
11      9.531423e-02
12      6.686288e-02
13      6.097939e-04
14      2.777840e-02
15      4.393914e-02
16      1.211973e-01
17      9.988311e-02
18      2.603332e-01
19      4.532593e-01
20      4.423383e-02
21      2.231662e-01
22      1.360857e-01
23      4.085984e-01
24      1.644349e+00
25      4.064265e+00
26      2.517246e+00
27      1.644349e+00
28      3.073247e-02
29      1.689347e+00
30      5.893717e-02
31      1.633731e+01
32      1.860544e-01
33      2.391338e+00
34      1.819972e-02
35      3.780627e-04
36      5.803290e-04
37      1.625364e-04
38      4.316160e-03
39      7.650989e-04
40      7.776000e-03
41      3.780627e-04
42      4.464640e-03
43      2.401000e-04
44      2.427962e-05
45      2.503737e-04
46      8.869689e-04
47      1.505280e-04
48      1.625364e-04
49      1.980921e-04
50      5.349770e-03
51      3.697143e-04
52      8.857102e-05
53      6.317266e-04
54      1.202371e+00
55      7.183429e-04
56      5.735413e-04
57      1.269914e-04
58      2.905085e-04
59      2.059116e-04
60      9.347956e-04
61      3.617634e-04
62      1.411015e-03
63      1.498743e-01
64      2.207971e-02
65      4.019200e-03
66      1.716472e-04
67      1.577988e-04
68      1.103158e-03
69      1.310878e-03
70      1.191040e-02
71      2.069473e-03
72      1.888471e-03
73      4.094685e-04
74      1.616443e-03
75      3.247318e-04
76      2.081457e-04
77      6.878514e-03
78      5.943218e-04
79      2.050400e-03
80      2.174377e-03
81      7.814815e-02
82      1.311275e-02
83      5.161815e-04
84      5.230353e-02
85      6.717004e+00
86      2.412603e-02
87      1.101666e-03
88      4.362046e-04
89      7.380653e+01
90      6.292867e-01
91      9.675005e-01
92      6.954157e-04
93      6.421747e-04
94      9.331835e-04
95      4.690665e-04
96      4.104380e-03
97      1.185639e-04
98      1.410129e-03
99      2.594067e-01
100     1.438752e-02
101     8.608815e-04
102     4.468392e-02
103     2.403447e-04
104     3.274384e-03
105     9.000588e-02
106     2.397071e-03
107     1.454295e-04
108     4.511507e-04
109     1.165433e-03
110     6.132215e-03
111     3.565619e-03
112     6.125000e-01
113     3.950000e-04
114     1.711472e-01
115     1.067572e-03
116     4.167680e-03
117     4.640617e-04
118     2.979903e-02
119     8.776309e-04
120     7.200945e-03
121     7.939579e-04
122     3.866103e-04
123     7.906022e-04
124     3.184401e-03
125     2.374649e-03
126     3.199399e-03
127     1.811497e-04
128     4.000454e-03
129     1.747514e-02
130     6.655067e-03
131     2.778413e-03
132     1.895943e-03
133     5.663981e-03
134     1.039586e-03
135     3.285899e-05
136     3.850963e-01
137     2.086986e-01
138     4.274663e-01
139     8.521858e-04
140              NaN
141     4.115226e-05
142     1.821410e-03
143              NaN
144              NaN
145     6.341130e-03
146     8.480886e-03
147     2.405487e-01
148     9.141734e-03
149     6.536439e+00
150     4.888645e-02
151     5.901657e-04
152     4.836661e-04
153              NaN
154     2.455642e-01
155     7.985250e-03
156     2.341270e-03
157     1.735337e+04
158     1.623096e+00
159     3.210528e+00
160     1.149913e+00
161              NaN
162     3.895660e-02
163     6.079175e-04
164     6.018460e-03
165     2.065170e-04
166     3.661017e-03
167     3.479762e-05
168     5.444486e-04
169     1.264736e+01
170     1.786031e-01
171     1.514278e-04
172     1.342740e-03
173     8.469968e+00
174     1.385142e-03
175              NaN
176     2.788082e-04
177     4.121600e-03
178     1.376987e-04
179     9.051605e-01
180     2.738746e-03
181     3.489344e-03
182     1.315218e-02
183     4.839042e-04
184     1.447428e-03
185     3.650308e-04
186              NaN
187     3.456818e-04
188     6.448607e-03
189     9.946126e-05
190     8.446151e-05
191     4.538616e+00
192     1.107606e-03
193     4.952208e-02
194              NaN
195              NaN
196     1.265362e-04
197              NaN
198     1.854956e+00
199     4.214501e-02
200     2.949246e-01
201     4.903377e-03
202     4.125000e-02
203     3.487029e+00
204     2.384186e-03
205     4.531200e-03
206     1.365498e-03
207     2.427556e-03
208     1.529600e-01
209     3.754675e-03
210     2.641874e-02
211     1.298066e-03
212     9.305232e-05
213     8.523598e-05
214     5.297321e-03
215     5.089497e-04
216     1.750577e-02
217     4.203520e-03
218     4.688204e-03
219     2.720506e+00
220     5.080526e-04
221     2.899848e-03
222     1.658509e-02
223     1.297223e-03
224     2.924450e+00
225     7.634133e-02
226     1.774291e-04
227     1.424819e-04
228     1.598140e-03
229     2.535916e-04
230     2.019915e+00
231     7.545941e-04
232     1.151899e-04
233     1.473840e-02
234     3.915966e-01
235     2.322197e-03
236     5.743383e-04
237     2.049719e-04
238     2.246821e-04
239     2.125395e-03
240     4.439907e-03
241     4.174193e-04
242     1.201019e-03
243     1.374602e-03
244     6.885131e+00
245     1.187339e-01
246     7.395142e-04
247     4.267324e-04
248     7.644389e-04
249     1.839890e-03
250     1.520255e-03
251     2.530372e-04
252     7.650989e-04
253     1.138551e-04
254     2.207481e-01
255     9.000588e-02
256     2.519170e+02
257     3.967285e-03
258     5.590982e-01
259     8.880939e-02
260     8.077412e-02
261     2.821738e-03
262     2.099843e+02
263     3.239898e+00
264     1.231436e-02
265     7.289261e-01
266     1.085200e-04
267     1.004909e-02
268     8.377245e+00
269     1.884408e-02
270     7.039729e-03
271     8.077412e-02
272              NaN
273     1.014467e-02
274     1.632596e-03
275     1.988368e-04
276     3.617320e-01
277     4.700965e-01
278     4.259840e-03
279     1.114104e-04
280     1.107606e-03
281              NaN
282     1.913898e-04
283     5.045567e-03
284     1.612558e-01
285     2.405487e-01
286     2.125633e-02
287     4.145855e+00
288     3.462099e-02
289     2.880859e-01
290     4.780053e-01
291     2.209365e-04
292     4.418729e-03
293     1.161622e+00
294     2.391338e+00
295     2.850235e-04
296     4.893040e-01
297     1.329622e-01
298     1.531145e-04
299     4.851755e-02
300     8.726032e-02
301     3.298734e+00
302     2.141818e-02
303     5.096468e-04
304     1.091463e-04
305     1.313150e+02
306     2.931218e-03
307     1.225401e-01
308     2.125000e-01
309     4.444961e-01
310     2.240136e+00
311     2.816856e+00
312     4.969219e+00
313     1.520255e-03
314     1.680554e-04
315     1.856489e-04
316     2.526845e+00
317     1.644349e+00
318     1.392319e-04
319     2.455642e-01
320     3.449931e-01
321     4.952208e-02
322     1.271121e-01
323     2.969557e-04
324     6.746263e-03
325     7.063921e-04
326     3.200136e-02
327     6.410783e-01
328     1.291534e-01
329     8.039894e-01
330     3.443287e+00
331     2.714398e-02
332     1.126231e-03
333     5.078241e-04
334     6.327749e-05
335     1.995704e-01
336     1.097394e-01
337     6.324642e-02
338     2.877642e-01
339     4.000000e-01
340     2.037838e+00
341     1.602062e-03
342     2.236742e-04
343     8.904067e-06
344     2.457992e-03
345     9.436810e-04
346     3.172154e-02
347     9.408417e-01
348     7.078325e+00
349     3.915966e-01
350     9.506227e+00
351     2.817725e-04
352     1.210239e-04
353     7.539881e-04
354     1.895943e-03
355     2.497843e-01
356     3.298734e+00
357     1.923069e-01
358     1.995704e-01
359     1.174214e-01
360     3.501153e+00
361     1.071100e-02
362     1.561058e-01
363     1.161622e+00
364     3.209842e-03
365     4.469419e-02
366     7.884714e-03
367     1.083246e-01
368     1.891513e-01
369     2.037009e-01
370     2.468761e+00
371     2.791890e-02
372     4.250742e-04
373     2.592068e-04
374     1.479290e-03
375     2.092627e-04
376     7.339142e-04
377     4.468392e-02
378     3.478229e+00
379     2.037838e+00
380     6.798632e-01
381     2.036095e-03
382     2.982865e-04
383     2.760556e-01
384     8.696296e-05
385     2.497843e-01
386     1.597441e+00
387     7.098418e-04
388     5.297321e-03
389     3.172154e-02
390     8.811310e-03
391     2.956462e-03
392     1.793175e-01
393     1.511392e+00
394     3.106591e-01
395     1.380741e+00
396     5.663981e-03
397     1.301324e+00
398     2.316817e-01
399     2.611816e-03
400     2.322549e-04
401     1.035040e-03
402     3.281312e-04
403     6.960829e-04
404     3.164418e-05
405     1.155817e-01
406     3.649186e-02
407     2.657750e-02
408     1.586574e-01
409     2.316817e-01
410     7.000000e-02
411     2.158604e-02
412     1.004311e-04
413     2.392085e-04
414     3.749103e-04
415     2.059937e-03
416     1.177528e+00
417     4.064265e+00
418     1.134398e+00
419     1.529600e-01
420     5.651021e+00
421     3.598323e-01
422     1.548776e+00
423     1.308944e+01
424     2.877642e-01
425     9.149345e-01
426     6.451232e-01
427     1.098710e-03
428     5.694929e-02
429     2.312299e+00
430     1.111870e-04
431     2.275831e-03
432     3.413746e-03
433     3.431490e-03
434     1.770268e-01
435     1.561058e-01
436     5.714741e-01
437     4.906775e-02
438     6.138548e-01
439     2.391338e+00
440     4.274875e-05
441     5.540741e-05
442     1.659996e-04
443     3.017501e-04
444     2.626271e-04
445     4.051657e-04
446     5.827772e-05
447     9.766586e-02
448     1.797932e+00
449     5.095338e-01
450     1.267598e+00
451     1.197677e+00
452     1.913898e+00
453     1.132536e-01
454     3.722221e+00
455     1.451130e-01
456     3.308020e-01
457     2.102998e+00
458              NaN
459     3.308020e-01
460     1.102854e+00
461     6.762565e-01
462     2.816856e+00
463     4.747179e-01
464     7.240401e+00
465     1.231348e-01
466     1.192931e-01
467     6.138548e-01
468     4.969219e+00
469     8.900329e+00
470     4.264017e-01
471     3.298734e+00
472     1.301324e+00
473     7.985250e-01
474     6.451232e-01
475     3.523295e-01
476     1.338968e+00
477     4.356178e-01
478     1.459070e+00
479     4.085984e-01
480     8.381879e-03
481     2.231662e-01
482     1.822917e-01
483     5.222229e-01
484     8.614936e+00
485     1.336806e-02
486     5.791430e-02
487     4.145855e+00
488     1.264762e+00
489     8.726032e-02
490     3.364265e+00
491     1.134398e+00
492     1.797932e+00
493     8.657911e-03
494     8.536836e-04
495     2.114170e-01
496     1.103659e+01
497     1.974832e+00
498     1.257751e-03
499     2.636619e+00
500     2.233235e-04
501     1.380741e+00
502     5.500393e-01
503     1.780975e-01
504     7.878161e-05
505     1.036435e-03
506     4.464000e-01
507     7.090379e-01
508     9.149345e-01
509     1.211669e-02
510     1.015987e+00
511     2.657776e-01
512     9.044173e-04
513     4.195318e-02
514     1.382828e-01
515     8.862189e-02
516     3.665055e+00
517     7.985250e-03
518     1.174214e-01
519              NaN
520     8.288175e-04
521     1.231348e-01
522     6.389121e-03
523     2.318761e+00
524     8.695721e-01
525     1.044922e+00
526     3.364265e+00
527     3.329374e-03
528     6.292867e-01
529     8.330587e-02
530              NaN
531              NaN
532     3.501153e+00
533     2.405487e-01
534     1.689347e+00
535     5.222229e-01
536     4.659860e-01
537     1.548776e+00
538     5.470208e-01
539     1.500160e-04
540     6.345662e-03
541     1.380741e+00
542     1.913898e+00
543     5.454668e-03
544     3.598323e-01
545     5.470208e-01
546     1.634984e-02
547              NaN
548     3.881086e+00
549     1.501642e+00
550     9.478393e-04
551     1.267598e+00
552     2.343993e-01
553     1.458333e-02
554     5.534959e-02
555     8.457004e-01
556     1.640903e+00
557     1.107107e-01
558     4.085984e-01
559     1.612558e-01
560     6.365333e+00
561     3.598323e-01
562     9.408417e-01
563     1.563411e-04
564     7.090379e-01
565     2.170401e+00
566     1.561058e-01
567     2.240136e+00
568     1.822917e-01
569     1.459070e+00
570     7.517809e-02
571     1.014576e-01
572     2.818469e-01
573     3.364265e+00
574              NaN
575              NaN
576     6.701426e+00
577     1.072225e+00
578     6.324642e-02
579     7.738930e-01
580     2.316817e-01
581     1.291534e-01
582     1.312307e-01
583     5.590982e-01
584     5.609907e+00
585     3.214366e-02
586     7.688002e+00
587     1.974832e+00
588     2.189894e-01
589     5.231481e+00
590     3.443287e+00
591     2.312299e+00
592     7.517809e-02
593     7.078325e+00
594     7.811039e-01
595     1.197677e+00
596     3.501153e+00
597     6.762565e-01
598     2.311206e-02
599     1.134398e+00
600     3.131189e+00
601     1.360857e-01
602     4.085984e-01
603              NaN
604     1.046867e-01
605     2.085614e-02
606     5.352334e-01
607     2.102998e+00
608     1.265306e+01
609     1.155817e-01
610     2.877642e-01
611     1.143909e+01
612     2.497843e-01
613     4.252442e+00
614     3.239391e-01
615     3.722221e+00
616     2.231662e-01
617     9.628824e-01
618     5.231481e+00
619     5.900065e+00
620     8.897544e-01
621     9.141270e-02
622     8.245613e-01
623     2.800363e-02
624     3.985038e+00
625     9.451585e+00
626     3.131189e+00
627     1.987580e+01
628     1.427956e-01
629     9.408417e-01
630     8.592073e-02
631     2.468761e+00
632     1.597441e+00
633     1.072225e+00
634     7.455023e-01
635     7.090379e-01
636     6.075660e-02
637     1.380741e+00
638     2.760556e-01
639     4.538616e+00
640     2.816856e+00
641     9.408417e-01
642     3.235051e+00
643     1.197677e+00
644     5.472540e+00
645     3.131189e+00
646     9.408417e-01
647     4.145855e+00
648     3.014471e-04
649     1.476023e-04
650     3.915387e-02
651     3.220675e-02
652     3.788665e-03
653     1.047486e-02
654     1.586574e-01
655     3.145865e-02
656     7.078325e+00
657     1.797932e+00
658     5.079117e+00
659     1.015987e+00
660     2.312299e+00
661     1.501642e+00
662     1.232112e+00
663     2.037009e-01
664     1.797932e+00
665     1.339272e-01
666     5.470208e-01
667     8.245613e-01
668     4.969219e+00
669     1.529600e-01
670     1.735843e+01
671     3.146828e+01
672     5.095338e-01
673     2.703871e-01
674     2.405487e-01
675     3.501153e+00
676     3.895937e-03
677     9.833474e-02
678     3.561225e-02
679     1.793484e-03
680     1.788801e-03
681     3.052694e-01
682     5.360153e-02
683     2.928044e-01
684     4.986150e-01
685     2.962442e-02
686     2.631393e-05
687              NaN
688     1.708540e-02
689     3.833831e-01
690     7.090379e-01
691     1.161622e+00
692     1.192931e-01
693     8.592073e-02
694     9.408417e-01
695     7.662345e-05
696     3.056772e-05
697     6.640625e-04
698     6.394869e-03
699     9.628824e-01
700     3.052694e-01
701     1.030586e-01
702     2.455642e-01
703     3.990204e-04
704     5.376000e+00
705     2.365034e-01
706     1.550840e-03
707     2.928044e-01
708     2.346421e-02
709     8.266438e-01
710     6.789234e-02
711              NaN
712              NaN
713     1.995704e-01
714     1.338968e+00
715     5.526068e-03
716     2.497843e-01
717     1.420820e+00
718     9.833474e-02
719     1.924402e-04
720     2.696614e-01
721     2.576780e+00
722     2.684005e-05
723     3.007250e-03
724              NaN
725     3.749192e-04
726              NaN
727     1.597441e+00
728     7.278362e+00
729     5.717212e-02
730     1.860544e-01
731     5.525033e-02
732     9.531423e-02
733     1.241733e-04
734     5.867503e-01
735     3.656887e-02
736     1.227690e-04
737     3.613730e-02
738              NaN
739     2.399459e-04
740     9.408417e-01
741     1.134398e+00
742     9.778981e-02
743     1.363601e+00
744     1.298506e+01
745              NaN
746     3.199606e-01
747     1.927627e-03
748     1.252747e-01
749     3.395492e-04
750     3.947660e-02
751              NaN
752     4.986150e-01
753     7.712566e-02
754     2.365034e-01
755              NaN
756     6.341130e-03
757     6.101367e-05
758     2.468761e+00
759     2.302064e-01
760     9.495018e-05
761     4.605030e-02
762     7.069389e-03
763     9.628824e-01
764     2.037009e-01
765     4.000000e-01
766     1.812418e+00
767     1.779859e+00
768     5.983747e-01
769     5.983997e-02
770     3.378186e-01
771     4.295680e-03
772     1.841623e-02
773     4.722858e-02
774     7.832241e-02
775              NaN
776     6.459958e-01
777     1.232112e+00
778     2.636619e+00
779     2.180102e+01
780     1.030586e-01
781     1.941180e-02
782     2.704572e-03
783     1.539282e-02
784     9.833474e-02
785     9.136907e-04
786     2.826285e-04
787     2.316817e-01
788     4.085984e-01
789              NaN
790     1.310941e+02
791     3.881086e+00
792     2.657776e-01
793     1.338968e+00
794     4.356178e-01
795     1.349273e-01
796     8.436928e+00
797     6.421752e-02
798     2.071255e-01
799     6.229013e-02
800     1.728355e-01
801     1.793175e-01
802     3.584836e+00
803     1.443575e-02
804     1.744045e+00
805              NaN
806     4.878298e-05
807     8.655778e-03
808     2.071255e-01
809     5.248346e-04
810     1.939064e-03
811              NaN
812     5.470208e-01
813     7.062698e-04
814              NaN
815              NaN
816     7.751958e-04
817     7.289261e-01
818     9.837773e-01
819     5.914720e-04
820     5.095338e-01
821     1.828180e-02
822     1.822917e-01
823     1.046867e-01
824     3.665055e+00
825     9.408417e-01
826     8.295973e-02
827     1.291534e-01
828     1.598145e-01
829     4.002977e-02
830     7.576193e-05
831     1.402771e-04
832     8.919405e-01
833     1.179703e-05
834     2.067539e-03
835     7.397160e-01
836     2.050400e-03
837     2.288304e-05
838     5.037716e-01
839     2.570151e-04
840     1.802042e-04
841     2.242922e-05
842     1.314212e-03
843     8.755657e-04
844     3.169538e-04
845     2.053861e-04
846     6.011492e-04
847     3.772739e-04
848     6.881624e-02
849     1.160040e-01
850     9.165685e-03
851     1.586574e-01
852     2.497843e-01
853     5.138993e-03
854     2.685547e-03
855     2.240136e+00
856     1.058676e-03
857     3.691565e+00
858     4.433130e-02
859              NaN
860     1.236230e-03
861     5.039882e-04
862     6.234144e-04
863     2.989691e-01
864     1.342593e-02
865     3.917480e-04
866     1.041561e-04
867     1.500000e-01
868     5.769360e-03
869     8.849477e-03
870              NaN
871     1.584798e+00
872     1.447428e-03
873     5.137697e-04
874     1.227026e-02
875     2.552585e-04
876     3.058607e-05
877     5.370750e-04
878     1.186973e-04
879     1.246808e-02
880     1.204378e-02
881     2.081204e-01
882     2.682575e-04
883     2.293587e-03
884     2.351534e-04
885     9.609443e-05
886     3.422533e-02
887     1.144747e+00
888     5.486968e-01
889     3.779087e-02
890     2.271769e-04
891     2.316550e-01
892     1.108732e-01
893     9.826224e-04
894     8.754510e-05
895     7.098418e-04
896     1.376987e-04
897     6.230339e-03
898     1.459010e-04
899     6.658435e-05
900     5.625205e-04
901     3.623387e-04
902     3.636812e-01
903     2.566360e-04
904     1.044277e-02
905     8.242435e-03
906     3.559836e+00
907              NaN
908     2.645388e-04
909     1.179998e-03
910     2.633409e-04
911     8.254423e-05
912     4.942854e-03
913     3.090467e-04
914     4.011539e-02
915     4.618143e-03
916     4.890147e-01
917     2.761082e-01
918     1.066873e-04
919     2.818817e-04
920     4.511507e-04
921     1.098710e-03
922     3.025920e+00
923     1.505067e-01
924     2.109686e-03
925     3.194331e-04
926     1.583980e+00
927     9.319607e-01
928     2.726153e-04
929     4.075520e-03
930     2.126998e-04
931     3.199399e-03
932     7.183429e-04
933     2.061559e-03
934     1.790756e-02
935     1.145567e-04
936     1.265362e-04
937     3.449352e-03
938     1.847114e+00
939     1.536608e-04
940     2.369046e-03
941     2.724333e+01
942     4.190342e-04
943     2.093629e-02
944     4.410342e-03
945     2.497843e-01
946     4.112576e-03
947     3.031773e-01
948     7.024874e-04
949     1.365498e-03
950     1.102854e+00
951     2.170401e+00

In [11]:
df["pl_type"] = df["Score_roch"].apply(lambda x: "Rocheuse" if x > 3.5 else "Gazeuse/Mixte")
df["pl_type"].value_counts()

C:\Users\berna\AppData\Local\Temp\ipykernel_13096\1822608203.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["pl_type"] = df["Score_roch"].apply(lambda x: "Rocheuse" if x > 3.5 else "Gazeuse/Mixte")

pl_type
Gazeuse/Mixte    5652
Rocheuse          501
Name: count, dtype: int64

In [12]:
df["sim_earth"] = (
    (1 - np.abs((df["pl_rade"] - 1) / (df["pl_rade"] + 1))) ** 0.57 *
    (1 - np.abs((df["pl_dens"] - 5.51) / (df["pl_dens"] + 5.51))) ** 1.07 *
    (1 - np.abs((df["Gravity_G_earth"] - 1) / (df["Gravity_G_earth"] + 1))) ** 0.70 *
    (1 - np.abs((df["pl_eqt"] - 288) / (df["pl_eqt"] + 288))) ** 5.58
) ** 0.25

C:\Users\berna\AppData\Local\Temp\ipykernel_13096\4252760722.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["sim_earth"] = (

In [14]:
df["sim_earth"].isna().sum()

np.int64(1661)

In [15]:
df["pl_rade"].isna().sum()

np.int64(50)

In [16]:
df["pl_dens"].isna().sum()

np.int64(139)

In [17]:
df["Gravity_G_earth"].isna().sum()

np.int64(74)

In [18]:
df["pl_eqt"].isna().sum()

np.int64(1563)

In [19]:
def impute_planets(df, max_iter=10):
    df = df.copy()

    for _ in range(max_iter):
        before_na = df[["Gravity_G_earth", "pl_dens", "pl_rade"]].isna().sum().sum()

        # g = rho * R
        mask_g = df["Gravity_G_earth"].isna() & df["pl_dens"].notna() & df["pl_rade"].notna()
        df.loc[mask_g, "Gravity_G_earth"] = df.loc[mask_g, "pl_dens"] * df.loc[mask_g, "pl_rade"]

        # rho = g / R
        mask_d = df["pl_dens"].isna() & df["Gravity_G_earth"].notna() & df["pl_rade"].notna()
        df.loc[mask_d, "pl_dens"] = df.loc[mask_d, "Gravity_G_earth"] / df.loc[mask_d, "pl_rade"]

        # R = g / rho
        mask_r = df["pl_rade"].isna() & df["Gravity_G_earth"].notna() & df["pl_dens"].notna()
        df.loc[mask_r, "pl_rade"] = df.loc[mask_r, "Gravity_G_earth"] / df.loc[mask_r, "pl_dens"]

        after_na = df[["Gravity_G_earth", "pl_dens", "pl_rade"]].isna().sum().sum()

        # stop si plus aucun progrès
        if after_na == before_na:
            break

    return df

In [ ]:
#def impute_planets(df):
#    df = df.copy()

##    # -------- PASS 1 --------
#    df["Gravity_1"] = np.where(
        df["Gravity_G_earth"].isna() & df["pl_dens"].notna() & df["pl_rade"].notna(),
        df["pl_dens"] * df["pl_rade"],
        df["Gravity_G_earth"]
    )

#    df["dens_1"] = np.where(
#        df["pl_dens"].isna() & df["Gravity_G_earth"].notna() & df["pl_rade"].notna(),
#        df["Gravity_G_earth"] / df["pl_rade"],
#        df["pl_dens"]
 #    )

#    df["rade_1"] = np.where(
#        df["pl_rade"].isna() & df["Gravity_G_earth"].notna() & df["pl_dens"].notna(),
#        df["Gravity_G_earth"] / df["pl_dens"],
 #       df["pl_rade"]
#     )

    # -------- PASS 2 --------
#    df["Gravity_2"] = np.where(
#        df["Gravity_1"].isna() & df["dens_1"].notna() & df["rade_1"].notna(),
#        df["dens_1"] * df["rade_1"],
#        df["Gravity_1"]
#     )

#    df["dens_2"] = np.where(
#        df["dens_1"].isna() & df["Gravity_1"].notna() & df["rade_1"].notna(),
#        df["Gravity_1"] / df["rade_1"],
#        df["dens_1"]
 #    )

#    df["rade_2"] = np.where(
#        df["rade_1"].isna() & df["Gravity_1"].notna() & df["dens_1"].notna(),
#        df["Gravity_1"] / df["dens_1"],
#        df["rade_1"]
#     )

    # -------- PASS 3 --------
#    df["Gravity_3"] = np.where(
#        df["Gravity_2"].isna() & df["dens_2"].notna() & df["rade_2"].notna(),
#        df["dens_2"] * df["rade_2"],
#        df["Gravity_2"]
#     )

#    df["dens_3"] = np.where(
        df["dens_2"].isna() & df["Gravity_2"].notna() & df["rade_2"].notna(),
        df["Gravity_2"] / df["rade_2"],
        df["dens_2"]
    )

#    df["rade_3"] = np.where(
#        df["rade_2"].isna() & df["Gravity_2"].notna() & df["dens_2"].notna(),
#        df["Gravity_2"] / df["dens_2"],
#        df["rade_2"]
#     )

    # -------- PASS 4 --------
 #    df["Gravity_4"] = np.where(
  #       df["Gravity_3"].isna() & df["dens_3"].notna() & df["rade_3"].notna(),
#         df["dens_3"] * df["rade_3"],
 #        df["Gravity_3"]
#     )

 #    df["dens_4"] = np.where(
 #        df["dens_3"].isna() & df["Gravity_3"].notna() & df["rade_3"].notna(),
 #        df["Gravity_3"] / df["rade_3"],
 #        df["dens_3"]
 #    )

 #    df["rade_4"] = np.where(
 #        df["rade_3"].isna() & df["Gravity_3"].notna() & df["dens_3"].notna(),
  #       df["Gravity_3"] / df["dens_3"],
  #       df["rade_3"]
 #    )

  #   # -------- FINAL --------
  #   df["Gravity_final"] = df["Gravity_4"]
  #   df["pl_dens_final"] = df["dens_4"]
  #   df["pl_rade_final"] = df["rade_4"]

  #   return df

In [20]:
df = impute_planets(df)

In [21]:
df["sim_earth"] = (
    (1 - np.abs((df["pl_rade"] - 1) / (df["pl_rade"] + 1))) ** 0.57 *
    (1 - np.abs((df["pl_dens"] - 5.51) / (df["pl_dens"] + 5.51))) ** 1.07 *
    (1 - np.abs((df["Gravity_G_earth"] - 1) / (df["Gravity_G_earth"] + 1))) ** 0.70 *
    (1 - np.abs((df["pl_eqt"] - 288) / (df["pl_eqt"] + 288))) ** 5.58
) ** 0.25

In [22]:
df["pl_rade"].isna().sum()

np.int64(50)

In [23]:
df["sim_earth"].isna().sum()

np.int64(1599)

In [24]:
df["pl_insol"].isna().sum()

np.int64(1840)

In [25]:
df["pl_insol_calc"] = df["st_lum"] / (df["pl_orbsmax"] ** 2)

# Remplacer les valeurs manquantes uniquement
df["pl_insol"] = df["pl_insol"].fillna(df["pl_insol_calc"])

In [26]:
df["pl_insol"].isna().sum()

np.int64(534)

In [27]:
df["pl_eqt"] = df["pl_eqt"].fillna(255 * (df["pl_insol"] ** 0.25))

In [28]:
df["pl_eqt"].isna().sum()

np.int64(863)

In [29]:
df["sim_earth"] = (
    (1 - np.abs((df["pl_rade"] - 1) / (df["pl_rade"] + 1))) ** 0.57 *
    (1 - np.abs((df["pl_dens"] - 5.51) / (df["pl_dens"] + 5.51))) ** 1.07 *
    (1 - np.abs((df["Gravity_G_earth"] - 1) / (df["Gravity_G_earth"] + 1))) ** 0.70 *
    (1 - np.abs((df["pl_eqt"] - 288) / (df["pl_eqt"] + 288))) ** 5.58
) ** 0.25

In [30]:
df["sim_earth"].isna().sum()

np.int64(911)

In [31]:
df["eau_possible"] = df["pl_insol"].between(0.5, 1.5).astype(int)
df["eau_possible"].isna().sum()

np.int64(0)

In [32]:
df[["eau_possible","pl_type"]].value_counts()

eau_possible  pl_type
0             Gazeuse/Mixte    5457
              Rocheuse          487
1             Gazeuse/Mixte     195
              Rocheuse           14
Name: count, dtype: int64

In [33]:
df["st_spectype"].value_counts()

st_spectype
G0 V                 65
G5 V                 62
K0                   61
M0 V                 55
G5                   54
M1 V                 50
K0 V                 44
G                    44
F8 V                 43
K2 V                 43
G8 V                 42
G9 V                 41
G2 V                 40
K3 V                 40
K0 III               39
G3 V                 38
F8                   36
G0                   36
K                    35
G6 V                 30
M                    27
F7 V                 25
K4 V                 25
F                    25
G1 V                 24
K7 V                 24
M2.5 V               23
K1 V                 22
F6 V                 22
K V                  22
G V                  22
G4 V                 21
M3.0 V               21
F9                   20
M0                   20
M4                   20
G2                   20
K5 V                 19
K1 III               19
M3.5 V               18
M1.5 V               18
M4.5 V               18
M2 V                 18
M1                   16
M3                   16
F5 V                 16
G3                   16
M V                  16
M3 V                 15
K1                   14
G9                   14
G4                   13
G8                   13
K2.5 V               13
K2                   13
K2 III               12
K3                   12
K7                   12
M1.0 V               12
F9 V                 11
K6 V                 11
F6                   11
G8 IV                11
K0 IV                10
K5                   10
M4 V                 10
M5.5 V               10
M2                    9
K4                    9
M3.5                  8
F5                    8
G7 V                  8
F7                    8
G7                    8
G6                    7
K1 IV                 7
M2.5                  7
G5 IV                 7
M0.0 V                7
M8.0 V                7
F V                   7
M0.5 V                7
K0 III-IV             7
G5V                   6
G2 IV                 6
G3 IV                 6
K0.0 V                6
G8 III                6
M5.0 V                6
M2.0 V                6
G5 IV/V               6
G0 IV                 6
K2V                   6
K3 III                5
M3.0                  5
G8/K0 IV              5
K8 V                  5
K3 IV                 5
G0V                   5
G3 IV-V               5
K4 III                5
G5IV                  5
K0V                   5
G2/G3 V               5
G9 III                5
F9.5 V                5
F3 V                  4
M2.5V                 4
K5 III                4
A5 V                  4
K4.5 V                4
WD                    4
G8.5V                 4
K0.5 V                4
M0.0                  4
M6 V                  4
G1                    4
M3.5-4 V              4
M0.5                  4
M2V                   4
K3V                   4
M4.0 V                4
K2 III-IV             4
K3.5 V                4
G3/G5 V               3
G9 V CN+1             3
M5                    3
F4                    3
F6 IV-V               3
A                     3
M5 V                  3
F4 V                  3
G1.5 V                3
M(6.1 +/- 0.7) V      3
G2V                   3
A8 V                  3
K0 III/IV             3
F7/F8V                3
G4 IV                 3
F6 IV                 3
G8 IV/V               3
G7 III                3
F7V                   3
M7.0 V                3
K7V                   3
K2 II                 2
G3/5V                 2
G2/3V                 2
B                     2
K7/M0 V               2
M1 III                2
G8 IV (+ G)           2
K0 IV-V               2
G2 IV-V               2
M4.0                  2
B9 V                  2
K9 V                  2
K6                    2
M4 +/- 0.5            2
G9 IV                 2
F9-F9.5               2
K6-K7                 2
K4/5V                 2
K3 VC                 2
K5.5                  2
M3.0V                 2
K7/M0                 2
F1 V                  2
K4.5                  2
M4.5+/-0.5            2
F2                    2
M1.0                  2
G3 III                2
G8 III/IV             2
G5 III                2
K7.5 V                2
F9 IV                 2
A2 V                  2
M3.5+/-0.5            2
F5V-G0V               2
G7 IV                 2
F8 IV                 2
F0                    2
K2 III/IV             2
A5V                   2
M1.5V                 2
K0/1 III              2
M0 III                2
DC                    2
F9V                   2
K1III(+M)             2
G3 IV/V               2
M0&plusmn;0.5         2
M2&plusmn;0.5         2
K7e V                 1
M2/3 V                1
G8/K0                 1
G0/2 V                1
K1 IIIb Fe-0.5        1
F8 IV/V               1
M8.5                  1
K1/2III               1
K1 IV-V               1
G1-1.5 V              1
M7.25                 1
K2III                 1
DQ                    1
L1.5                  1
M7                    1
sdBV                  1
A8 III                1
M2 III                1
M6.5+/-0.5            1
A5                    1
M1.5                  1
K4/5 V                1
M3.5 +/- 1.0          1
G9/K0                 1
M5V                   1
K1/2 V                1
G8/9 IV               1
M6                    1
M3.5 Ve               1
M1.0+/-0.5            1
F2 V                  1
K1.5+/-1              1
G3V                   1
M5.0+0.5-0.5          1
G8/G9                 1
M5.5+/-0.5            1
K1/2V                 1
K7-M0 V               1
G1/2 V                1
B9 Vne                1
A1 IV-V               1
B2 IV                 1
K0 IV/V               1
K2 VC                 1
G3/5 V                1
A8                    1
B9.5-A0               1
K6-M1                 1
K3-K4 V               1
F3                    1
M6.5                  1
A0 V                  1
F9 D                  1
M2.5 III              1
G5 III/IV             1
M0.5-1.0 V            1
G0Vvar                1
G8/K0 III             1
G0/1 V                1
Am C                  1
M0V:                  1
K1-K2                 1
G1 IV                 1
M4.5                  1
K3/4 IV               1
M4 +/- 0.5 V          1
K9 V/M0 V             1
M2.5e                 1
M9                    1
M0.5 Ve               1
Be9.5/AO              1
M3+/-1                1
M0.5+/-0.5 V          1
K1/K2 V               1
G9 IV-V               1
G2/G3 IV/V            1
M5.0                  1
M5.5/M6               1
M2V:                  1
G0 VI                 1
M3.3                  1
K1 V(P)               1
K2 IV                 1
G8V                   1
K1V                   1
G7 IV/V               1
G2/3 V                1
M4.0+/-0.5            1
A7 V                  1
G6 IV                 1
M8                    1
G7 IV-V               1
G7 V Fe-1 CH-0.5      1
F5V                   1
K1.5 V                1
M1+/-0.5              1
M9-L1                 1
K5/M0V                1
B2.5 V                1
G2/G3                 1
K5V                   1
F8/G0 IV/V            1
G6/8 V                1
G8 V+                 1
F5-F8 V               1
M7.5                  1
G6 III                1
G4 II-III             1
M2+/-0.5              1
A9/F0                 1
F9/G0                 1
G1V                   1
M4.5 Ve               1
m3 V                  1
M4.5V-M5V             1
K1 III-IV             1
F5 IV                 1
F8 V CH+0.4           1
K5e                   1
K0IIIvar              1
M2.0V                 1
B9 IV                 1
M4+/-0.5              1
M4.0&plusmn;1.0 V     1
M(3.5+/-0.5) V        1
M 4.5V                1
A5-A6                 1
F0 IV                 1
A8Ve                  1
T8.5                  1
M1&plusmn;0.5         1
Name: count, dtype: int64

In [34]:
def map_spectral_type(x):
    if pd.isna(x):
        return "Unknown"
    
    x = str(x).upper()

    if "WD" in x or "DQ" in x or "DC" in x:
        return "White Dwarf"

    if "O" in x:
        return "O"
    if "B" in x:
        return "B"
    if "A" in x:
        return "A"
    if "F" in x:
        return "F"
    if "G" in x:
        return "G"
    if "K" in x:
        return "K"
    if "M" in x:
        return "M"

    return "Other"


df["st_spectype_group"] = df["st_spectype"].apply(map_spectral_type)

In [35]:
df["st_spectype_group"].value_counts()

st_spectype_group
Unknown        3845
G               778
K               645
M               551
F               287
A                26
B                11
White Dwarf       7
Other             2
O                 1
Name: count, dtype: int64